### ISSUE TITLE
Add support for playlist images to get_images()

### ISSUE THREAD

**Issue by pft** [mopidy/mopidy-spotify#100]
Spotify playlists may have images associated,  and made available through their api.

They cannot currently be retrieved with `get_images()`. Parsing the URI already errors out.

```
ValueError: Could not parse u'spotify:user:accountname:playlist:2BCH....nws1' as a Spotify URI
```

**Comment by jaedb** [comment]
+1

**Comment by kingosticks** [comment]
For anyone looking at doing this, note that the difference with playlists is that they require authorisation to access.

**Comment by adamcik** [comment]
3e82e5457b5ae4afd1b328719c1f7313630ccfa0 fixed this.
