### ISSUE TITLE
Slow/unreliable Artists and albums views

### ISSUE THREAD

**Issue by gontanon** [mopidy/mopidy-spotify#101]
I'm running:

```
osmc@pi:~$ dpkg -l | grep mopi
ii  libspotify12                          12.1.103-0mopidy1                 armhf        Library for using the Spotify music streaming service
ii  mopidy                                2.0.0-1                           all          music server with support for MPD/HTTP clients
ii  mopidy-podcast                        1.1.2-1                           all          Mopidy extension for searching and browsing podcasts
ii  mopidy-scrobbler                      1.1.1-3                           all          Mopidy extension for scrobbling music to Last.fm
ii  mopidy-spotify                        3.0.0-0mopidy1                    all          Mopidy extension for playing music from Spotify
ii  mopidy-spotify-tunigo                 1.0.0-0mopidy1                    all          Mopidy extension for providing the browse feature of Spotify
ii  python-cachetools                     1.0.0-1~bpo70+0mopidy1            all          extensible memoizing collections and decorators for Python
ii  python-cffi                           1.1.2-1~bpo70+0mopidy2            all          Foreign Function Interface for Python calling C code
ii  python-cffi-backend                   1.1.2-1~bpo70+0mopidy2            armhf        Foreign Function Interface for Python calling C code - backend
ii  python-ipaddress                      1.0.14-1~bpo70+0mopidy1           all          Backport of Python 3 ipaddress module (Python 2)
ii  python-spotify                        2.0.5-0mopidy1                    armhf        Python bindings for libspotify (Python 2)
```

Also, two frontends, mopify and spotmop:

```
osmc@pi:~$ pip list | grep -i mopi
Mopidy (2.0.0)
Mopidy-Moped (0.6.4)
Mopidy-Mopify (1.5.16)
Mopidy-MusicBox-Webclient (2.0.0)
Mopidy-Podcast (1.1.2)
Mopidy-Scrobbler (1.1.1)
Mopidy-Spotify (3.0.0)
Mopidy-Spotify-Tunigo (1.0.0)
Mopidy-Spotmop (2.5.18)
```

For what it's worth this is running on a Raspberry Pi 2. I've been experiencing the following ever since I installed everything a few months ago as well as a now after a recent upgrade. This happens in both front-ends, that's why I'm reporting on mopidy-spotify:

   * Both the Artists and Albums views take ages to load completely, over a minute.
   * Sometimes, they come out empty.
   * Sometimes they come out with very incomplete/partial results.
   * When the Artists/Albums list are empty or incomplete, reloading doesn't change the result.

In contrast, the Playlists, New releases, Browse and Featured playlists views in Mopify all work fast and flawlessly.

Please let me know if you need me to collect debug information. I've run mopidy with `--save-debug-logs` but nothing in the log stands out as relevant, I'll be happy to post the file though.

**Comment by kingosticks** [comment]
You've chosen two webclients that both do external requests to the Spotify HTTP API to extend the features/metadata beyond what Mopidy provides. Are you sure the data that is slow to load is coming from Mopidy or is it coming from Spotify directly? Do you see the same issues with traditional clients that don't use the Spotify HTTP API e.g. Mopidy-Mobile, Mopidy-Musicbox-Webclient, Mopidy-Moped etc.

Also, you can use the command `mopidy deps` to more easily get the versions of all your installed extensions.

**Comment by gontanon** [comment]
Thanks for the quick reply. I suppose that on Mobile, Musicbox-Webclient and Moped the equivalent to Albums would be "Spotify/Top Albums/Personal", is that right? I can't see any other view that would equate to my list of Albums. Yet, this view is empty in all three of those webclients.

**Comment by gontanon** [comment]
I'm looking at this snippet from the mopify Artists view:

https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/app/music/library/artists/artists.controller.js#L49

Seems like it generates the Artists list by loading the list of tracks and getting the artist for each of them. I can imagine how that may be slow if one has thousands of saved tracks :-\.

Is this a mopidy or spotify-http call?:

```
            Spotify.getSavedUserTracks({
                limit: 50,
                offset: offset
            }).then(function(response){
```

**Comment by gontanon** [comment]
Ok, I've found it in the Mopify source code, it does fetch the Albums and Artists from the Spotify HTTP API. I'll close this and report/ask on the mopify tracker.

Thanks!

**Comment by kingosticks** [comment]
Yeh, it's the Spotify Web API. Mopidy (via libspotify) has no access to the Spotify "My Music" collection.

Those "Top lists"  are something different but we've had problems with them lately, possibly another casualty of the recent Spotify/libspotify API issues but I'm not 100% sure what the state of those are.
