### ISSUE TITLE
spotify unlimited accounts ?

### ISSUE THREAD

**Issue by Sigzegv** [mopidy/mopidy-spotify#103]
As said in documentation "A Spotify Premium subscription. Mopidy-Spotify will not work with Spotify Free, just Spotify Premium."

But it seems older spotify unlimited accounts are not supported, is there a reason ? (thoses accounts were sold half the premium price some years ago)

**Comment by kingosticks** [comment]
Whatever the reason it's a restriction enforced by Spotify's libspotify library and I'm afraid there is nothing we can do about it. You can try and bring it up with them.

**Comment by Sigzegv** [comment]
ok, thnx for the info

**Comment by jodal** [comment]
libspotify didn't work with Spotify Unlimited either. It has only ever worked with Spotify Premium.
