### ISSUE TITLE
[Question] Where are the auth scopes defined?

### ISSUE THREAD

**Issue by jaedb** [mopidy/mopidy-spotify#105]
I'm trying to expand the authorization scopes requested by `Mopidy-Spotify` but I cannot see where this is defined. Or is this something defined in `libspotify`?

**Comment by adamcik** [comment]
There are no auth scopes in libspotify, it doesn't use any OAuth or anything like that. We keep using it as it is the only way to get streaming.

https://github.com/lfcabend/mopidy-spotify-web might be what you are looking for. It does everything but the streaming, relying on this backend for that part only.

**Comment by jaedb** [comment]
@adamcik Cool, thanks. I'm actually developing a web interface (https://github.com/jaedb/spotmop)[Spotmop] however would like to utilize `Mopidy-Spotify`'s authentication layer. I am getting an error saying that the necessary scope has not been authorized.

How does `Mopidy-Spotify` define the scopes for the authorization request?

**Comment by adamcik** [comment]
We just use libspotify which predates the web APIs. We don't request any auth scopes.

If I remember right Spotmop like Mopify which I believe you started off from (not that I see that credited any more) use the Spotify web APIs directly. This has nothing to do with the auth layer in Mopidy-Spotify.

Anyway I don't think I can help you with this, what you are looking for is somewhere in the code you got off Mopify.

**Comment by jaedb** [comment]
@adamcik Ok, that's what I suspected as I couldn't find the relevant code. 

As a side-note, since v2.4 `Spotmop` is an original build with a significant deviation (both in code and concept) from `Mopify`. This is why I have removed the credit to `Mopify`.
