### ISSUE TITLE
Spotify Connect

### ISSUE THREAD

**Issue by yannik-b** [mopidy/mopidy-spotify#107]
Hi,

is it possible to integrate mopidy-spotify into Spotify Connect?

https://developer.spotify.com/spotify-connect-hardware-partners/

They say there "hardware partners", but why shouldn't it be possible for Spotify to add mopidy-spotify?

Best regards, Yannik Buerkle

**Comment by adamcik** [comment]
Please see #14 for the history on this, but the short answer is no it is not currently possible.
