### ISSUE TITLE
local/media_dir must be set??

### ISSUE THREAD

**Issue by kriiiss** [mopidy/mopidy-spotify#111]
Hi guys, 

I am new to all of this and wanted to know what I am doing wrong. I am trying to install mopidy with spotify and ncmpcpp and have followed several guides online.

[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = mopidy.log
config_file =

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs =
  $XDG_MUSIC_DIR|Music
  ~/|Home
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[local]
enabled = false  ; Extension disabled due to config errors.
library = json
media_dir =  ; Must be set.
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt

[spotify]
enabled = true
username = ******
password = ********
bitrate = 320
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries =

I get this 

INFO     Starting Mopidy 2.0.0
INFO     Loading config from builtin defaults
INFO     Loading config from /Users/*********/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: spotify, mpd, http, stream, m3u, softwaremixer, file
INFO     Disabled extensions: local
WARNING  Found local configuration errors, the extension has been automatically disabled:
WARNING    local/media_dir must be set.
WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, SpotifyBackend
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Logged in to Spotify in offline mode
INFO     Logged in to Spotify in online mode
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     Starting GLib mainloop

Thanks

**Comment by ZenithDK** [comment]
Do the directories you configured in media_dirs [file] exist?
Do you have a $XDG_MUSIC_DIR?
You should be able to open this file: `~/.config/user-dirs.dirs` and see what it is configured to.

**Comment by yannik-b** [comment]
@ZenithDK
The warning is about [local], not about [file] 

So the line `media_dir = ;` under the headline [local] has to be extented to - for example - `media_dir = $XDG_MUSIC_DIR;`

**Comment by ZenithDK** [comment]
Sorry, I should have been more clear: I know that it's empty under local, but since it's listed as disabled, should it complain? I was thinking it was a copy/paste error and that it was the file path it complained about.
But yeah, try setting media_dir to something instead of leaving it empty, or - just remove everything besides the `enabled = false` - that should also work I would think.

**Comment by kriiiss** [comment]
@ZenithDK I ran ~/.config/user-dirs.dirs and it does not exist

I will try to reinstall everything again tomorrow

Thanks

**Comment by kingosticks** [comment]
The official documentation is the best source of information regarding installation and setup. It recommends to only define config entries that you want to set differently from the defaults. 

If you are not intending to use the local backend then explicitly disable it in your config. If you want to use the local backend then setting local/media_dir might make things clearer. The default value for local/media_dir depends on your particular operating system.

In any case, this is not a mopidy-spotify issue. If you are still having problems with the local backend please open a new topic at http://discuss.mopidy.com. Thanks.
