### ISSUE TITLE
mopidy and systemd can't get along

### ISSUE THREAD

**Issue by fanzila** [mopidy/mopidy-spotify#112]
Hey there, 
Under Debian Jessie, starting mopidy as a service will fail because of segfault  in libspotify.so.12.1.51 : 

```
# /etc/init.d/mopidy start
==> /var/log/kern.log <==
Jul 29 07:29:24 rmsbox kernel: [ 1664.008842] mopidy[8400]: segfault at 0 ip 00007f6336b95b9e sp 00007f632effb6e0 error 4 in libspotify.so.12.1.51[7f63369f8000+25c000]
```
but starting mopidy 'manually' # /usr/bin/mopidy --config /etc/mopidy/mopidy.conf will have no problem

**Comment by fanzila** [comment]
resolved by reinstalling everything with apt

**Comment by mar-v-in** [comment]
This problem occurs when /var/cache/mopidy is not owned by mopidy user (or whatever user is defined in your systemd config).

**Comment by fanzila** [comment]
Thanks Marvin!
