### ISSUE TITLE
Getting constant UNABLE_TO_CONTACT_SERVER errors

### ISSUE THREAD

**Issue by sl-digital** [mopidy/mopidy-spotify#113]
I started experiencing an issue where mopidy-spotify will log in offline mode, then switch to online, then let me play one or two tracks before throwing the  "UNABLE_TO_CONTACT_SERVER" error.  After that the player becomes unresponsive.

Is this an error with libspotify logging in to the Spotify servers or something else?  I'm unable to find any useful information on what this error refers to.

**Comment by jodal** [comment]
The error is from libspotify, yes, and probably due to Spotify issues. It is not something we can do anything about.

On my own system, this started 2016-08-08 18:54:39 and ended about 2016-08-09 17:34, UTC+2. Hopefully the issue has been resolved for you too.
