### ISSUE TITLE
Spotify stutters when changing song

### ISSUE THREAD

**Issue by ddavy** [mopidy/mopidy-spotify#120]
Hi,

I have the same issue as described in #26 . When I change the song, it stutters. I've already installed pyspotify with pip, but it didn't fix the issue.
- Installed versions (`mopidy deps`):
[http://pastebin.com/507jjV2u](http://pastebin.com/507jjV2u)

- Mopidy config:
[http://pastebin.com/tasP72PY](http://pastebin.com/tasP72PY)

Any help is appreciated.

Thanks

**Comment by yannik-b** [comment]
Hi, I don't use mopidy-spotify anymore bc no Premium :-1:, so I can't see this issue by myself, but I've got this problem too in official Spotify Linux Client.
So I think this isn't a problem of mopidy-spotify but from sound decoder or something like that...

**Comment by ddavy** [comment]
@yannik-b You might be right. I changed the [audio] output to alsasink and there seems to be less stuttering. I also removed pulseaudio as I read somewhere else this might interfere with gstreamer. Not sure what might've fixed it. I tested the alsasink output before with the same stuttering result, so I guess it has something to do with pulseaudio.
