### ISSUE TITLE
Session must be logged in an online

### ISSUE THREAD

**Issue by buttonfreak** [mopidy/mopidy-spotify#123]
The plugin suddenly stopped working. From the log;
`2016-11-25 07:26:57,170 ERROR [512:SpotifyEventLoop] spotify.session: Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
2016-11-25 07:26:57,174 INFO [512:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in offline mode`

Lookups from the webinterface also fail;
`2016-11-25 07:29:37,532 INFO [512:SpotifyBackend-14] mopidy_spotify.lookup: Failed to lookup "spotify:user:[username]:playlist:6BSXtythXjxuRwcl6DN7Or": Session must be logged in and online to load objects: <ConnectionState.OFFLINE: 4>`

The account used on device is premium, valid and I can use it from the app.

**Comment by buttonfreak** [comment]
It seems there is an issue at Spotify.. Spotify webinterface  does not work as well.

**Comment by kingosticks** [comment]
Sounds like there is nothing to do there. Incidentally it does work for me, perhaps this is a region specific problem.
