### ISSUE TITLE
pyspotify<1.999,>=1.9 required, but found pyspotify 2.0.5

### ISSUE THREAD

**Issue by SilentMF** [mopidy/mopidy-spotify#125]
Just upgraded from Debian Wheezy to Jessie. I installed Mopidy-Spotify from APT and keep getting the following error when launching mopidy

> INFO     Disabled extension spotify: pyspotify<1.999,>=1.9 required, but found pyspotify 2.0.5 at /usr/local/lib/python2.7/dist-packages

If I downgrade to pyspotify 1.9 the extension will enable but then throws python errors.

**Comment by trygveaa** [comment]
Which version of Mopidy-Spotify do you have, and what repo did you install it from?

The newest version of Mopidy-Spotify uses pyspotify 2, and that version is available from apt.mopidy.com.

**Comment by SilentMF** [comment]
I'm using:
> deb http://apt.mopidy.com/ jessie main contrib non-free
> deb-src http://apt.mopidy.com/ jessie main contrib non-free

Tried with both Mopidy-spotify version 3.0.0 and an older 2.3.1 both give the same error

**Comment by trygveaa** [comment]
Please install Mopidy-Spotify 3 and pyspotify 2 (i.e. the newest versions of both) and post the output of the `mopidy deps` command.

**Comment by SilentMF** [comment]
ah, you know what it was. I had mopidy-spotify installed from PIP that was version 1.4.0 uninstalling that got it working
