### ISSUE TITLE
get_distinct Result is not JSON serializable

### ISSUE THREAD

**Issue by chises** [mopidy/mopidy-spotify#126]
Using Mopidy 2.0.1-117-ge72d5dc with Mopidy-Spotify 3.0.0.
`mopidy.library.getDistinct({"field":'artist', "query":{'artist': ['linkin park']}}).then(function(data){ console.log(data); });`
Returns
`Jan 11 12:42:09 mopidy[7412]: INFO     Searching Spotify for: artist:"linkin park"
Jan 11 12:42:09 mopidy[7412]: ERROR    WebSocket request error: set([u'Linkin Park', u'LINKIN PARK x STEVE AOKI', u'Karaoke - Linkin Park']) is not JSON serializable`

**Comment by kingosticks** [comment]
From https://docs.mopidy.com/en/latest/api/core/#mopidy.core.LibraryController.get_distinct
> This has mainly been added to support the list commands the MPD protocol supports in a more sane fashion. Other frontends are not recommended to use this method.

That would include a HTTP frontend.

**Comment by chises** [comment]
mhh okay. got it.. :-(

**Comment by kingosticks** [comment]
Distinct is a bit of a funny one. I don't know if we want to fix it or not. Do you really want to know the unique artists from all the tracks in your playlists that match a particular query? You can always do it manually in JS using other API commands.

**Comment by chises** [comment]
thats is my workaround. i will do it in JS now :)

**Comment by csibug** [comment]
can you give me some hint how to get the artist list of a media library uri on websocket? what is the preferred API call for this?

**Comment by kingosticks** [comment]
As this thread states, get_distinct isn't supported for anything other than the MPD frontend. The preferred method is do a regular lookup and filter out the artists on the client side.

**Comment by csibug** [comment]
thank you for the response!
