### ISSUE TITLE
New Playlists not Discovered

### ISSUE THREAD

**Issue by donniebishop** [mopidy/mopidy-spotify#127]
For the last few weeks, I noticed that the Discover Weekly playlist was missing from my list of playlists in ncmpcpp. This was annoying but I figured there might have been a change to how Discover Weekly presents itself, and I lived with it.

Last night, I created a few new playlists, and noticed that they are not showing up in my list of available playlists.

I am currently running mopidy v2.1.0 and mopidy-spotify v3.0.0

Here is my current config, located in `/etc/mopidy/mopidy.conf`:

```
[core]
restore_state = false
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[local]
data_dir = /var/lib/mopidy/local
media_dir = /var/lib/mopidy/media
scan_follow_symlinks = true

[m3u]
playlists_dir = /var/lib/mopidy/playlists

[scrobbler]
username = {OMITTED}
password = {OMITTED}

[spotify]
bitrate = 160
enabled = true
username = {OMITTED}
password = {OMITTED}
volume_normalization = false

[spotify_tunigo]
enabled = true
region = US

[soundcloud]
enabled = true
auth_token = {OMITTED}
explore = 25
```

**Comment by salt-J** [comment]
I have the same problem only I just reinstalled mopidy and mopify-spotify so nothing shows up for me.

**Comment by donniebishop** [comment]
I was gonna try uninstalling and reinstalling, but now that you've said that...

Really hope this gets addressed soon.

**Comment by juzam** [comment]
I have the same Issue with the Discover Weekly playlist. I've noticed that the user referenced in the spotify uri changed from `spotifydiscover` to `spotify` . now "tailored" playlists like Discover Weekly of Release Radar don't get picked up. 
here's the relevant log: 
```
INFO [20551:SpotifyBackend-4] mopidy_spotify.lookup: Failed to lookup "spotify:user:spotify:playlist:37i9dQZEVXcQ0q3fz8VFTc": Operation did not complete in 10.000s
```
Other playlists by the same `spotify` user works fine, so it doesn't seem to be just a timeout like the log seems to imply.

**Comment by kingosticks** [comment]
People have been reporting this on other playlists too, including their own. It's looking like Spotify have changed/broken something at their end. If you enable a more verbose log level (-vvvv) you should see one or more "ChannelError(4, 1, playlist)" type messages. 

There is not much we can do to address this while we continue to use libspotify/pyspotify for our playlist information. This is another reason why we need to move over more things to use the Spotify WebAPI instead.

**Comment by donniebishop** [comment]
Hey all, not sure what happened, but when I checked on my playlists this morning, all the new ones I created last week are now appearing.

Looks like they're all loaded properly, but I didn't notice any big changes to my system. The most recent changes to my system was an update to `requests` and `python2-requests`. Mopidy and mopidy-spotify seem unchanged and haven't been updated since the issue was open.

I do notice that Discover Weekly still isn't showing up in my playlists, but that's been an issue for a while now. Can anyone else confirm?

**Comment by trygveaa** [comment]
> Hey all, not sure what happened, but when I checked on my playlists this morning, all the new ones I created last week are now appearing.

Nice, the playlists I got a timeout on is now working again for me too.

My guess is that there was a problem with the libspotify servers that has now been fixed.

> I do notice that Discover Weekly still isn't showing up in my playlists, but that's been an issue for a while now. Can anyone else confirm?

This hasn't changed for me either. I have the discover weekly playlist on one of my machines, but with the wrong tracks, and I don't have it on another of my machines.

**Comment by Drapherfr** [comment]
Hi, same problem for me since january -> Playlist "discover weekly" not ok. Any solution with that user issue (Failed to lookup "spotify:user:spotify:playlist:) ?

I liked very much the spotify's playlist "discover weekly" :-(

**Comment by kingosticks** [comment]
"Discover Weekly", "Release Radar" and any other special playlists owned by the Spotify user no longer work with Spotify's libspotify library as discussed in https://github.com/mopidy/mopidy-spotify/issues/122. This is their doing and unfortunately they show absolutely no interest in fixing it (see https://github.com/mopidy/mopidy-spotify/issues/110).

Fixing this will be part of https://github.com/mopidy/mopidy-spotify/issues/130.

Closing this since whatever was wrong with *regular user playlists* was a temporary issue with the Spotify servers.

**Comment by ikcalB** [comment]
@kingosticks is there any progress on merging mopidy-spotify-web?

Tried again today (after 1y off) and still don't see `Discover Weekly`

**Comment by kenogo** [comment]
@ikcalB He has indeed been working on his fork on the following branch: https://github.com/kingosticks/mopidy-spotify/tree/fix/web-api-playlists-v2 Haven't tried it yet, but looks like it works from the commit messages :)

**Comment by ikcalB** [comment]
@kenogo am trying that branch right now: At least in GMPC seemingly nothing changed. Still can only see `Spotify->Top {playlists,artists,albums}`

Which client do you use?
