### ISSUE TITLE
No personal spotify playlists

### ISSUE THREAD

**Issue by koallen** [mopidy/mopidy-spotify#133]
I'm running Ubuntu 16.04 LTS and installed both mopidy and mopidy-spotify from the mopidy repository. When I open `ncmpcpp` or `ncmpc`, in the browse window, there is only

- Top albums
- Top artists
- Top tracks

Why are my personal spotify playlists not showing up? I've tried to delete the `spotify` folder in `/var/cache/mopidy` and `/var/lib/mopidy`, but it doesn't help. :(

**Comment by karlvr** [comment]
I believe I am having the same problem. All playlist load attempts through mopidy-spotify timeout after 10s. I have tried increasing the timeout in the mopidy.conf, however the playlist requests still timeout after 10s.

```
2017-03-09 19:20:46,640 INFO [13948:SpotifyBackend-8] mopidy_spotify.lookup: Failed to lookup "spotify:user:119532211:playlist:3P7Tr4RmqP8MFr2ItafksO": Operation did not complete in 10.000s
```

**Comment by nefaspartim** [comment]
I'm having the same issues, but nothing is getting returned for a lookup call with a playlist URI.  Is someone working on #130 (and I guess would that even fix this issue)?

**Comment by gabepaez** [comment]
I'm having the same issue. I'm not able to access any Spotify playlists with the same `mopidy_spotify.lookup: Failed to lookup` error

**Comment by qdlmcfresh** [comment]
I think spotify has changed something in the playlist creation process, which is not compatible with good old libspotify. Every  new playlist i create either via webapi/spotify desktop/ spotify android is not recognized by mopidy-spotify. All my old playlists and playlists some playlists im following are loaded perfectly fine. So the only possible fix would be [#130](https://github.com/mopidy/mopidy-spotify/issues/130)

**Comment by kingosticks** [comment]
I just created one on the Android client which appeared as usual.

**Comment by chises** [comment]
i am facing the same issue, that Playlists does not Show up. especially Playlists that i am following. Playlists that were created by myself are showing up. 
Playlists, created by spotify, that i just follow, does not Show up.
i can see These error in the log:
```
May  3 17:17:12 Ipse mopidy[22319]: DEBUG    2017-05-03 17:17:12,534 [22319:Dummy-9] spotify.session
May  3 17:17:12 Ipse mopidy[22319]: libspotify log message: 15:17:12.533 E [ap:4210] ChannelError(0, 1, playlist)
May  3 17:17:22 Ipse mopidy[22319]: DEBUG    2017-05-03 17:17:22,772 [22319:Dummy-9] spotify.session
May  3 17:17:22 Ipse mopidy[22319]: libspotify log message: 15:17:22.771 E [ap:4210] ChannelError(3, 1, playlist)
May  3 17:17:22 Ipse mopidy[22319]: DEBUG    2017-05-03 17:17:22,772 [22319:Dummy-9] spotify.session
May  3 17:17:22 Ipse mopidy[22319]: Notify main thread
May  3 17:17:22 Ipse mopidy[22319]: DEBUG    2017-05-03 17:17:22,773 [22319:Dummy-9] spotify.session
May  3 17:17:22 Ipse mopidy[22319]: libspotify log message: 15:17:22.773 E [ap:4210] ChannelError(4, 1, playlist)


```

**Comment by oblitum** [comment]
I'm using mopidy-spotify and mopidy-spotify-web. I have my playlists listed and can play them but they just show up in the Browse view, browsing [Spotify] I just have the Top albums, Top artists and Top tracks, there are no other playlists. On mopidy-spotify-web I get other playlists like the Genres & Moods playlists, but simply can't play any, even with #139  applied and timeout changed to 45s.

**Comment by kingosticks** [comment]
Fixed in https://github.com/mopidy/mopidy-spotify/commit/4aafc68be8d41cd6b54b42f90d034b8277b35f9d
