### ISSUE TITLE
Cannot play playlists created by "Spotify"

### ISSUE THREAD

**Issue by corneboele** [mopidy/mopidy-spotify#140]
We use the load by URI a lot, but recently we cannot load the playlist that are created by Spotify itself. Every other playlist or artist URI works perfectly. Any idea what could be the problem?

**Comment by kingosticks** [comment]
This looks like https://github.com/mopidy/mopidy-spotify/issues/133

**Comment by NiPKIT** [comment]
I have the same issue. I can see all my personal playlists and playlist from other people who i am following. But i cant see official playlists created by spotify.

**Comment by poikilotherm** [comment]
Hi there,

I struggle from the same issue. Playlist built by myself or others are no problem, but anything related to "spotify:user:spotify:playlist:xxxx" is just not loading.

I didn't manage to enable debugging output for the extension - is this builtin?

Willing to help, debug and create a PR if someone can give me a hand.

**Comment by jakuboz** [comment]
Hi,
same issue here for quite a long time. Just burned a fresh copy of raspbian and issue persists.
Playlists that are not created by user 'Spotify' work normally.
If I can provide any more details- I'll be happy to help.

**Comment by kingosticks** [comment]
This issue is due to a breaking change in Spotify's libspotify library which is end of life and so will not be fixed by Spotify.  Therefore, the issue will persist until someone changes mopidy-spotify to use the Spotify Web API for playlist data instead of libspotify. 

I did some [initial work on this](https://github.com/kingosticks/mopidy-spotify/tree/fix/incompatible_playlists) and found that caching will be required, and of course a fair amount of tests. I won't have the time to work on it any further until after the holidays but others are more than welcome to have a go.

**Comment by scheleaap** [comment]
I use [Iris](https://github.com/jaedb/Iris) in combination with Mopidy and Mopidy-Spotify to play Spotify playlists (at least my Discover Weekly playlist) and that works fine. Does that help you?

See https://github.com/scheleaap/ansible-role-mopidy/blob/master/tasks/install.yml if you're interested in the details of how I set up Mopidy.

**Comment by NiPKIT** [comment]
I also use iris. In iris the spotify playlists work fine. I think iris uses [spotipy](https://github.com/plamere/spotipy) to interact with spotify. But when I use the command line (mpc) to list the playlists it doesn't work. I think because mopidy uses the old libspotify like @kingosticks mentioned.

**Comment by jasondaigo** [comment]
im shocked that this issue is present since may; i just subscribed to spotify and i will definitely cancel it again; i dont wait a year for this feature.

**Comment by kentletor** [comment]
bummed that I cant get mpc working with Mopidy-Spotify. Mopify works great but when I play a song on mopify then try to pause or play it with mpc, mopidy stalls and needs to be restarted. I wanted to use Ha-Bridge to be able to use my Echo to control my RPI's spotify experience.

**Comment by trygveaa** [comment]
@kentletor: That's a completely separate issue, and what you're describing should normally work fine.

**Comment by kentletor** [comment]
@trygveaa
Mpc detects my spotify playlists but cannot load them. Playlists work fine in mopify

**Comment by kingosticks** [comment]
The same playlists are played through libspotify regardless of frontend, what you describe doesn't make sense. In addition, this issue does not require mopidy to be restarted. Whatever you are seeing is not the same issue, can you please open a new issue and include a bug log?

**Comment by ryanrdetzel** [comment]
Iris (and other frontends) I think work by just adding the songs to the existing playlist which is different than playing the playlist uri directly. The former will work fine, the later won't work as it's a known issue. So a hack could be when a playlist is received to look it up and just add it like the frontends do it.

**Comment by kingosticks** [comment]
Libspotify plays tracks, never playlists. But what you describe is exactly what mopidy-spotify needs to do. Change the libspotify playlist->tracks lookup to be a Web API playlist->tracks lookup. And it can do it for all playlists, no need to be a special case.  If someone has the motivation/time to do it then great, go for it.

**Comment by kingosticks** [comment]
Fixed in https://github.com/mopidy/mopidy-spotify/commit/4aafc68be8d41cd6b54b42f90d034b8277b35f9d
