### ISSUE TITLE
Search returns no results

### ISSUE THREAD

**Issue by Plez** [mopidy/mopidy-spotify#142]
Just as the title says, searching returns no results, basically I can only access my already created playlists, is this expected behaviour?

Any clients suggested to discern if its not a player issue?

`INFO     New MPD connection from [::ffff:127.0.0.1]:37660
INFO     Searching Spotify for: "DNA"
INFO     Searching Spotify for: "sophie"
INFO     Searching Spotify for: "SOPHIE"
`

no errors appear from mopidy from what i can tell

**Comment by kingosticks** [comment]
Possibly https://github.com/mopidy/mopidy-spotify/issues/130#issuecomment-304714643
?

**Comment by Plez** [comment]
yeah that seems to be the same error, especialy the last comment. I'll monitor that thread instead, thank you.

**Comment by theos-space** [comment]
happening to me too.

**Comment by ikciwor** [comment]
I also have this problem. It begun about week ago. Mopidy can spot my playlists, but search always fails. Tried on ncmpcpp and moped clients - same results

**Comment by kingosticks** [comment]
Search stopped working ~3 days ago when Spotify changed their API to require authentication as per the issue I've already linked above. Have you tried that branch?

**Comment by Plez** [comment]
Can confirm the link that you posted fixes the issue, i can now use the search function

**Comment by ikciwor** [comment]
Yes, it worked, but today the problem returned. Now I can't even browse contents of my playlists (earlier it was possible while search was broken)

**Comment by Sebastiaan76** [comment]
I'm having no luck adding the client_id lines to my conf file. If i place them under the [spotify] section I see the following in my debug output: spotify/client_id unknown config key.

running 'mopidy config' also shows the [spotify] config gets disabled. 

If I place them under [spotify_web] i get no errors, but search still won't work.

**Comment by kingosticks** [comment]
You need to install and use the fixed oauth branch, it sounds like you have not done this. 
```pip install https://github.com/mopidy/mopidy-spotify/archive/feature/oauth.zip```

**Comment by charbar** [comment]
My searches in NCMPCPP and Moped are still not returning any results after updating the oauth branch, installing mopidy-spotify-web and adding a [spotify_web] section to my mopidy.conf (populated with the client ID and secret generated by Mopidy's website). Everything else is working fine, with the rest of my previously working mopidy.conf unchanged. Mopidy is not giving any errors when starting or after performing a search, either. I've probably just overlooked something basic, but I can't seem to figure out what. Any suggestions?

**Comment by kingosticks** [comment]
You don't need mopidy-spotify-web. You need to add those two new config settings to your existing Spotify section, as the oauth branch readme states.

**Comment by Sebastiaan76** [comment]
Have done both ( including installation of the oauth branch ) but if I add those entries against my [spotify] section, running 'mopidy config' states the extension is disabled due to config errors.

I had to change the mopidy script to point to python2 on the oauth branch, but it is working other than that ( minus the search )

**Comment by charbar** [comment]
I'm also getting the config error after putting client_id and client_secret in the [spotify] section of my mopidy.conf file. I've also uninstalled the mopidy-spotify-web package and removed the [spotify_web] section from my conf file.

**Comment by Sebastiaan76** [comment]
So, I installed on a VM from scratch under Python2 on Arch Linux. Managed to get it working (although had some issues with permissions on the /var/cache and other similar dirs ). So, in short, the OAuth version is working, I think my previous Mopidy install mustn't be removing fully with pip uninstall, so will have to figure out where it's overlapping.

**Comment by charbar** [comment]
I just got my main install to work. I downloaded the zip file from the [oauth branch](https://github.com/mopidy/mopidy-spotify/tree/feature/oauth) and installed the package with Python 2 from a terminal opened in the extracted folder, running _sudo python2 setup.py install_. If this doesn't work for you, let me know and I'll troubleshoot it with you. I uninstalled and reinstalled a few packages before arriving at the solution, which may or may not have affected the outcome.

**Comment by Sebastiaan76** [comment]
That did the trick! Thanks charbar. All working now. _sudo python2 setup.py install_ ftw! :)

**Comment by kingosticks** [comment]
If you are using Arch (which would be worth mentioning) then I think it's 'sudo pip2 install whatever'.

**Comment by Sebastiaan76** [comment]
Yes, main install is also Arch.

**Comment by charbar** [comment]
Great - Glad you've got it working, Sebastiaan76! I am also using Arch.

Thanks for the Python tip, help with the config file and all of your work on Mopidy, kingosticks. I use it everyday and hope to be able to contribute once I've gotten a bit more Python coding experience under my belt.

**Comment by jodal** [comment]
Fixed by #143.

**Comment by ldimitroff** [comment]
I'm still having this issue, but with no error, just not getting any results. Can play only already saved playlists, but can't search or start a station. Already installed the oauth addon with no luck. Any thoughts?

**Comment by kingosticks** [comment]
What do you mean by install the oauth add on exactly? The latest version of mopidy-spotify has the required fixes. Once you've updated you must follow the project readme which outlines the additional authentication steps that are now required.

**Comment by ldimitroff** [comment]
Yeah, sorry about that... I did what you have commented 

> pip install https://github.com/mopidy/mopidy-spotify/archive/feature/oauth.zip

But yesterday did a fresh install anyways, setted up the keys: 

> [spotify]
username = alice
password = secret
client_id = ... client_id value you got from mopidy.com ...
client_secret = ... client_secret value you got from mopidy.com ...

It's a facebook login so I had to go to generate the username Id and device's password. Playlists already saved works just fine, but the search doesn't return result, it even doesn't timeout after 10 seconds (by default)

**Comment by kingosticks** [comment]
Verify the fresh install includes mopidy-spotify  v3.1.0 (run `mopidy deps`). I don't have a Facebook login to try it but I can't think why it would be different. Your logs will probably have the answer (run `mopidy -v`). 

Note that playlist support has not changed and it should work like usual.
