### ISSUE TITLE
3.1.0 breaks Spotify Support

### ISSUE THREAD

**Issue by thexmanxyz** [mopidy/mopidy-spotify#153]
Hey there,

I have mopidy running on a RPI3 with debian and after an upgrade to 3.1.0 yesterday the mopidy-spotify plugin seems to be broken. There are no personal playlists in 3.1.0 I also can't access anything spotify related. The playlist browsing for Spotify playlists works but there are no titles shown. Idk if this is related to #133 or #140 or a specific distribution. However I tried reinstalling the plugin, which didn't change anything. Finally, reverting back to version 3.0.0 did it and now everything works again like a charm. So I assume that the version 3.1.0 breaks the Spotify support, at least on my debian setup. I also tried reinstalling the 3.1.0 multiple times but that does not help. Only the 3.0.0 works.

Linux Version: 
4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
Debian 8.0

Any suggestions? Just want to let you know that something breaks the plugin.

**Comment by kingosticks** [comment]
I'm not able to reproduce what you describe on my x86 system and my personal playlists show up fine (Spotify owned playlists currently do not, that's #140).  Searching and playback work fine also. Searching does not work in v3.0.0, so I'm not sure I understand your findings.

Please provide the output of `mopidy deps` and a link to a verbose log (`mopidy -v`) as described [here](https://docs.mopidy.com/en/latest/troubleshooting/#sharing-config-and-log-output).

**Comment by thexmanxyz** [comment]
You're right it's possible that searching does not work. I didn't test everything in deep so I can't tell how many of the features are currently broken. However, playback and public playlists work (some may not => #140). Ok that's strange and I'm currently also not able to reproduce it because the system is not located in my home and I also do not have PI3 laying around to test. However I will come back soon with the debug and dependency output ;)

**Comment by jodal** [comment]
Make sure you've set the new required configs in 3.1.0.

**Comment by thexmanxyz** [comment]
@jodal sorry for my maybe stupid question. But what are the new config which have to be set in addition to ones working with 3.0.0? are they located in the mopidy.conf? Thanks already for your help!

**Comment by kingosticks** [comment]
```
client_id = ... client_id value you got from mopidy.com ...
client_secret = ... client_secret value you got from mopidy.com ...
```

Obtained from https://www.mopidy.com/authenticate/#spotify

**Comment by thexmanxyz** [comment]
@kingosticks Big thanks, I overlooked the client credentials because I confused them with the spotify_web plugin, which also have the same two key value pairs. Didn't see that these have now to be also set for the mopidy-spotify plugin. Thanks for clarification!

**Comment by LxFx** [comment]
Solved by adding new required configs, thanks!

**Comment by thexmanxyz** [comment]
sorry for late report back. the suggested answer worked ;)
