### ISSUE TITLE
Better Fedora install instructions

### ISSUE THREAD

**Issue by frnkshin** [mopidy/mopidy-spotify#154]
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory

        No working compiler found, or bogus compiler options
        passed to the compiler from Python's distutils module.
        See the error messages above.

The error message above shows up when doing `sudo pip install mopidy-spotify`

All of the dependencies were installed, and the error persisted.

Installing `redhat-rpm-config` helped resolve the issue.

**Comment by kingosticks** [comment]
Isn't this just a specific quirk of building on Fedora/Redhat?  We don't have detailed instructions for building pyspotify on Fedora/Redhat, we just state you need a (working) C compiler. 

Would you be able to contribute a Fedora section [here](https://github.com/mopidy/pyspotify/blob/v2.x/develop/docs/installation.rst#build-tools) ?

**Comment by hshin23** [comment]
@kingosticks I would but I'm not sure about other dependencies other than `redhat-rpm-config` for `pyspotify.` Is it okay to just add that as the sole dependency under `Build-tools/Fedora?`

**Comment by kingosticks** [comment]
Yeh, I mean it's a start!

**Comment by kingosticks** [comment]
From https://github.com/mopidy/mopidy-spotify/issues/211 it sounds like Fedora removed libspotify from their repository. Installing on this platform is now the same as installing from source (which involves obtaining a copy of libspotify from somewhere, apt.mopiy.com seems to be one of the few remaining places).
