### ISSUE TITLE
No sound when playing from spotify to icecast2

### ISSUE THREAD

**Issue by UnconnectedBedna** [mopidy/mopidy-spotify#155]
Everything is working fine except the sound when playing from spotify.
Local files plays fine.

When installing I installed mopidy-spotify before icecast and tested it through hdmi and it worked fine.

I since then added icecast and a 500ms silence mp3 to stop the stream from dropping when changing song.

I have no idea how to solve this..

**Comment by kingosticks** [comment]
Please, in future, rather than remove your question it's helpful to say what the fix was. That way others can benefit from what you discovered and we can see where to improve the documentation.

**Comment by UnconnectedBedna** [comment]
Sorry. The fix was to restart the pi 3 times without doing any other changes... :-S
