### ISSUE TITLE
Spotify initialization hangs forever

### ISSUE THREAD

**Issue by BlackLight** [mopidy/mopidy-spotify#157]
As of yesterday, I've started experiencing an issue with mopidy-spotify on all of my devices that prevents the initialization to be completed.

Even if I leave the program running for several hours, spotify will never finalize its initialization and therefore mopidy never starts.

I see several messages like these when running mopidy with -vvvv, might be related:

`
libspotify log message: 06:22:22.808 E [ap:4172] ChannelError(0, 1, playlist)
`

And then it forever hangs on the eventloop messages:

`
DEBUG    2017-08-16 08:32:17,610 [20314:SpotifyEventLoop] spotify.eventloop
  Waiting 0.066s for new events
DEBUG    2017-08-16 08:32:17,676 [20314:SpotifyEventLoop] spotify.eventloop
  Timeout reached; processing events
DEBUG    2017-08-16 08:32:17,677 [20314:SpotifyEventLoop] spotify.session
  Notify main thread
`

Has anything changed on Spotify side as far as you know? Everything worked fine until 2 days ago.

**Comment by kingosticks** [comment]
Closing this in favour of https://discuss.mopidy.com/t/mopidy-spotify-initialization-hangs-forever/1827
