### ISSUE TITLE
how to get spotify client_id and client_secret

### ISSUE THREAD

**Issue by Falleut** [mopidy/mopidy-spotify#158]
Hi,

when I login here [https://www.mopidy.com/authenticate/#spotify](https://www.mopidy.com/authenticate/#spotify) the window closes right away, I have no chance to see/generate the id and secret there. Tested it wth 4 browsers on 2 machines.
Am I missing something?

Thanks in advance.

**Comment by kingosticks** [comment]
The client id and secret will replace the placeholders in the mock config area on the page at https://www.mopidy.com/authenticate/. Just as the text should explain.

**Comment by Falleut** [comment]
Thanks, you are right, the id and secret are replaced. I did read the text on the page a couple of times but did not realize that it works that way.

"issue" closed

**Comment by kingosticks** [comment]
If you can propose a better wording or so.me other improvement to make it more obvious then we can change it.

**Comment by Falleut** [comment]
maybe after the existing text:
> 2. Add the credentials to the spotify config section in your mopidy.conf file:

something could be added, like:

> (the client_id and client_secret are generated and displayed below after you sucesfully login to Spotify in step 1 )

sry, I can't think of something better.

**Comment by zudebluvstein** [comment]
So this is still a thing, I've been chasing the same issue after getting the spotify clientid and secret from developers.spotify.com and not copy/pasting it from this.  The wording wasn't clear that it puts it inside the example text

> After the pop up closes, add the following to your mopidy.conf file:

maybe change it to

>After the pop up closes it will change the text below, add the following text to your mopidy.conf file:

**Comment by kingosticks** [comment]
Done in https://github.com/mopidy/website/commit/2d81b53ed7a22729cf21d70a1a73174c1405eac0
