### ISSUE TITLE
Incorrect permissions scope for Spotify token, but no way to alter them

### ISSUE THREAD

**Issue by MichaelMallett** [mopidy/mopidy-spotify#159]
So I've added the auth token to mopidy config, and it seems to work for playing normally though mopify, however if I try and make a search in mopify or in mpc, eg mpc search artist hendrix, it results in:

`ERROR    Fetching https://auth.mopidy.com/spotify/token failed: HTTPSConnectionPool(host='auth.mopidy.com', port=443): Max retries exceeded with url: /spotify/token (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))`

Details of my environment:

Mac OSX 10.12.16
Mopidy 2.1.0
Mopidy-Spotify 3.1.0

I'm pretty sure this is a auth token permissions issue, but there doesn't appear to be a way to request the right ones? I only have REVOKE ACCESS in the spotify dashboard, and the auth link in this project doesn't give me an option to get different permissions.

**Comment by adamcik** [comment]
`(Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))`

This is a problem on the SSL protocol level, so most likely either you have old libraries on your end, and/or our Fastly setup is being too strict.

**Comment by MichaelMallett** [comment]
Ah ok. I have the latest version of openssl...is there something you can
direct me to that I might be missing?

**Comment by kingosticks** [comment]
What version is that? The latest version for Mac OSX is sometimes horribly outdated.

**Comment by MichaelMallett** [comment]
Ah ok on closer inspection its from Jan 2017. Version 1.0.2, just the
latest version in brew. I'll look at upgrading

**Comment by adamcik** [comment]
https://github.com/requests/requests/issues/1847 might be what you are seeing?

**Comment by adamcik** [comment]
Was a bit too quick there, I'll double check that.

**Comment by adamcik** [comment]
See https://github.com/kelproject/pykube/issues/80#issuecomment-280958538 instead where it looks like someone had a similar issue and traced it back to MacOS version issues.

**Comment by MichaelMallett** [comment]
Yeah so OSX was still using it's old version. I upgraded openssl and got a different but similar SSL error, and then when I restarted my machine my mopidy is completely broken. I've tried adding in the python paths etc but I got dependency errors. I installed gi as it was saying it was missing (tho couldn't have been as it was previously working) and now I get attribute errors.

`Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy==2.1.0', 'console_scripts', 'mopidy')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/mopidy/__main__.py", line 8, in <module>
    from mopidy.internal.gi import Gst  # noqa: F401
  File "/usr/local/lib/python2.7/site-packages/mopidy/internal/gi.py", line 9, in <module>
    gi.require_version('Gst', '1.0')
AttributeError: 'module' object has no attribute 'require_version'`

Feels like my whole python set up is completely hosed now, this is all a bit beyond me.

**Comment by MichaelMallett** [comment]
Ok I completely removed everything, reinstalled and got it working again, but now with the correct openssl:

`openssl version -a
OpenSSL 1.0.2l  25 May 2017`

And I'm still getting this error

`ERROR    Fetching https://auth.mopidy.com/spotify/token failed: HTTPSConnectionPool(host='auth.mopidy.com', port=443): Max retries exceeded with url: /spotify/token (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))`

**Comment by MichaelMallett** [comment]
Ok. So I reinstall python using this answer here.
https://stackoverflow.com/questions/24323858/python-referencing-old-ssl-version

And then also the very last answer also procved critical:
brew unlink openssl --force --overwrite python && brew link openssl --force --overwrite python

After that I brew uninstall mopidy and mopidy-spotify and reinstalled and it works!
