### ISSUE TITLE
Web Client list empty when running as a service

### ISSUE THREAD

**Issue by xt16johnny** [mopidy/mopidy-spotify#161]
Hello,

I am running latest version of Mopidy + MusicBox web client. 
When I run as a service, the list of 'Web Clients' which is normally automatically populated, is empty. 
I can still access the MusicBox web client by typing the URL. 

Is this an issue with my config? It resides in /etc/mopidy/mopidy.conf and everything else appears to work normally. 

Cheers,
J

**Comment by kingosticks** [comment]
Hi, this isn't an issue with mopidy-spotify so could you please start a topic at https://discuss.mopidy.com/.  

Please include the output of `sudo mopidyctl deps` and `sudo mopidyctl config` (and anything else you think relevant from https://docs.mopidy.com/en/latest/troubleshooting/), along with some basic information about what OS you are running. 

Also please ensure you have done a full page reload (ensure this isn't a browser cache issue).
