### ISSUE TITLE
Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>

### ISSUE THREAD

**Issue by AFCM1** [mopidy/mopidy-spotify#163]
Hey guys,  

I got an error when I try to run mopidy : Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>  
So I tried some solution found on google : 
1- Changed hostname : "127.0.0.1" to "" in [mpd] and [http]
2- Try wifi and ethernet connection
3- No VPN in my lan  
4- My user is in gpio group

And also my credentials are correct

Thanks a lot,

**Comment by jaedb** [comment]
Do you connect successfully first, and then you receive this error? Or do you never receive the `Logged in to Spotify in online mode` message?

**Comment by woutslakhorst** [comment]
I had the same thing:

```
Feb 26 08:19:00 raspberrypi mopidy[526]: ERROR    [SpotifyEventLoop] spotify.session Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Feb 26 08:19:00 raspberrypi mopidy[526]: DEBUG    [SpotifyEventLoop] mopidy_spotify.backend Logged out of Spotify
Feb 26 08:19:00 raspberrypi mopidy[526]: INFO     [SpotifyEventLoop] spotify.session Spotify logged out
Feb 26 08:19:00 raspberrypi mopidy[526]: DEBUG    [SpotifyEventLoop] mopidy_spotify.backend Logged out of Spotify
```

After refreshing the client_id and client_secret, it worked again.

**Comment by matthiasheyman** [comment]
I am having the same problem. I refreshed the client_id and secret, the first time I restarted mopidy this worked, the second time it didn't. Now I can refresh client_id and secret as much as I want, it doesn't work anymore.

**Comment by kingosticks** [comment]
An issue for the current Spotify outage is at https://github.com/mopidy/mopidy-spotify/issues/257. I'm not sure we really need that issue since there's nothing we can do about it but we surely don't also need this one from 3 years ago.
