### ISSUE TITLE
Spoitfy search broken again?

### ISSUE THREAD

**Issue by baderas** [mopidy/mopidy-spotify#164]
Hi,

I'm using mopidy-spotify 3.10 and still can't search spotify. Whatever frontend I use, the search is hanging endless. 
The log just says "mopidy[3576]: INFO     Searching Spotify for: "cepheus""
Playing songs from spotify however works, just the search is broken.
Again an API change?

In /etc/mopidy/mopidy.conf I have:
[spotify]
username = 
password = 
client_id = 
client_secret = 

client_id and client_secret are generated on https://www.mopidy.com/authenticate/#spotify

Since I'm new to mopidy, maybe I'm doing something wrong?

Versions:
mopidy 2.1.0-1
mopidy-spotify  3.1.0-0mopidy1

**Comment by kingosticks** [comment]
We typically answer usage questions at https://discourse.mopidy.com/

Please use `mopidy config` (or `sudo mopidyctl config` for the service) as to display your config in a manner that helps someone trying to debug your problem.

Search is working for me and Spotify have not announced any API changes lately. I would suggest running with verbose logging (`-v`) to see the debug information regarding the OAuth token being obtained (or not).

**Comment by baderas** [comment]
Debug log shows that token exists and expires in 3600s. Disabled all other plugins.
Same result. No Errors, no Warnings in log.
Could you show a debug log from a working system? Are there any lines after "Searching Spotify..."?

**Comment by kingosticks** [comment]
Sure, unfortunately there isn't anything other than the response after that line:
```
INFO     2017-11-03 13:36:36,528 [1286:MpdSession-20] mopidy.mpd.session
  New MPD connection from [::ffff:127.0.0.1]:53310
DEBUG    2017-11-03 13:36:43,671 [1286:MpdSession-20] mopidy.mpd.session
  Request from [::ffff:127.0.0.1]:53310: find any cepheus
INFO     2017-11-03 13:36:43,830 [1286:SpotifyBackend-10] mopidy_spotify.search
  Searching Spotify for: "cepheus"
DEBUG    2017-11-03 13:36:43,832 [1286:SpotifyBackend-10] mopidy_spotify.web
  Fetching OAuth token from https://auth.mopidy.com/spotify/token
DEBUG    2017-11-03 13:36:44,441 [1286:SpotifyBackend-10] mopidy_spotify.web
  Token expires in 3600 seconds.
DEBUG    2017-11-03 13:36:44,441 [1286:SpotifyBackend-10] mopidy_spotify.web
  Token scopes: playlist-read-private playlist-read-collaborative user-library-read user-follow-read playlist-modify-private user-read-recently-played user-read-private user-top-read
DEBUG    2017-11-03 13:36:44,568 [1286:MpdSession-20] mopidy.mpd.session
  Response to [::ffff:127.0.0.1]:53310: 
    file: spotify:artist:1qiSxUDljngAm6PvXwkA3L
    Time: 0
    Artist: Cepheus
    Title: Artist: Cepheus
    file: spotify:artist:3KvKZjyTPXmJFXwUZ6Kpxr
    Time: 0
    Artist: Cepheus 1
```

What frontends are you using here?

**Comment by kingosticks** [comment]
I tell a lie, you can go for extra verbosity (`-vvv`) and see the HTTP requests, my successfull requests are:
```
INFO     2017-11-03 13:40:50,284 [1714:MpdSession-20] mopidy.mpd.session
  New MPD connection from [::ffff:127.0.0.1]:53386
DEBUG    2017-11-03 13:40:52,782 [1714:MpdSession-20] mopidy.mpd.session
  Request from [::ffff:127.0.0.1]:53386: find any cepheus
INFO     2017-11-03 13:40:52,964 [1714:SpotifyBackend-8] mopidy_spotify.search
  Searching Spotify for: "cepheus"
DEBUG    2017-11-03 13:40:52,964 [1714:SpotifyBackend-8] mopidy_spotify.web
  Fetching OAuth token from https://auth.mopidy.com/spotify/token
DEBUG    2017-11-03 13:40:52,968 [1714:SpotifyBackend-8] urllib3.connectionpool
  Starting new HTTPS connection (1): auth.mopidy.com
DEBUG    2017-11-03 13:40:53,561 [1714:SpotifyBackend-8] urllib3.connectionpool
  https://auth.mopidy.com:443 "POST /spotify/token HTTP/1.1" 200 511
DEBUG    2017-11-03 13:40:53,562 [1714:SpotifyBackend-8] mopidy_spotify.web
  Token expires in 3600 seconds.
DEBUG    2017-11-03 13:40:53,562 [1714:SpotifyBackend-8] mopidy_spotify.web
  Token scopes: playlist-read-private playlist-read-collaborative user-library-read user-follow-read playlist-modify-private user-read-recently-played user-read-private user-top-read
DEBUG    2017-11-03 13:40:53,565 [1714:SpotifyBackend-8] urllib3.connectionpool
  Starting new HTTPS connection (1): api.spotify.com
DEBUG    2017-11-03 13:40:53,724 [1714:SpotifyBackend-8] urllib3.connectionpool
  https://api.spotify.com:443 "GET /v1/search?q=%22cepheus%22&type=album%2Cartist%2Ctrack&limit=50&market=GB HTTP/1.1" 200 None
DEBUG    2017-11-03 13:40:53,734 [1714:MpdSession-20] mopidy.mpd.session
  Response to [::ffff:127.0.0.1]:53386: 
    file: spotify:artist:1qiSxUDljngAm6PvXwkA3L
    Time: 0
    Artist: Cepheus
    Title: Artist: Cepheus
    file: spotify:artist:3KvKZjyTPXmJFXwUZ6Kpxr
    Time: 0
    Artist: Cepheus 1
```
Note that I omitted all the eventloop spam in there.

**Comment by GammaZor** [comment]
Hi.

Having a similar issues.
Based from debug log it searches the song and gets results, but the search on the front end returns nothing.

Front end is Mopify. Is the issue with mopidy-spotify or should I investigate mopidy-Mopify rather?

Auth token is added and working. Any help would be greatly appreciated!

Additional info:
Debian
Mopidy 2.1.0

Snip of log:
INFO     2017-12-18 18:42:44,972 [3018:SpotifyBackend-3] mopidy_spotify.search
  Searching Spotify for: "panda"
DEBUG    2017-12-18 18:42:44,972 [3018:SpotifyBackend-3] mopidy_spotify.web
  Fetching OAuth token from https://auth.mopidy.com/spotify/token
DEBUG    2017-12-18 18:42:46,654 [3018:SpotifyBackend-3] mopidy_spotify.web
  Token expires in 3600 seconds.
DEBUG    2017-12-18 18:42:46,654 [3018:SpotifyBackend-3] mopidy_spotify.web
  Token scopes: playlist-read-private playlist-read-collaborative user-library-read user-follow-read
DEBUG    2017-12-18 18:42:48,243 [3018:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 172.16.0.180: '{"jsonrpc": "2.0", "id": 110, "result": [{"__model__": "SearchResult", "artists": [{"__model__": "Artist", "name": "Gold Panda", "uri": "spotify:artist:6xS3zemJD9h94iueQvGqVk"}, {"__model__": "Artist", "name": "Panda Bear", "uri": "spotify:artist:1R84VlXnFFULOsWWV8IrC

**Comment by kingosticks** [comment]
You got a result so it doesn't look like mopidy-spotify's fault. It should be a quick experiment to try another webclient. I used musicbox-webclient earlier today without issue.

**Comment by GammaZor** [comment]
Confirmed fronted was the issue. Thanks. 
Seems like Mopidy-Mopify is a bit out of date. musicbox-webclient works 100%

**Comment by kingosticks** [comment]
We can reopen if they can reproduce the OP's issue.
