### ISSUE TITLE
Question about client_id & client_secret

### ISSUE THREAD

**Issue by chises** [mopidy/mopidy-spotify#165]
Hi guys,
if i write a application on top of mopidy, how to request the client_id & client_that are required by mopidy-spotify secret by myself?

i have my (own) static client_id & client_secret from spotify by requesting a app.

Atm i am use the https://developer.spotify.com/web-api/authorization-guide/ workflow to request access token & refresh_token.

Thank you all for your support!

**Comment by edeuxk** [comment]
it would be nice if someone can answer. I also need help for this.

**Comment by adamcik** [comment]
Please see https://github.com/mopidy/mopidy-spotify/issues/145

**Comment by edeuxk** [comment]
@adamcik  I've created a Spotify App.
So I have my own app CLIENT_ID and CLIENT_SECRET.

I created a node.js server with spotify-passport middleware (I know how to use it).
Once the user connect to my Spotify App I can return the user accessToken and user refreshToken.
But I can't find the client_id and client_secret.

**Comment by adamcik** [comment]
https://www.mopidy.com/authenticate/ can get you an new id&secret, note that these only work with our endpoints mentioned in the other bug, i.e. they have nothing to do with normal auth flows supported by Spotify and is fully custom.

**Comment by edeuxk** [comment]
So you are telling that there is no way that the user can connect to my Spotify App created here : 
https://beta.developer.spotify.com/dashboard/applications

What does your mopidy.com authenticate do more than the spotify callback?

**Comment by adamcik** [comment]
No that is not supported, at this point it's not really clear what you are trying to do. Other than that it likely is well outside what this project is able to support.

If you read up in https://github.com/mopidy/mopidy-spotify/issues/145#issuecomment-307928905 and onwards and look at https://github.com/adamcik/oauthclientbridge I've tried to explain the how and why of what mopidy.com/authenticate 

Good luck with whatever it is you are trying to achieve.
