### ISSUE TITLE
Option to sort tracks by source (e.g. Spotify first)

### ISSUE THREAD

**Issue by wuservices** [mopidy/mopidy-spotify#166]
I have a few sources like SoundCloud, YouTube, and Spotify set up. However, the Spotify track often show up last. Is it possible to make Spotify tracks come up first since they're the best quality?

I saw you can choose sources by search, but it'd be great to have a default result ordering for all users.

Thank you!

**Comment by adamcik** [comment]
This would need to be solved in mopidy itself, it's not something that could be solved in a plugin. I forget if we have an issue for this in the main repo, feel free to open one there :-)

**Comment by wuservices** [comment]
Whoops too many repos open! I meant to open this in Iris, sorry about that :)
