### ISSUE TITLE
Playing a track with mopidy-spotify crashes mopidy

### ISSUE THREAD

**Issue by zodiac403** [mopidy/mopidy-spotify#168]
Hi there,

I am trying to run **mopidy-spotify@3.1.0** and **mopidy-mopify@1.6.1** on a current Raspian **Stretch** distribution. Connecting with Spotify, searching for songs and browsing playlists works fine. But when I click a song in the UI with the intention to **play** it, the **mopidy** service crashes.

~~~
mopidy[1898]: INFO     Logged in to Spotify in online mode
mopidy[1898]: INFO     Starting Mopidy frontends: QueueManagerFrontend, MpdFrontend, HttpFrontend
mopidy[1898]: INFO     MPD server running at [::ffff:127.0.0.1]:6600
mopidy[1898]: INFO     Starting GLib mainloop
mopidy[1898]: INFO     HTTP server running at [::ffff:127.0.0.1]:6680
mopidy[1898]: INFO     Failed to lookup "spotify:user:spotify:playlist:***": Operation did not complete in 10.000s
mopidy[1898]: INFO     Searching Spotify for: "***"
systemd[1]: mopidy.service: Main process exited, code=exited, status=255/n/a
systemd[1]: mopidy.service: Unit entered failed state.
systemd[1]: mopidy.service: Failed with result 'exit-code'.
~~~

Does anyone face same issues? Any ideas where to start debugging it?

Best

**Comment by kingosticks** [comment]
That is doing a lookup for a playlist that is owned by the spotify user, which Spotify broke support for and does not currently work. You can see the timeout after 10 seconds. But that should not crash mopidy, I've not seen that before. Do all songs do this?

**Comment by zodiac403** [comment]
Hi @kingosticks 
thanks for the quick reply! Yes, all songs I tried so far do this.

**Comment by kingosticks** [comment]
Can you get a verbose log? Easiest to do when not running as a service.

**Comment by zodiac403** [comment]
Strange. `systemctl start mopidy` reproduces the problem every time.
With `mopidy` it works as expected.

**Comment by kingosticks** [comment]
Perhaps a permission problem when the mopidy user accesses your audio device? Could you try running Mopidy as the mopidy user?

**Comment by zodiac403** [comment]
You were right, @kingosticks Seems to be an issue with user rights.

The service runs as user **mopidy**. Per default the user is member of the **audio** group only. Adding it to group **video** fixed my probelm.

~~~
$ groups mopidy
mopidy : audio video
~~~

Don t know yet, if this was an issue with the Mopidy service or the Spotify plugin? For me we could close this issue. When more folks report this issue, we probably should dig deeper?

Thanks for your quick reactions! Helped a lot.

**Comment by kingosticks** [comment]
It would be an issue with mopidy itself. I assume you are using Raspbian
Stretch with the gui i.e. not Raspbian lite? What audio output is this,
HDMI?

**Comment by lukgewuno** [comment]
This happened to me too, and @zodiac403 fix worked. I am running Raspbian Stretch on a RPI Zero W with fixed HDMI audio output.

**Comment by dionmindhive** [comment]
Had the exact same issue (but using the 3.5mm output).
Adding mopidy to the video group (default was just audio), as above, solved it for me.
For anyone wondering how to add a user to a group.
Check out this guide:
https://www.modmypi.com/blog/how-to-add-new-users-and-add-users-to-groups

**Comment by kingosticks** [comment]
This is part of our docs since https://github.com/mopidy/mopidy/commit/ba708001f42e654373d82d01d09bbf0826e604e1

Please re-open if you see the original issue.
