### ISSUE TITLE
Cannot get client_id or client_secret from authentication process

### ISSUE THREAD

**Issue by heytcass** [mopidy/mopidy-spotify#170]
I am trying to enable mopidy-spotify for the first time and I am running into a road block. When I follow the link in the configuration section of the docs to the mopidy site and click the "Log In with Spotify" button, a pop-up window shows up. I enter my username and password there and click "Okay" and the pop-up window disappears without redirecting anywhere.

If I check the apps section of my Spotify account I see that the app has been authorized, but there is no way to find what my id and secret are. Have they changes the authorization process, or am I missing something?

**Comment by kingosticks** [comment]
The client Id secret are filled in on the original page which had the "log in with Spotify" button.
