### ISSUE TITLE
unable to get credentials

### ISSUE THREAD

**Issue by whoppelaar** [mopidy/mopidy-spotify#172]
In order to get the Spotify-credentials client_id and client_secret, you have to visit the authenticate-page:
https://www.mopidy.com/authenticate/#spotify 

If you click on the green button ' Log in with spotify' a popup appears, but disappears immediately. So you can't get the credentials

[spotify]
username = alice
password = secret
client_id = ... client_id value you got from mopidy.com ...
client_secret = ... client_secret value you got from mopidy.com ...

**Comment by kingosticks** [comment]
https://github.com/mopidy/mopidy-spotify/issues/170

**Comment by whoppelaar** [comment]
Sorry for bothering you with a question already asked! And thanks for the
answer! Just didn't notice the credentials were filled in...

2018-01-25 15:27 GMT+01:00 Nick Steel <notifications@github.com>:

**Comment by kingosticks** [comment]
No worries. I've created https://github.com/mopidy/mopidy-website/pull/4 to hopefully improve this a bit but if you have any suggestions to make it more obvious then please say.
