### ISSUE TITLE
sh: safe_fifo: command not found and ncmpcpp timeout

### ISSUE THREAD

**Issue by rusmelezi** [mopidy/mopidy-spotify#174]
When I try searching  a track It works correctly but when I try playing a track ncmpcpp playing one second of track and then says "ncmpcpp: timeout".

Output:

> INFO     Starting Mopidy 2.1.0
> INFO     Loading config from builtin defaults
> INFO     Loading config from /home/rusmelezi/.config/mopidy/mopidy.conf
> INFO     Loading config from command line options
> INFO     Enabled extensions: spotify, mpd, http, stream, m3u, softwaremixer, file
> INFO     Disabled extensions: local
> WARNING  Found local configuration errors, the extension has been automatically disabled:
> WARNING    local/media_dir must be set.
> WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
> INFO     Starting Mopidy mixer: SoftwareMixer
> INFO     Starting Mopidy audio
> INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, SpotifyBackend
> INFO     Starting Mopidy core
> INFO     Logged in to Spotify in offline mode
> INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
> INFO     MPD server running at [::ffff:127.0.0.1]:6600
> INFO     HTTP server running at [::ffff:127.0.0.1]:6680
> INFO     Starting GLib mainloop
> INFO     Logged in to Spotify in online mode
> INFO     Audio output set to "tee name=t ! queue ! autoaudiosink t. ! queue ! udpsink port=5555"
> INFO     New MPD connection from [::ffff:127.0.0.1]:60092
> INFO     Searching Spotify for: "back in black"
> sh: safe_fifo: command not found
> INFO     New MPD connection from [::ffff:127.0.0.1]:60098
> INFO     New MPD connection from [::ffff:127.0.0.1]:60100
> INFO     New MPD connection from [::ffff:127.0.0.1]:60102
> INFO     New MPD connection from [::ffff:127.0.0.1]:60116
> INFO     New MPD connection from [::ffff:127.0.0.1]:60122
> INFO     New MPD connection from [::ffff:127.0.0.1]:60126
> INFO     New MPD connection from [::ffff:127.0.0.1]:60138
> INFO     New MPD connection from [::ffff:127.0.0.1]:60146
> INFO     New MPD connection from [::ffff:127.0.0.1]:60148
> INFO     New MPD connection from [::ffff:127.0.0.1]:60176
> INFO     New MPD connection from [::ffff:127.0.0.1]:60188
> INFO     New MPD connection from [::ffff:127.0.0.1]:60190
> INFO     New MPD connection from [::ffff:127.0.0.1]:60204
> INFO     New MPD connection from [::ffff:127.0.0.1]:60210
> INFO     New MPD connection from [::ffff:127.0.0.1]:60212
> INFO     New MPD connection from [::ffff:127.0.0.1]:60216
> INFO     New MPD connection from [::ffff:127.0.0.1]:60262
> INFO     New MPD connection from [::ffff:127.0.0.1]:60264
> INFO     New MPD connection from [::ffff:127.0.0.1]:60266
> WARNING  Rejected connection from [::ffff:127.0.0.1]:60268
>

**Comment by kingosticks** [comment]
Have you open this here because this *only* happens with the mopidy-spotify backend? Does it also happen with a non-custom audio output configured?

**Comment by kingosticks** [comment]
And you can see your client has hit the default configured max number of connections. It doesn't need 20 connections open, it seems to be messed up.

**Comment by rusmelezi** [comment]
I don't have any idea why but I think it was happening because of my broken ALSA setup, I realized no sound output in youtube etc. and fixed my ALSA setup for hearing sounds and then I checked ncmpcpp and everything worked fine.
