### ISSUE TITLE
Spotify playlists

### ISSUE THREAD

**Issue by pixeldublu** [mopidy/mopidy-spotify#176]
Hello, playing spotify playlists does not work anymore ? 

Just installed and tried all day to play a playlist without any success. 
(spotify:user:spotify:playlist:37i9dQZF1DXbITWG1ZJKYt) (or any other, even tried creating personal)

Playing tracks works perfectly. (spotify:track:2iUrcZcAuVIahQD0dg9HLe)

Thank you

**Comment by kingosticks** [comment]
This is a known issue (#140)
