### ISSUE TITLE
Unable to authenticate with Spotify

### ISSUE THREAD

**Issue by fatg3erman** [mopidy/mopidy-spotify#178]
I was setting up a new installation. I've configured spotify login name and client id and client secret but on running mopidy I get this:

ERROR    Refreshing the auth token failed: hostname 'auth.mopidy.com' doesn't match either of 'b2.shared.global.fastly.net', '*.barkcdn.net', '*.bicycling.com', '*.brisbanetimes.com.au', '*.chicagocitysports.com', '*.chuchro.com', '*.comtrade.com', '*.couponroller.com', '*.crew.co', '*.eu.newrelic.com', '*.eu.nr-assets.net', '*.eu01.nr-data.net', '*.ffx.io', '*.ffxblue.com.au', '*.gadventures.com', '*.getmyboat.ca', '*.getmyboat.co.uk', '*.getmyboat.co.za', '*.getmyboat.com.au', '*.getmyboat.ie', '*.getmyboat.nz', '*.hycu.com', '*.hycusoftware.com', '*.jimdo-frickel-staging.com', '*.jimdo.de', '*.kravet.com', '*.luzernerzeitung.ch', '*.menshealth.com', '*.metacpan.org', '*.moviefanatic.com', '*.mux.com', '*.nmgassets.com', '*.nowth.is', '*.nzz.ch', '*.osce.org', '*.perfectaudience.com', '*.prevention.com', '*.realcrowd.com', '*.risd.edu', '*.rtl.fr', '*.runnersworld.com', '*.scalefastr.io', '*.scroll.com', '*.smh.com.au', '*.stagingworkyardwebsite.com', '*.startle.cloud', '*.tagblatt.ch', '*.theage.com.au', '*.tipotapp.com', '*.watoday.com.au', '*.wine.com', '*.womenshealthmag.com', '*.zipcar.ca', '*.zipcar.com', '*.zipcar.io', 'apf.psa.org.au', 'api.exponea.com', 'app.bar-beats.co.uk', 'app.tipotapp.com', 'bicycling.com', 'cdn.besynchro.com', 'cdn.hyfnlocalcreative.com', 'cdn.pachamama.com', 'chicagocitysports.com', 'chuchro.com', 'codigodescuento.enfemenino.com', 'comtrade.com', 'couponroller.com', 'crew.co', 'eu.newrelic.com', 'eu.nr-assets.net', 'eu01.nr-data.net', 'fastly.site', 'fastly.storytel.se', 'ffx.io', 'gadventures.co.uk', 'gadventures.com', 'gadventures.com.au', 'gadventures.de', 'getmyboat.ca', 'getmyboat.co.uk', 'getmyboat.co.za', 'getmyboat.com.au', 'getmyboat.ie', 'getmyboat.nz', 'gutscheine.faz.net', 'hycu.com', 'hycusoftware.com', 'images.6play.fr', 'jimdo.de', 'jimdofree.com', 'kravet.com', 'marthalouisa.com', 'medicalnote.jp', 'menshealth.com', 'metacpan.org', 'moviefanatic.com', 'mux.com', 'nmgassets.com', 'nowth.is', 'online.mps-gba.de', 'osce.org', 'perfectaudience.com', 'preview.pointb.com', 'realcrowd.com', 'risd.edu', 'rlesports.gg', 'rocketleagueesports.com', 'rtl.fr', 'runnersworld.com', 'scroll.com', 'sdk.a-mo.net', 'secure.paymo.life', 'stagingworkyardwebsite.com', 'startle.cloud', 'stg-secure.paymo.life', 'test-bart.zesty.network', 'test-bart2.zesty.network', 'tipotapp.com', 'voxer.com', 'web.voxer.com', 'wine.com', 'womenshealthmag.com', 'www.australia.gov.au', 'www.barigallery.com', 'www.cigarpage.com', 'www.diffen.com', 'www.fieldsupply.com', 'www.gadventures.co.uk', 'www.gadventures.com.au', 'www.kingdomran.jp', 'www.marthalouisa.com', 'www.pointb.com', 'www.rlesports.gg', 'www.rocketleagueesports.com', 'www.voxer.com', 'www.wildfang.com', 'www.wingsupply.com', 'zipcar.ca', 'zipcar.com', 'zipcar.io', 'ztransforms.com'
WARNING  Did not receive authentication token!
WARNING  Could not initialize spotipy web api instance

Ubuntu 14.04, Mopidy 2.1, Mopidy-Spotify 3.1.0

**Comment by kingosticks** [comment]
That's a very old Ubuntu. Any chance this is a very old certificate package
version?

**Comment by fatg3erman** [comment]
Quite possible but 14.04 is still supported. Which certificate package should I be looking at?

**Comment by fatg3erman** [comment]
It does appear you could be right. I've uninstalled everything and now mopidy won't even install as the ubuntu 14.04 versions of several packages are incompatible. I was really hopinh not to have to upgrade this box, it has mythtv running on it.... Ah well.. see you in about 14 days :)

**Comment by L422Y** [comment]
I don't believe having to upgrade the box should be necessary, I am also running into this issue on 14.04... A workaround would be nice instead of having to reinstall everything..

**Comment by isaidi** [comment]
has anyone else figure out a way to update the SSL certificates ?  I am also running ubuntu 14.04 and would rather not update. I manually updated most my packages with pip install --upgrade.  

However it's obvoius i have old certificates   and spotify-web keeps failing to recieve token becuase the SSL Hostname mismatch in certificates.  

`ERROR    Certificate did not match expected hostname: auth.mopidy.com. 
.....
Caused by SSLError(CertificateError("hostname 'auth.mopidy.com' doesn't match 'e.sni.fastly.net'",`

**Comment by isaidi** [comment]
not sure if this helps  ?

Spotify-web is using python requests to verify SSL certificate with auth.mopidy.com  when asking for token... but it fails to match certificate.   so some how i need to fix it  ?  
this link shows up python requests work - but not sure what I need to to do to update my certificates ?

http://docs.python-requests.org/en/master/user/advanced/

i also  update my system certificates - but still no luck..

`$  sudo update-ca-certificates
Updating certificates in /etc/ssl/certs... 0 added, 0 removed;
done
Running hooks in /etc/ca-certificates/update.d...
done
done.`

**Comment by kingosticks** [comment]
I have to consider this issue too stale to action but please re-open if that's wrong.
