### ISSUE TITLE
mopidy-spotify working but ncmpcpp says "connection refused"

### ISSUE THREAD

**Issue by amarazzi** [mopidy/mopidy-spotify#181]
If I type in my console mopidy-spotify it connects to Spotify without problems.

When I start ncmpcpp it says Connection Refused and can't search songs.

Is someone having the same problem?

**Comment by kingosticks** [comment]
I am afraid typing "mopidy-spotify" in the console makes no sense as that is not how you use Mopidy. Please refer to the Mopidy documentation if you don't know how to use it. 

If you are still having problems please post your question at the [user forum](https://discourse.mopidy.com/) and explain *exactly* what you are doing and exactly what you expect to happen.

**Comment by amarazzi** [comment]
I meant mopidy :P
