### ISSUE TITLE
libspotify dependencie ?

### ISSUE THREAD

**Issue by amstramgram** [mopidy/mopidy-spotify#183]
How fixed missing libspotify in python2-pyspotify for mopidy-spotify package ? I try to download this package from AUR.

Thank you

**Comment by kingosticks** [comment]
This is an Arch specific problem, there is nothing we can do here about this. I guess they need to add libspotify back and point it to use the binaries available at https://mopidy.github.io/libspotify-archive/

**Comment by kingosticks** [comment]
Libspotify can be found at https://mopidy.github.io/libspotify-archive/
