### ISSUE TITLE
Cannot play playlists

### ISSUE THREAD

**Issue by halinet** [mopidy/mopidy-spotify#187]
Since three days ago, cannot play playlists. Only track and album.
I`m using mpc client.

track ok:
` mpc add spotify:track:7ef4DlsgrMEH11cDZd32M6`

album ok:
`mpc add spotify:album:5EBGCvO6upi3GNknMVe9x9`

All playlists - error:
`mpc add spotify:user:spotify:playlist:37i9dQZF1DX6J5NfMJS675`
**error adding spotify:user:spotify:playlist:37i9dQZF1DX6J5NfMJS675: directory or file not found**

Raspbian GNU/Linux 8 (jessie), mopidy 2.1.0 , Mopidy-Spotify 3.1.0

**Comment by kingosticks** [comment]
Duplicate of #182
