### ISSUE TITLE
Another Mopidy-Spotify Search Issue

### ISSUE THREAD

**Issue by Hamspiced** [mopidy/mopidy-spotify#191]
I seem to consistently have issues with Mopidy-Spotify  not pulling accurate search results using ncmpcpp.   

I tried to narrow it down and even did a fresh install without Mopidy-Spotify and used Mopify as a debugging tool and haven't gotten anywhere.   

I think it has something to do with the Libspotify or pyspotify deps.   I am on OSX High Sierra.  Currently from a fresh build this what what i usually do.
```
brew remove --force $(brew list) --ignore-dependencies  
brew cleanup
brew reinstall gst-python --without-python --with-python@2
Brew install Mopidy
Brew Install Mopidy-Spotify
```
Without doing an install of GST-Python --without-python --with-python@2 Ill get an error even attempting to brew instlal Mopidy.

Afterwards, Mopidy runs fine without any issues on startup.  

Next ill Brew install NCMPCPP and on attempting a search ill get the following:

> ERROR    SpotifyBackend backend caused an exception.
> Traceback (most recent call last):
>   File "/usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
>     yield
>   File "/usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages/mopidy/core/library.py", line 347, in search
>     result = future.get()
>   File "/usr/local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
>     compat.reraise(*self._data['exc_info'])
>   File "/usr/local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
>     exec('raise tp, value, tb')
>   File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
>     response = self._handle_receive(message)
>   File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
>     return callee(*message['args'], **message['kwargs'])
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/library.py", line 37, in search
>     query, uris, exact)
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/search.py", line 62, in search
>     'type': ','.join(types)})
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/web.py", line 79, in get
>     self._refresh_token()
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/web.py", line 56, in _refresh_token
>     data={'grant_type': 'client_credentials'})
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/web.py", line 41, in _request
>     raise Error('Fetching %s failed: %s' % (url, e))
> Error: Fetching https://auth.mopidy.com/spotify/token failed: [Errno 2] No such file or directory`
> 

Here is where it gets odd.   Any search with a 4 character or less limit will absolutely not work while in Mopify.   However in NCMPCPP, it will still throw an error, give 100 results.  But will not list Playlists, or Artists.  Only songs tied to the artist.

This example is searching for NoFx

> INFO     Searching Spotify for: artist:"NoFx"
> ERROR    SpotifyBackend backend caused an exception.
> Traceback (most recent call last):
>   File "/usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
>     yield
>   File "/usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages/mopidy/core/library.py", line 347, in search
>     result = future.get()
>   File "/usr/local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
>     compat.reraise(*self._data['exc_info'])
>   File "/usr/local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
>     exec('raise tp, value, tb')
>   File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
>     response = self._handle_receive(message)
>   File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
>     return callee(*message['args'], **message['kwargs'])
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/library.py", line 37, in search
>     query, uris, exact)
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/search.py", line 62, in search
>     'type': ','.join(types)})
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/web.py", line 79, in get
>     self._refresh_token()
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/web.py", line 56, in _refresh_token
>     data={'grant_type': 'client_credentials'})
>   File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/web.py", line 41, in _request
>     raise Error('Fetching %s failed: %s' % (url, e))
> Error: Fetching https://auth.mopidy.com/spotify/token failed: [Errno 2] No such file or directory

> Search engine                                                                         Volume: 100%
> ──────────────────────────────────────────────────────────────────────────────────────────────[r]─
> NOFX - S/M Airlines (7" Version)                                                            (4:27)
> NOFX - We Called It America                                                                 (2:07)
> NOFX - I Am An Alcoholic                                                                    (2:36)
> NOFX - Together on the Sand                                                                 (1:14)
> NOFX - The Death of John Smith                                                              (3:50)
> NOFX - Antennaes                                                                            (1:18)
> NOFX - 60%                                                                                  (2:25)
> NOFX - The Quitter Download                                                                 (1:52)
> NOFX - Remnants                                                                             (2:59)
> NOFX - Jeff Wears Birkenstocks                                                              (1:28)
> NOFX - S & M Airlines                                                                       (4:43)
> NOFX - On the Rag                                                                           (1:42)
> NOFX - Day to Daze                                                                          (1:59)
> NOFX - Please Play This Song On The R                                                       (2:17)'
> 

Searching the same "NoFx" produces no results in Mopify.

Also searching for "Jason Mraz"  will net 1 result where Mopify lists many many more.

In addition to all of this no spotify playists on my account are displayed.

I have made sure i am completely updated on Brew, and my OSX.  I have copy and pasted my spotify token auth 3 or so times now with the same result.

Below are Mopidy Config and Deps.

```
 ~/.config/mopidy  mopidy config
[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %message)s
debug_file = /.config/mopidy/mopidy.log
config_file =

[audio]
mixer = software
mixer_volume =
output = tee name=t t. ! queue ! autoaudiosink t. ! queue ! audioresample ! audioconvert ! audio/x-raw,rate=44100,channels=1,format=S16LE ! wavenc ! filesink location=/tmp/mpd.fifo
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[spotify]
enabled = true
username = ********
password = ********
bitrate = 320
volume_normalization = true
private_session = false
timeout = 30
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries =
client_id = *********
client_secret = ********

[mopify]
enabled = true
debug = false

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password =
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist =
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs =
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions =
  .jpg
  .jpeg
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[local]
enabled = true
library = json
media_dir =*******************
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt
  .ini
  .ipa
  .itc
  .itdb
```

```
Executable: /usr/local/bin/mopidy
Platform: Darwin-16.7.0-x86_64-i386-64bit
Python: CPython 2.7.15 from /usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7
Mopidy: 2.1.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
  Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages
  requests>=2.0: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
  setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
  tornado>=3.2: 4.5.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    singledispatch: 3.4.0.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      six: 1.11.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    certifi: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/site-packages
Mopidy-Mopify: 1.6.1 from /usr/local/lib/python2.7/site-packages
  Mopidy>=0.19: 2.1.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages
    requests>=2.0: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
    tornado>=3.2: 4.5.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      singledispatch: 3.4.0.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        six: 1.11.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      certifi: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/site-packages
  ConfigObj: 5.0.6 from /usr/local/lib/python2.7/site-packages
    six: 1.11.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
  setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
Mopidy-Spotify-Web: 0.3.0 from /usr/local/lib/python2.7/site-packages
  Mopidy>=0.19.0: 2.1.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages
    requests>=2.0: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
    tornado>=3.2: 4.5.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      singledispatch: 3.4.0.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        six: 1.11.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      certifi: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/site-packages
  setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
  requests: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
  spotipy: 2.4.4 from /usr/local/lib/python2.7/site-packages
    requests>=1.0: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
  Mopidy-Spotify>=1.2.0: 3.0.0 from /usr/local/lib/python2.7/site-packages
    requests>=2.0: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    pyspotify>=2.0.5: 2.0.5 from /usr/local/Cellar/pyspotify/2.0.5_1/libexec/lib/python2.7/site-packages
      cffi>=1.0.0: 1.11.5 from /usr/local/lib/python2.7/site-packages
        pycparser: 2.18 from /usr/local/lib/python2.7/site-packages
    Mopidy>=2.0: 2.1.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages
      requests>=2.0: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
      tornado>=3.2: 4.5.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        singledispatch: 3.4.0.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
          six: 1.11.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        certifi: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/site-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages
    setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
  Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages
Mopidy-Spotify: 3.0.0 from /usr/local/lib/python2.7/site-packages
  requests>=2.0: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
  pyspotify>=2.0.5: 2.0.5 from /usr/local/Cellar/pyspotify/2.0.5_1/libexec/lib/python2.7/site-packages
    cffi>=1.0.0: 1.11.5 from /usr/local/lib/python2.7/site-packages
      pycparser: 2.18 from /usr/local/lib/python2.7/site-packages
  Mopidy>=2.0: 2.1.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages
    requests>=2.0: 2.18.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      idna<2.7,>=2.5: 2.6 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      certifi>=2017.4.17: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
    setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
    tornado>=3.2: 4.5.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      singledispatch: 3.4.0.3 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
        six: 1.11.0 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      certifi: 2018.4.16 from /usr/local/Cellar/mopidy/2.1.0_1/libexec/lib/python2.7/site-packages
      backports_abc>=0.4: 0.5 from /usr/local/lib/python2.7/site-packages
  Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/site-packages
  setuptools: 39.2.0 from /usr/local/lib/python2.7/site-packages
GStreamer: 1.14.1.0 from /usr/local/lib/python2.7/site-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.28.3
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        oss4sink
        id3demux
        id3v2mux
        mpegaudioparse
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        alsasink
        osssink
        pulsesink
        flump3dec
        lamemp3enc
        mad
        mpg123audiodec

```

A few things i have tried with no results.   I attempted to install KingOfSticks fork for pulling playlists but got many Sha errors.  Finally installed it, same issue.   I attempted to Uninstall Pyspotify and reinstall it and got even more issues even playing songs, or songs not playing all the way through.

Each time i try something new i start from the begininng and do a fresh start as i posted above.  I have not edited my Config for Ncmpcpp or Mopidy short of repasting the Auth Token info for Spotify.

Any help would be appreciated.  I am sure i somehow missed something along the way and i just cant see it.

Edit x10 :  i have no idea how to use markdown in github....

**Comment by kingosticks** [comment]
Mopidy-Spotify 4.0 was released in Dec 2019 and search should be fully working. If you still have this problem after updating to the latest versions then please re-open this.
