### ISSUE TITLE
Track/Album offline playback

### ISSUE THREAD

**Issue by roosemberth** [mopidy/mopidy-spotify#193]
Hi,
Is it possible to cache a song so that when we lose the TCP connection (ie. while roaming/unstable network) we can continue listening at least for a couple of minutes ?

Bonus points: Entire albums

**Comment by jjok** [comment]
That's probably a fairly grey area. Spotify's terms of use specifically say that you can't download the audio. You may be able to get away with caching the current track.

**Comment by kingosticks** [comment]
libspotify technically has support for offline sync and [pyspotify supports that](https://pyspotify.mopidy.com/en/latest/api/offline/). But I don't know how you'd expose that here in Mopidy-Spotify.

Alternatively, you should be able to achieve the first part of this by increasing your `audio/buffer_time` [config value](https://docs.mopidy.com/en/latest/config/#confval-audio/buffer_time). Possibly at the expense of increased latency.

**Comment by adamcik** [comment]
Don't know if we have an existing bug for this already, but I think the quickest way to get this working would be to have the extension register a new CLI sub-command with mopidy where you could mark e.g. playlists as available offline.

I.e. it would just be lookup the playlist and then set https://pyspotify.mopidy.com/en/latest/api/playlist/#spotify.Playlist.set_offline_mode depending on if we are adding or removing.

Thinking this through we could perhaps also have a magic Offline playlist. The playlist wouldn't exist in Spotify and just contain the playlists that are available offline. So the mechanism for controlling things would be adding a playlist to the offline playlist.

Either of these ways you sidestep us not having a clean way to add this generically in Mopidy with a new Core API concept, or adding support for extension provided API extensions. Either of which are not likely to happen fast.

**Comment by jjok** [comment]
I think https://github.com/mopidy/mopidy-gmusic/issues/161 could solve the original issue of unstable internet connection. It wouldn't necessarily help with making albums and playlists available offline.

**Comment by kingosticks** [comment]
I think from an implementation standpoint this is the same as https://github.com/mopidy/mopidy-spotify/issues/10
