### ISSUE TITLE
Intermittent connection, search, and playback issues

### ISSUE THREAD

**Issue by duanearnett** [mopidy/mopidy-spotify#197]
Mopidy and mopidy-spotify have been working well for over a year. Recently (the past few months) there have been intermittent connection and playback issues. Currently, if I can get search to work, I can playback the first  minute or so of a song, playback then stops. If I queue up another song, it may wait a few minutes, but, will eventually (probably) play the first minute or so and stop.

This is on x86, ubuntu, mopidy v2.1, mopidy-spotify v3.1, using ncmpcpp as my front end if that even matters.

```
2018-08-23 08:21:09,692 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Disconnected from Spotify
2018-08-23 08:23:18,130 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in online mode
2018-08-23 08:23:19,090 ERROR [28188:SpotifyEventLoop] spotify.session: Spotify connection error: <ErrorType.CLIENT_TOO_OLD: 9>
2018-08-23 08:23:19,091 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Disconnected from Spotify
2018-08-23 08:25:35,269 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in online mode
2018-08-23 08:25:36,377 ERROR [28188:SpotifyEventLoop] spotify.session: Spotify connection error: <ErrorType.CLIENT_TOO_OLD: 9>
2018-08-23 08:25:36,377 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Disconnected from Spotify
2018-08-23 08:27:52,222 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in online mode
2018-08-23 08:27:52,690 ERROR [28188:SpotifyEventLoop] spotify.session: Spotify connection error: <ErrorType.CLIENT_TOO_OLD: 9>
2018-08-23 08:27:52,690 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Disconnected from Spotify
2018-08-23 08:30:08,331 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in online mode
2018-08-23 08:30:09,077 ERROR [28188:SpotifyEventLoop] spotify.session: Spotify connection error: <ErrorType.CLIENT_TOO_OLD: 9>
2018-08-23 08:30:09,077 INFO [28188:SpotifyEventLoop] mopidy_spotify.backend: Disconnected from Spotify
```

Is this just because libspotify is out of date and the Spotify region I'm connecting to is bouncing it? Any way I can help troubleshoot this issue? Or is there a recommended alternative?

**Comment by kingosticks** [comment]
Your conclusion seems likely but I don't know if we can do anything about it. I away at the moment without access to a machine to test if I now get this.

Are you getting this client too old message every time or just sometimes? What region are you in?

**Comment by duanearnett** [comment]
Every time now. This intermittent behavior is consistent. I’m in the southeast US. Should I hop on a VPN or something? Or do you think it’s a combination of my account and the lib?

**Comment by kingosticks** [comment]
I'm back in the UK now and I can verify that I don't see this issue. If you have access to a VPN then that should help temporarily but I guess it's only a matter of time before Spotify roll out this client version requirement across all regions and put the final nail in libspotify's coffin.

**Comment by duanearnett** [comment]
@kingosticks Tried this morning on a VPN in both London and Chicago and saw the same behavior. 

```
2018-09-04 08:12:00,005 INFO [7480:MpdSession-24] mopidy.mpd.session: New MPD connection from [::ffff:127.0.0.1]:58486
2018-09-04 08:12:01,612 ERROR [7480:SpotifyEventLoop] spotify.session: Spotify connection error: <ErrorType.CLIENT_TOO_OLD: 9>
2018-09-04 08:12:01,613 INFO [7480:SpotifyEventLoop] mopidy_spotify.backend: Disconnected from Spotify
2018-09-04 08:12:40,506 INFO [7480:SpotifyEventLoop] mopidy_spotify.backend: Logged in to Spotify in online mode
2018-09-04 08:12:41,031 ERROR [7480:SpotifyEventLoop] spotify.session: Spotify connection error: <ErrorType.CLIENT_TOO_OLD: 9>
2018-09-04 08:12:41,031 INFO [7480:SpotifyEventLoop] mopidy_spotify.backend: Disconnected from Spotify
```

It will eventually reconnect for a few minutes, but then just goes back to the above logs on repeat...

Anything I can do to help here (I like my ncmpcpp setup over the spotify desktop client)? ...help to remove the dependency on libspotify? I find it unlikely and/or strange I'm the only one experiencing this behavior.

**Comment by kingosticks** [comment]
That's odd. Can you see exactly what version of libspotify you have?
```
$ apt-cache show libspotify*
Package: libspotify12
Architecture: amd64
Version: 12.1.51-1
Priority: extra
Section: libs
Source: libspotify
Maintainer: Stein Magnus Jodal <stein.magnus@jodal.no>
Installed-Size: 2569
Depends: libc6 (>= 2.7)
Filename: dists/stretch/non-free/binary-amd64/libspotify12_12.1.51-1_amd64.deb
Size: 1145468
MD5sum: 15f308474632a3bf0214a3beeeaa9265
SHA1: 4be11cc82b48a752e8acf15f72d7b1b40f90a4d5
SHA256: 9ab71db7215fc278e8d2ad550b2329dde34cc25dd82c09986089240acdab7021
SHA512: a8aee48e569275198e4d91494604c7d15933e520a2deae1c8ba1cdc2941d68014bdc5eb69361e9d09516f02af188f87af0fef27bc90eb8c3501ab4a024051996
Homepage: http://developer.spotify.com/en/libspotify/
Description: Library for using the Spotify music streaming service
 The libspotify C API package allows third party developers to write
 applications that utilize the Spotify music streaming service.
Description-md5: c639258edb5bbb13ef7341b5abaf7ad6
```

If you run with debug logging you can see what Spotify access point you are assigned. I don't know if that's interesting... I'm on:
```
DEBUG    2018-09-04 15:37:17,534 [32477:Dummy-12] spotify.session
  libspotify log message: 14:37:17.534 I [ap:1752] Connecting to AP ap.spotify.com:4070
DEBUG    2018-09-04 15:37:17,565 [32477:Dummy-12] spotify.session
  libspotify log message: 14:37:17.565 I [ap:1226] Connected to AP: 104.199.65.5:4070
```

Anything special about your account e.g. facebook login, family membership etc?

**Comment by duanearnett** [comment]
```
Package: libspotify12
Architecture: amd64
Version: 12.1.51-1
Priority: extra
Section: libs
Source: libspotify
Maintainer: Stein Magnus Jodal <stein.magnus@jodal.no>
Installed-Size: 2569
Depends: libc6 (>= 2.7)
Filename: dists/stretch/non-free/binary-amd64/libspotify12_12.1.51-1_amd64.deb
Size: 1145468
MD5sum: 15f308474632a3bf0214a3beeeaa9265
SHA1: 4be11cc82b48a752e8acf15f72d7b1b40f90a4d5
SHA256: 9ab71db7215fc278e8d2ad550b2329dde34cc25dd82c09986089240acdab7021
SHA512: a8aee48e569275198e4d91494604c7d15933e520a2deae1c8ba1cdc2941d68014bdc5eb69361e9d09516f02af188f87af0fef27bc90eb8c3501ab4a024051996
Homepage: http://developer.spotify.com/en/libspotify/
Description: Library for using the Spotify music streaming service
 The libspotify C API package allows third party developers to write
 applications that utilize the Spotify music streaming service.
Description-md5: c639258edb5bbb13ef7341b5abaf7ad6

Package: libspotify-dev
Architecture: amd64
Version: 12.1.51-1
Priority: extra
Section: libdevel
Source: libspotify
Maintainer: Stein Magnus Jodal <stein.magnus@jodal.no>
Installed-Size: 1642
Depends: libspotify12 (= 12.1.51-1)
Filename: dists/stretch/non-free/binary-amd64/libspotify-dev_12.1.51-1_amd64.deb
Size: 464066
MD5sum: 455edf2d13a8234ab31d6dda27452fae
SHA1: d537c5604d4d0e64cb0aa231b02aa27168d37635
SHA256: acdd35ce4726c047683de36ea2c52b5f86c9625345d8a42ebe874c61153c2ed9
SHA512: 5e8973a2ca08b589ef70b622bcdd14caded0b9f1d0c28af7f7bd20806fc37d269d3ad7deec8da0f2a5f93efbf60cd38deb89b92dff14d8f4f38bb4130823cb94
Homepage: http://developer.spotify.com/en/libspotify/
Description: Library for using the Spotify music streaming service
 This development package provides the header files and the symbolic links to
 allow compilation and linking of programs that use the libraries provided in
 the libspotify12 package.
Description-md5: d47de16681cf12a7bb07ed939bc01a82
```

```
DEBUG    2018-09-05 23:08:42,398 [31013:Dummy-12] spotify.session
libspotify log message: 04:08:42.398 I [ap:1226] Connected to AP: 104.199.240.132:443
```

Nothing special about my account I think - it is very old. I **believe** it **was** a facebook login at first because that was the only way to log in when they were in beta...I might be making that up, otherwise, everything about it is normal.

**Comment by duanearnett** [comment]
Also - I don't pretend to know anything about the inner workings of spotify or libspotify, but find it weird that my AP I'm connected to is over port :443, and not what appears to be the common :4070 Spotify port (according to my 15 seconds of Googling, and your snippet).

**Comment by duanearnett** [comment]
Just wanted to leave an update on this issue. I created a new account and it seems to be working fine. I'll keep using the new Spotify account and see if there are any issues...

**Comment by duanearnett** [comment]
This has started again after a few months of working perfectly - same behavior as before on a brand new spotify account.

**Comment by kingosticks** [comment]
Things have moved on and work very differently in Mopidy-Spotify [v5.0.0a3](https://github.com/mopidy/mopidy-spotify/releases/tag/v5.0.0a3) and [gst-plugin-spotify_0.14.0~alpha.1-1](https://github.com/kingosticks/gst-plugins-rs-build/releases/tag/gst-plugin-spotify_0.14.0-alpha.1-1). Please re-open if required.
