### ISSUE TITLE
Mopidy crashes when using mopidy spotify and startin from /etc/init.d/ 

### ISSUE THREAD

**Issue by reboot-me-now** [mopidy/mopidy-spotify#200]
Hi, 

Mopidy without mopidy-spotify works, mopidy with mopidy-spotify from command line
"mopidy --config=/etc/mopidy/mopidy.conf" also works. 
Starting from /etc/init.d/ does not, mopidy crashes.

Changing daemon user to different other (including root) still leads to a crash.

OS, 
Raspbian GNU/Linux 9

Versions, 
Mopidy (2.1.0)
Mopidy-Spotify (3.1.0)

Error log,
sep 28 20:55:02 ljud mopidy[20292]: INFO     Starting Mopidy mixer: SoftwareMixer
sep 28 20:55:02 ljud mopidy[20292]: INFO     Starting Mopidy audio
sep 28 20:55:02 ljud mopidy[20292]: INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, SpotifyBackend
sep 28 20:55:02 ljud mopidy[20292]: INFO     Audio output set to "lamemp3enc ! shout2send mount=mopidy ip=***** port=****password=****"
sep 28 20:55:02 ljud systemd[1]: mopidy.service: Main process exited, code=killed, status=11/SEGV
sep 28 20:55:02 ljud systemd[1]: mopidy.service: Unit entered failed state.
sep 28 20:55:02 ljud systemd[1]: mopidy.service: Failed with result 'signal'.

mopidy deps, 
Executable: /usr/bin/mopidy
Platform: Linux-4.14.70-v7+-armv7l-with-debian-9.4
Python: CPython 2.7.13 from /usr/lib/python2.7
Mopidy: 2.1.0 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify: 3.1.0 from /usr/lib/python2.7/dist-packages
  Mopidy>=2.0: 2.1.0 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  pyspotify>=2.0.5: 2.0.5 from /usr/lib/python2.7/dist-packages
    cffi>=1.0.0: 1.9.1 from /usr/lib/python2.7/dist-packages
  requests>=2.0: 2.12.4 from /usr/lib/python2.7/dist-packages
GStreamer: 1.10.4.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.22.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec

**Comment by kingosticks** [comment]
User issues belong on the forum rather than our bug tracker. But since you are here:

* How exactly are you starting the Mopidy service? Please also revert any change you tried to make, they are not necessary. 
* How exactly did you install everything?
* Please try removing that audio config and get something simple working.

**Comment by reboot-me-now** [comment]
So, as you correctly suspected it was a user error,  

Removing and recreating
    cache_dir = /var/cache/mopidy
    data_dir = /var/lib/mopidy
with RW for the mopidy user solved it. Haven´t checked why the fatal error didn´t occur while running it from command line, but let´s chalk that one to user error to. 

Logging an RW check on the cache and data dir might be an improvement?

Sorry for registering it on the bug tracker, should have checked more thoroughly.

Thanks for helping =)

**Comment by kingosticks** [comment]
I'd guess we don't check the permissions on those directories since it's libspotify that uses them, rather than any code of ours. We don't know the exact conditions in which they are required to be accessible. But you are right, we could just check anyway and issue a warning since the lack of feedback here was very unhelpful.

**Comment by kingosticks** [comment]
Raised issue in Mopidy core for this.
