### ISSUE TITLE
Multiple Spotify account

### ISSUE THREAD

**Issue by Hydro8** [mopidy/mopidy-spotify#204]
Hi
I didn't find answer to my question so sorry if the response was already told.

Is it possible to have multiple Spotify account ?

I have a family plan and I want to be able to use Spotify connect but also my wife with her own account.

Thank for the information

**Comment by kingosticks** [comment]
Nope, afraid that is not supported without restarting mopidy to switch between accounts. If you are fine with that then just have a separate config file per user and explicitly specify the config file you want to load.

**Comment by Hydro8** [comment]
Ok thank for the information !
