### ISSUE TITLE
Spotify has been paused because your account is being used somewhere else.

### ISSUE THREAD

**Issue by duncan-qabana** [mopidy/mopidy-spotify#205]
I get almost the same error as #1721 , we have a dedicated spotify account for mopidy and we still get the error:

>  Spotify has been paused because your account is being used somewhere else.

After that we need to restart mopidy , because everything we do will give 

> Your request has timed out.

When I do 

> sudo systemctl status mopidy

It shows the same error over and over again

```
mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-11-28 08:10:03 UTC; 23h ago
  Process: 16531 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 16528 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 16535 (mopidy)
   CGroup: /system.slice/mopidy.service
           └─16535 /usr/bin/python /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Nov 28 16:37:07 raspberrypi mopidy[16535]:   File "/usr/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch
Nov 28 16:37:07 raspberrypi mopidy[16535]:     self._async_client.fetch, request, **kwargs))
Nov 28 16:37:07 raspberrypi mopidy[16535]:   File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 457, in run_sync
Nov 28 16:37:07 raspberrypi mopidy[16535]:     return future_cell[0].result()
Nov 28 16:37:07 raspberrypi mopidy[16535]:   File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
Nov 28 16:37:07 raspberrypi mopidy[16535]:     raise_exc_info(self._exc_info)
Nov 28 16:37:07 raspberrypi mopidy[16535]:   File "<string>", line 3, in raise_exc_info
Nov 28 16:37:07 raspberrypi mopidy[16535]: HTTPError: HTTP 503: Backend unavailable, connection timeout
Nov 28 16:37:07 raspberrypi mopidy[16535]: ERROR    500 GET /iris/http/refresh_spotify_token (172.16.16.141) 1477.45ms
Nov 28 16:42:23 raspberrypi mopidy[16535]: WARNING  Spotify has been paused because your account is being used somewhere else.
```

This happends 2-3 times a day now. To be certain, I have changed the password and used Spotify's logout everywhere, that didn't fix it. It's starting to be quite annoying.

Tech stuff:
Mopidy 2.2.1 as service
Iris 3.30.0
Raspberry with Raspbian 9
Python 2.7.13

edit: Markdown fix

**Comment by kingosticks** [comment]
What mopidy-spotify version? Feel free to use use `sudo mopidyctl deps` to properly provide verison info.

**Comment by kingosticks** [comment]
This may be fixed by #162 so can you try the development version?

**Comment by duncan-qabana** [comment]
Thanks for your quick reply,

The command reports: Mopidy-Spotify: 3.1.0
I am going to install the dev version, will report back to you when it does (or hopefully doesn't) occur.

**Comment by duncan-qabana** [comment]
We have tried it for a couple of days now. The crashes are less frequently, but we still had a couple.
Now we have installed a script that connects to the service, so we restart through ssh and make it start playing again when it's ready with our phones

**Comment by Wqrld** [comment]
same issue on 3.1.0, how would i install the dev version?
