### ISSUE TITLE
error while adding when using local.rc or mopidy as a service

### ISSUE THREAD

**Issue by ThinkerTinker** [mopidy/mopidy-spotify#206]
Hi everyone,

I have a strange behaviour here - at least for me. I use local.rc to start mopidy at boot (configuring mopidy as system service returns the same problem).

Here comes my local.rc

#!/bin/sh -e

bin/sleep 20
sudo python /home/pi/rot.py  &
sudo python /home/pi/weiss.py  &
sudo python /home/pi/blau.py  &
sudo python /home/pi/gruen.py  &
sudo python /home/pi/gelb.py  &
sleep 10
sudo mopidy &

_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

exit 0

(I just added sudo to mopidy & - I have no more ideas)

MPD is obviously running and I do using SSH as user pi:

`mpc add spotify:album:4RJuzMFg5iWb33aTkDq34W`

and get

`error adding spotify:album:4RJuzMFg5iWb33aTkDq34W: directory or file not found`

If I start mopidy manually everything just works fine.... maybe local.rc does not honor the sleep and has no active WLAN connection? I have no clue at all. :-(

**Comment by ThinkerTinker** [comment]
Ok... as always after posting I found a solution....
Starting with ` su pi -c 'mopidy &'` does the trick - but now no more MPD messages in the shell. This was not the issue so you may close this. Sorry. If anyone has a quick idea how to get the MPD prints in the SSH shell I appreciate it. Thanks! :-)

**Comment by kingosticks** [comment]
I don't understand your question but if you want to re-ask it at http://discourse.mopidy.com and maybe explain it a different way we can try to help with getting "the MPD prints in the SSH shell".
