### ISSUE TITLE
`local/media_dir` not loading from config

### ISSUE THREAD

**Issue by iancboswell** [mopidy/mopidy-spotify#208]
I've been running mopidy as a service on my Raspberry Pi, and decided I'd try to set up the `local` extension. Unfortunately, it doesn't seem to be reading anything I put into the `media_dir` parameter. This is from my `/etc/mopidy/mopidy.conf`:

```
[local]
enabled = true
library = json
media_dir = "/home/pi/Music"
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt
```

When I restart the service, it gives me a warning that `media_dir` must be set, and disables the `local` extension. Am I doing something wrong, or is there a bug with the config? I added in the quotes after it didn't work with the raw path, but they didn't seem to make a difference. /home/pi/Music is a real folder with a few mp3 files in it.

**Comment by kingosticks** [comment]
The Mopidy service runs as user mopidy. Does it have the required permissions to see that directory owned by user pi?

**Comment by iancboswell** [comment]
Indeed it does. That directory has read access to all. Thanks for the quick reply and apologies for opening this issue in the wrong place. I thought it might be a bug because at the very least it's giving me a misleading warning (that I didn't specify `local/media_dir`, when I actually did)

**Comment by iancboswell** [comment]
I've started a topic in the discourse forum so I'll go ahead and close this issue here.
