### ISSUE TITLE
Can not add spotify tracks to mpd

### ISSUE THREAD

**Issue by yo-han** [mopidy/mopidy-spotify#213]
When I run `mpc add spotify:user:spotify:playlist:3ZgmfR6lsnCwdffZUan8EA` I get `error adding spotify:user:spotify:playlist:3ZgmfR6lsnCwdffZUan8EA: directory or file not found` and I see this error in the logs:

```
DEBUG    2019-02-24 13:18:35,532 [1836:MpdSession-11] mopidy.mpd.session
  Request from [[::ffff:127.0.0.1]:6600]: command_list_begin
DEBUG    2019-02-24 13:18:35,541 [1836:MpdSession-11] mopidy.mpd.session
  Request from [[::ffff:127.0.0.1]:6600]: add "spotify:user:spotify:playlist:3ZgmfR6lsnCwdffZUan8EA"
DEBUG    2019-02-24 13:18:35,551 [1836:MpdSession-11] mopidy.mpd.session
  Request from [[::ffff:127.0.0.1]:6600]: command_list_end
DEBUG    2019-02-24 13:18:35,953 [1836:MpdSession-11] mopidy.mpd.session
  Response to [[::ffff:127.0.0.1]:6600]: ACK [50@0] {add} directory or file not found
DEBUG    2019-02-24 13:18:35,972 [1836:MpdSession-11] mopidy.internal.network
  Client most likely disconnected.
DEBUG    2019-02-24 13:18:35,987 [1836:MpdSession-11] mopidy.internal.network
  Already stopping: Actor is shutting down.
```

How can I fix this? All configs and full logs are here: https://gist.github.com/yo-han/a07f0610c25b59c3cbc39ba6c4d6e3f6

**Comment by fmarzocca** [comment]
I have the same issue. Did you fix it?

**Comment by yo-han** [comment]
I switched to another branch I found in this topic. https://github.com/mopidy/mopidy-spotify/issues/182

**Comment by kingosticks** [comment]
This should be fixed in https://github.com/mopidy/mopidy-spotify/commit/4aafc68be8d41cd6b54b42f90d034b8277b35f9d
