### ISSUE TITLE
can not connect to spotify

### ISSUE THREAD

**Issue by arifainchtein** [mopidy/mopidy-spotify#218]
Hello,
I have the same issue as  a previously closed issue.  I installed mopidy and th spotify extension as described in the readme.  When I run i get
 

2018-11-06 22:04:17,795 ERROR [4440:SpotifyEventLoop] spotify.session: Spotify login error: <ErrorType.BAD_USERNAME_OR_PASSWORD: 6>

I have Spotify Premium account
It is not connected to Facebook
My username contains only lowercase English characters and underscore ("_"), 15 characters
My password contains only lower and uppercase English characters and numbers, 8 characters
I regenerated the client_id and client_secret to check they were copy-pasted correctly (unless I'm doing some systematic error here)
I can actually see my Spotify playlists with Spotify Web Browse.
I have triple verified that the credentials are correct.

here is the conf file:

`[mpd]
hostname = ::

[spotify]
username = xxxx
password = yyyy
bitrate = 160
timeout = 10
cache_dir = $XDG_CACHE_DIR/mopidy/spotify
settings_dir = $XDG_CONFIG_DIR/mopidy/spotify
client_secret = wwwww
client_id = zzzzzz`

any suggestions would be greately appreciated.

**Comment by arifainchtein** [comment]
Sorry, i forgot to say I am running on raspberry pi using stretch.

**Comment by kingosticks** [comment]
That error is from libspotify being unable to login using the supplied `username` and `password`, not the Web API so we can ignore `client_id` / `client_secret` for now. 

My only idea would be to double check you are editing the correct config file for the way you are running Mopidy, as explained at https://docs.mopidy.com/en/latest/service/

Then use `mopidy config` or `sudo mopidyctl config`, as appropriate, to verify your credentials are as expected.
