### ISSUE TITLE
No spotify in my mopidy.conf

### ISSUE THREAD

**Issue by Dergos** [mopidy/mopidy-spotify#219]
I have installed mopidy-spofity at least 6 times, and yet it never appears in config file. Can anyone help?

`# For further information about options in this file see:
#   http://docs.mopidy.com/
#
# The initial commented out values reflect the defaults as of:
#   Mopidy 2.2.2
#   Mopidy-File 2.2.2
#   Mopidy-HTTP 2.2.2
#   Mopidy-Local 2.2.2
#   Mopidy-M3U 2.2.2
#   Mopidy-MPD 2.2.2
#   Mopidy-SoftwareMixer 2.2.2
#   Mopidy-Stream 2.2.2
#
# Available options and defaults might have changed since then,
# run `mopidy config` to see the current effective config and
# `mopidy --version` to check the current version.

[core]
#cache_dir = $XDG_CACHE_DIR/mopidy
#config_dir = $XDG_CONFIG_DIR/mopidy
#data_dir = $XDG_DATA_DIR/mopidy
#max_tracklist_length = 10000
#restore_state = false

[logging]
#color = true
#console_format = %(levelname)-8s %(message)s
#debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
#debug_file = mopidy.log
#config_file =

[audio]
#mixer = software
#mixer_volume = 
#output = autoaudiosink
#buffer_time = 

[proxy]
#scheme = 
#hostname = 
#port = 
#username = 
#password = 

[mpd]
#enabled = true
#hostname = 127.0.0.1
#port = 6600
#password = 
#max_connections = 20
#connection_timeout = 60
#zeroconf = Mopidy MPD server on $hostname
#command_blacklist = 
#  listall
#  listallinfo
#default_playlist_scheme = m3u

[http]
#enabled = true
#hostname = 127.0.0.1
#port = 6680
#static_dir =
#zeroconf = Mopidy HTTP server on $hostname
#allowed_origins = 
#csrf_protection = true

[stream]
#enabled = true
#protocols = 
#  http
#  https
#  mms
#  rtmp
#  rtmps
#  rtsp
#metadata_blacklist = 
#timeout = 5000

[m3u]
#enabled = true
#base_dir = $XDG_MUSIC_DIR
#default_encoding = latin-1
#default_extension = .m3u8
#playlists_dir =

[softwaremixer]
#enabled = true

[file]
#enabled = true
#media_dirs = 
#  $XDG_MUSIC_DIR|Music
#  ~/|Home
#excluded_file_extensions = 
#  .jpg
#  .jpeg
#show_dotfiles = false
#follow_symlinks = false
#metadata_timeout = 1000

[local]
#enabled = true
#library = json
#media_dir = $XDG_MUSIC_DIR
#scan_timeout = 1000
#scan_flush_threshold = 100
#scan_follow_symlinks = false
#excluded_file_extensions = 
#  .directory
#  .html
#  .jpeg
#  .jpg
#  .log
#  .nfo
#  .png
#  .txt`

**Comment by kingosticks** [comment]
Installing an extension will not add it to your config file. You must manually add any settings you want to change to the config file yourself. You only need to add a setting if you want to change it from the default value. For Mopidy-Spotify you'll need to add your login information.  

Also note that lines starting with a '#' character are *commented out* (ignored). You must remove that character for the setting to take effect. More information available at https://docs.mopidy.com/en/latest/config/
