### ISSUE TITLE
Mopidy won't recognize [spotify] in default.conf

### ISSUE THREAD

**Issue by Dergos** [mopidy/mopidy-spotify#220]
When I start mopidy it shows this:
`WARNING  Found spotify configuration errors, the extension has been automatically disabled:
 WARNING    spotify/username must be set.
 WARNING    spotify/client_secret must be set.
 WARNING    spotify/password must be set.
 WARNING    spotify/client_id must be set.
 WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.`
But when I check the default.conf file it shows that they are set.
Does anyone know how to fix this?

**Comment by marrobHD** [comment]
same issue. Have you got it working?

**Comment by kingosticks** [comment]
You need to make sure you are editing the correct config file. The location of that file depends on if you run Mopidy as your user or as service. This is explained in the project's documentation. That documentation does not mention any file names default.conf.

https://docs.mopidy.com/en/latest/config/

**Comment by kingosticks** [comment]
https://docs.mopidy.com/en/latest/service/ might also be helpful for anyone who ends up here. If you are still having problems please reopen.
