### ISSUE TITLE
Move to different spotify library

### ISSUE THREAD

**Issue by varunagrawal** [mopidy/mopidy-spotify#222]
Thank you for all your hard work, @jodal.

Do you think it would be a good idea to move to a different library for Spotify integration, such as [spotipy](https://github.com/plamere/spotipy)?
I've used this library in the past and its support for the Web API is pretty spot on. I can help build it up for Mopidy.

**Comment by jodal** [comment]
I moved your issue from the pyspotify repo to mopidy-spotify repo. pyspotify will forever remain just a wrapper around libspotify, and as libspotify seems abandoned, pyspotify is complete.

As for moving Mopidy-Spotify to something else, yes, I think the right way forward is to use the Spotify Web API for as much as possible and pyspotify only for the music retrieval part which isn't available through the Web API. I think there's some work on this already in various branches. #182 is a relevant issue, though quite long and undigestable at this point. @kingosticks probably has a better overview of the current state of things here than I have.

I personally won't prioritize any work on Mopidy-Spotify until Mopidy 3 is out, running on Python 3.

**Comment by kingosticks** [comment]
I haven't touched my branch in some months due to lack of time, but I have been using it without issue so I need to see where the tests got to and make a PR. 

As for the general topic, we already have #114 and #110 so I don't think we need another.

**Comment by varunagrawal** [comment]
I raised this issue since there has been very little movement regarding the Spotify plugin for Mopidy since #110 and #114. I know you guys have lives beyond Mopidy but I would like to contribute and get this to a stable place. 

I'm currently having all sorts of issues. First the install instructions are outdated, so you get pyspotify version issues when you either install from deb or PyPI. Only installing from source seems to work. Second, I'm facing authentication issues, particularly for the token refresh. I figured this is simply because of pyspotify being outdated and rather than reinventing the wheel, using a solid library like spotipy seemed to be a good idea. 

I'd love to hear your thoughts on this and help contribute as much as I can. :)

**Comment by kingosticks** [comment]
The deb installation instructions should work as they are. If you are having problems with them, or with authentication then please create a new post at https://discourse.mopidy.com/ with specifics and we can work through that. If we do have an issue there it'd be great to iron that out, nobody (on a Debian-based system) should have to install from source. 

We already have our own wheel which we use for searching and to retrieve images so it's not really re-inventing. Adding a dependency on Spotipy doesn't seem worth it to me and it restricts our options when it comes to getting things performant enough for use within Mopidy.

**Comment by trygveaa** [comment]
> Second, I'm facing authentication issues, particularly for the token refresh. I figured this is simply because of pyspotify being outdated and rather than reinventing the wheel, using a solid library like spotipy seemed to be a good idea.

Even if we use the web api (via custom implementation or spotipy) for more stuff, we still have to use pyspotify for playback since the web api doesn't support that. So any authentication issues won't be solved by implementing more of the web api or switching to spotipy.

So if you're having issues with authentication in pyspotify, that would have to be solved either way. I'm not aware of any issues though. I haven't used mopidy-spotify much lately, but haven't had any issues with authentication or playback the times I've used it.
