### ISSUE TITLE
Installation procedure Manjaro Linux

### ISSUE THREAD

**Issue by EverWinter23** [mopidy/mopidy-spotify#223]
Can't install using pacman, what's the procedure? Do I need to enable AUR?

**Comment by kingosticks** [comment]
That's what the installation instructions in the readme say. However, last time I checked, the AUR package was broken because libspotify had been removed. No idea how/why that happened or why nobody has fixed it. For that reason you may need to install manually. Maybe @tkem can advise.

**Comment by tkem** [comment]
Nope ;-)

**Comment by EverWinter23** [comment]
@tkem ;-) When you say nope, what exactly are you saying to? That I need to enable AUR or that libspotify has been removed?

**Comment by tkem** [comment]
That I cannot advise on this. Don't know anything about AUR nor libspotify, I guess @kingosticks mistook me for somebody else.

**Comment by Simon-the-Sorcerer** [comment]
I'm using [this](https://aur.archlinux.org/packages/mopidy-spotify-playlist-fix-git/) package from aur and it's working for me.

**Comment by kingosticks** [comment]
I did, sorry @tkem!

**Comment by kingosticks** [comment]
The libspotify dependency still looks broken to me but I don't even have an arch system so maybe I'm talking rubbish and it magically works. Is interesting to see my branch packaged up as used there. I guess I should just merge it...

**Comment by adamcik** [comment]
@trygveaa is probably who you wanted to loop in, I think he might have state on Arch packaging (or at least used to).

**Comment by trygveaa** [comment]
Yes, you need to install it from AUR. The `mopidy-spotify` package works fine.

@kingosticks: Why do you think the `libspotify` package is broken?

**Comment by kingosticks** [comment]
I think it was broken at one point after Spotify stopped hosting. And then I saw the recent comments at https://aur.archlinux.org/packages/libspotify/ and saw https://aur.archlinux.org/libspotify.git is a broken link so assumed it was still in that state. But having looked closer, I see the PKGBUILD looks legit so maybe I am totally wrong, apologies if so.

**Comment by trygveaa** [comment]
https://aur.archlinux.org/libspotify.git is not broken, you just have to clone it with git instead of visiting it in a browser. I tested it now, and it works fine, so I'll close this issue.

**Comment by trygveaa** [comment]
I see the installation docs said to use yaourt, which is dead and not recommended, so I replaced it with yay.
