### ISSUE TITLE
Play Spotify playlist on Mopidy start (headless, Raspberry Pi)

### ISSUE THREAD

**Issue by jarodwsams** [mopidy/mopidy-spotify#225]
This isn't an issue, unless you count the fact that I couldn't find any documentation for it. I'm running Mopidy on a headless Raspberry Pi connected directly into a front-of-house audio mixer. Every time I turn the RPi on I want it to start the same private playlist. I was able to get the playlists working perfectly with the fix/web-api-playlists-v2 branch using the UI and MPDroid on my phone.

What I'd like to know: Is there a way to set this all up so Mopidy, using Mopidy-Spotify, automatically starts playing my specific playlist every time Mopidy starts from systemctl?

If the Mopidy and/or Mopidy-Spotify community uses something like Slack or Discord where I could bring this up in conversation, let me know and I'll engage there.

Thank you,

**Comment by kingosticks** [comment]
User support questions can be asked at https://discourse.mopidy.com/ please.

**Comment by jarodwsams** [comment]
Thank you.
