### ISSUE TITLE
Spotify-mopidy fixed playlist v2 branch unable to log in to spotify

### ISSUE THREAD

**Issue by nibrocd** [mopidy/mopidy-spotify#229]
Hello I'm trying to use your branch of mopidy-spotify to see my spotify playlists but it will not work. I cloned your git and installed mopidy-spotify using  "sudo pip install ." in the git directory. Initially I had issues from missing dependencies but I installed those and properly built/installed the fixed branch for mopidy-spotify and now it will not properly start.

I have my spotify username, password, client id and client secret in the mopidy config file but it still says they are incorrect. If I uninstall your fix and install with "sudo apt install mopidy-spotify" or "sudo pip install mopidy-spotify" the extension will work properly and I will be able to access spotify through mopidy but it wont have playlists. 

Here is the output after I try to run mopidy, Thanks for the help

pi@raspberrypi:/etc/mopidy $ mopidy
/usr/lib/python2.7/dist-packages/mopidy/ext.py:202: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  extension_class = entry_point.load(require=False)
INFO     Starting Mopidy 2.2.3
INFO     Loading config from builtin defaults
INFO     Loading config from /home/pi/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, local
INFO     Disabled extensions: spotify
WARNING  Found spotify configuration errors, the extension has been automatically disabled:
WARNING    spotify/client_secret unknown config key.
WARNING    spotify/client_id unknown config key.
WARNING  Please fix the extension configuration errors or disable the extensions to silence these messages.
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     Audio output set to "autoaudiosink"
INFO     No local library metadata cache found at /home/pi/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     Starting GLib mainloop

**Comment by kingosticks** [comment]
Hi,

1) Install everything from APT as normal
2) sudo pip install -U https://github.com/kingosticks/mopidy-spotify/archive/fix/web-api-playlists-v2.zip
3) Make sure you edit the correct config file corresponding to the way you run Mopidy ([as your user](https://docs.mopidy.com/en/latest/config/) or [as a service](https://docs.mopidy.com/en/latest/service/#service)

Please post any other issues *using* mopidy-spotify on the user forum at https://discourse.mopidy.com/c/mopidy.
