### ISSUE TITLE
Block explicit content?

### ISSUE THREAD

**Issue by p-doyle** [mopidy/mopidy-spotify#255]
Is there a way to block explicit content?  It seems like its possible from within the app:  https://support.spotify.com/us/using_spotify/system_settings/explicit-content/

**Comment by kingosticks** [comment]
Not consistently because we use libspotify (which doesn't offer this feature at all) and the Spotify Web API (which doesn't offer this feature properly, see https://github.com/spotify/web-api/issues/296).

So someone could implement something to filter search results but it wouldn't work reliably.

**Comment by p-doyle** [comment]
Got it, thanks.
