### ISSUE TITLE
Error connecting with spotify - UNABLE_TO_CONTACT_SERVER: 8

### ISSUE THREAD

**Issue by nunong21** [mopidy/mopidy-spotify#257]
Hello, 

I had mopidy-spotify playing without problems, and yesterday the music stopped. 
I went to Mopidy-Iris and now every time I try to play some music I get the error message saying "Mopidy: Failed to add some tracks". 

Since then I tried already doing multiple things, I checked my subscription (its a family plan with a valid subscription) and updated the credit card that was expiring at the end of this month. 

Generated full new tokens, client secrets, etc (even tried with a new login). 

And in my mopidy journal, I'm getting the messages: 

`Feb 26 10:24:01 mopidy[1119]: ERROR    [SpotifyEventLoop] spotify.session Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Feb 26 10:24:06 mopidy[1119]: INFO     [SpotifyBackend-6] mopidy_spotify.lookup Failed to lookup 'spotify:track:4RbKBuzAMn0e3dNpxH5Fql': Session must be logged in and online to load objects: <ConnectionState.LOGGED_OUT: 0>
`

After some googling what I found was related to the subscription (which I check and seems fine), and with the connected Facebook, which my account isn't connected to any Facebook. 

Has anyone had this problem solved?

**Comment by BlackLight** [comment]
I'm also affected by the issue since yesterday and I've reported it to @SpotifyCares on Twitter just in case (haven't got an answer yet though).

After a bit of investigation, it seems that the connection to the ap.spotify.com selected access point host fails. Debug logs with strace:

```
# First we try to connect on port 4070 -> time out
  libspotify log message: 12:16:01.935 I [ap:1752] Connecting to AP ap.spotify.com:4070
[pid 3544440] connect(15, {sa_family=AF_INET, sin_port=htons(4070), sin_addr=inet_addr("104.154.126.74")}, 16) = -1 EINPROGRESS (Operation now in progress)

# Then on port 443 -> also time out
libspotify log message: 12:16:06.942 I [ap:1752] Connecting to AP ap.spotify.com:443
[pid 3544440] connect(15, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("104.199.64.124")}, 16) = -1 EINPROGRESS (Operation now in progress)

# Then on port 80 -> also timeout
libspotify log message: 12:16:11.950 I [ap:1752] Connecting to AP ap.spotify.com:80
pid 3544440] connect(15, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("104.199.65.134")}, 16) = -1 EINPROGRESS (Operation now in progress)

# Eventually we get a connection failure triggered by libspotify
ERROR    2020-02-26 12:16:16,964 [3544371:SpotifyEventLoop] spotify.session
  Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
```

libspotify is closed source so I can't investigate further what's going on and how the AP hosts are selected. @jodal @kingosticks any clue?

**Comment by sorvakko** [comment]
Works again for me, ap.spotify.com started responding on at least port 443 a short while ago. No change in my setup (didn't even restart spotify in the meantime).

**Comment by nunong21** [comment]
> Works again for me, ap.spotify.com started responding on at least port 443 a short while ago. No change in my setup (didn't even restart mopidy in the meantime).

Tested it right now, but still no luck for me

**Comment by BlackLight** [comment]
> Works again for me, ap.spotify.com started responding on at least port 443 a short while ago. No change in my setup (didn't even restart mopidy in the meantime).

Just out of curiosity, from which country are you connecting? Downdetector yesterday and this morning painted a big red zone for Spotify connectivity over north-west Europe (mostly UK, NL and Belgium), and I believe that the AP host selection logic is also performed on geographical basis.

**Comment by sorvakko** [comment]
> 
> 
> > Works again for me, ap.spotify.com started responding on at least port 443 a short while ago. No change in my setup (didn't even restart mopidy in the meantime).
> 
> Just out of curiosity, from which country are you connecting? Downdetector yesterday and this morning painted a big red zone for Spotify connectivity over north-west Europe (mostly UK, NL and Belgium), and I believe that the AP host selection logic is also performed on geographical basis. Things don't work yet for me btw.

Finland for me. And seems one of my clients works and the other doesn't (both connecting behind the same NATted address, so might be something funky on Spotify's end still).

**Comment by nunong21** [comment]
Portugal here. Still not working, getting the same error. Unfortunately I only have one device to test it on

**Comment by Eluminae** [comment]
Not working for me too in France.

    ERROR    2020-02-26 15:32:08,713 [7605:SpotifyEventLoop] spotify.session
      Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>

**Comment by kingosticks** [comment]
This must be a regional Spotify issue because I don't see an issue right now:
```
DEBUG    2020-02-26 15:01:20,942 [140:SpotifyEventLoop] spotify.eventloop
  Spotify event loop started
DEBUG    2020-02-26 15:01:20,980 [140:SpotifyBackend-6] mopidy_spotify.web
  Fetching OAuth token from https://auth.mopidy.com/spotify/token
DEBUG    2020-02-26 15:01:20,980 [140:Dummy-9] spotify.session
  libspotify log message: 15:01:20.979 I [ap:1752] Connecting to AP ap.spotify.com:4070
DEBUG    2020-02-26 15:01:20,980 [140:SpotifyEventLoop] spotify.eventloop
  Waiting 300.619s for new events
DEBUG    2020-02-26 15:01:20,980 [140:SpotifyBackend-6] urllib3.connectionpool
  Starting new HTTPS connection (1): auth.mopidy.com:443
DEBUG    2020-02-26 15:01:20,998 [140:Dummy-9] spotify.session
  libspotify log message: 15:01:20.998 I [ap:1226] Connected to AP: 35.190.243.156:4070
DEBUG    2020-02-26 15:01:21,065 [140:Dummy-9] spotify.session
  Notify main thread
DEBUG    2020-02-26 15:01:21,066 [140:SpotifyEventLoop] spotify.eventloop
  Notification received; processing events
DEBUG    2020-02-26 15:01:21,066 [140:SpotifyEventLoop] spotify.eventloop
  Waiting 300.533s for new events
DEBUG    2020-02-26 15:01:21,135 [140:Dummy-9] spotify.session
  Notify main thread
DEBUG    2020-02-26 15:01:21,136 [140:SpotifyEventLoop] spotify.eventloop
  Notification received; processing events
DEBUG    2020-02-26 15:01:21,137 [140:Dummy-9] spotify.session
  Notify main thread
INFO     2020-02-26 15:01:21,180 [140:SpotifyEventLoop] spotify.session
  Spotify logged in
DEBUG    2020-02-26 15:01:21,180 [140:SpotifyEventLoop] spotify.session
  Credentials blob updated: 
DEBUG    2020-02-26 15:01:21,181 [140:SpotifyEventLoop] spotify.session
  Connection state updated
INFO     2020-02-26 15:01:21,182 [140:SpotifyEventLoop] mopidy_spotify.backend
  Logged in to Spotify in online mode
```

**Comment by PuzzledSquid** [comment]
Just started working for me (UK) again, yep

**Comment by BlackLight** [comment]
Things have just started working for me too. I believe that it's a regional issue that impacted some of their AP hosts, and it's possibly related to yesterday's outage (a big chunk of Western Europe and some parts of the US were impacted according to downdetector, and most of the users reported login issues).

It'd be super nice if Spotify could inform its users more proactively about these downtimes and provide an ETA for a fix. At peak time yesterday there were >100 reports per hour according to downdetector, so probably it wasn't just an issue with the geeks using mopidy/libspotify. Surely a better communication from their side would save me a lot of time spent reversing/debugging libspotify. And unfortunately @SpotifyCares just runs away when a user starts talking technical to them :)

**Comment by johnmcguin** [comment]
FWIW, I was experiencing this as well starting last night and looked into it a bit this morning. Reset passwords, re authed on the extensions page, restarted mopidy mutltiple times. I am in the US and unable to test at the moment but reading the thread, fingers crossed it will work when I get home tonight 🤞

**Comment by BlackLight** [comment]
@johnmcguin a good idea IMHO would be to poke @SpotifyCares on Twitter. Run mopidy with network trace logs (`strace -f -e trace=network -s 10000 mopidy -vvvv`), search for `ap.spotify.com` and copy the IPs that are down in your region. If it's only me poking them they'll believe that it's only a geek playing with their libraries and they'll keep ignoring me. If it's multiple users and all of them report to them which access point hosts are actually down they'll have to provide a proper answer. Their customer support is technically quite poor and deserves being poked a bit more.

**Comment by johnmcguin** [comment]
@BlackLight Good idea, I certainly will if the issue persists next time I check :)

**Comment by nunong21** [comment]
Well, in Portugal and still having issues with this...

**Comment by matthiasheyman** [comment]
In Belgium it seems to be fixed

**Comment by nunong21** [comment]
48H after and still having issues with this... His there anyone still having the same problem?

**Comment by BlackLight** [comment]
> 48H after and still having issues with this... His there anyone still having the same problem?

It's fixed for me (Netherlands). If you still have issues use the strace+debug logs to check if it's indeed the Spotify AP being down for you. If that's the case copy the 3 IP addresses libspotify tries to connect to and poke @SpotifyCares on Twitter to let them know that they're down for you.

**Comment by juliusvaart** [comment]
Can confirm that after a reboot my issues are gone (the Netherlands). Before reboot i still had the issue.

**Comment by kingosticks** [comment]
I'm going to close this. I am sorry if you are still seeing an outage in your region but there's nothing we can do here to resolve Spotify server problems.
