### ISSUE TITLE
Login is only attempted when mopidy starts

### ISSUE THREAD

**Issue by Gigahawk** [mopidy/mopidy-spotify#259]
If mopidy is started without an internet connection, the Spotify login will fail, and no attempt to reconnect is made even if the connection is restored.

The plugin should periodically attempt to login if it is currently not logged in.

**Comment by kingosticks** [comment]
Alternatively, could you ensure you wait for your Internet connection to become ready before starting Mopidy? The Mopidy systemd unit waits for the network target.

**Comment by Gigahawk** [comment]
I'm on a distro that doesn't use systemd, I just have mopidy start with my window manager.

**Comment by s-martin** [comment]
We use mopidy-spotify in our project and users have reported just recently that login to Spotify doesn't work anymore. Reason could be, that internet connection is not available yet, but this was never an issue in the past.
See:
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/893
https://github.com/MiczFlor/RPi-Jukebox-RFID/issues/901

Were there any changes in 3.0.2?

**Comment by kingosticks** [comment]
The changelog is available online but there were no changes in Mopidy 3.0.2 that would impact the ability of libspotify to login.

**Comment by s-martin** [comment]
> The changelog is available online but there were no changes in Mopidy 3.0.2 that would impact the ability of libspotify to login.

Thanks for the info and pointing us into the right direction.

**Comment by kobbejager** [comment]
I have the same issue on Rasbian Buster Lite. In /etc/init.d/mopidy network is listed as a requirement, but apparently it does not wait for the (wired) network to be fully started. Anyway, I agree with the initial comment that Mopidy-Spotify should try to reconnect regularly.

**Comment by jaor** [comment]
fwiw, same for me with debian sid and mopidy started using the systemd
unit on boot.  i'm never logged in spotify when i first access mopidy
after a reboot (the server is running, and other backends working).  i
need to restart via service for logging to happen.

**Comment by kingosticks** [comment]
Mopidy requires the network and we already specify that in our service files. If your system isn't waiting for the network to be ready, I'm finding it hard to see how that's a Mopidy issue. I've already mentioned the fix for Raspbian above. 

I get there may be some other case that I don't appreciate and so if someone wants to submit a PR for this (that works properly and is tested) then I will review it.
