### ISSUE TITLE
Connection error spotify

### ISSUE THREAD

**Issue by Jotterloo** [mopidy/mopidy-spotify#267]
I have been wrestling a long time, but still no succes with getting spotify working in Mopidy.
At this moment I have a fresh install (buster) with little extensions, but from the fresh start still no succes. 
At first I used my main account, which is a Spotify family created with facebook. To rule those possible problems out I created a new account, which is now in the three months free premium trial. 
But still no luck in connecting to Spotify.
The strange thing is that at first it looks like connecting succeeds, but after that I receive the error UNABLE_TO_CONTACT_SERVER: 8. 
This error is mentioned in other issues, but there it is said the is because of (temporary) outage of spotify servers, But I have this error for about 3 weeks now, so not that temporarily. ANd all other devices are playing without any problems (but probably not using the api)

Long story short: Any idea what I can do to find the source of the problem?
This is what I get to see in the log when I start Mopidy:

```
`jun 21 09:31:13 musicbox mopidy[17796]: INFO     [SpotifyBackend-7] mopidy_spotify.web Logged into Spotify Web API as **********

jun 21 09:31:14 musicbox mopidy[17796]: INFO     [SpotifyBackend-7] mopidy_spotify.playlists Refreshed 4 Spotify playlists

jun 21 09:31:14 musicbox mopidy[17796]: INFO     [MainThread] mopidy.commands Starting Mopidy core

jun 21 09:31:14 musicbox mopidy[17796]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: MpdFrontend, HttpFrontend

jun 21 09:31:14 musicbox mopidy[17796]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::]:6600

jun 21 09:31:15 musicbox mopidy[17796]: INFO     [HttpFrontend-13] mopidy.http.actor HTTP server running at [::]:6680

jun 21 09:31:15 musicbox mopidy[17796]: INFO     [MainThread] mopidy.commands Starting GLib mainloop

jun 21 09:31:32 musicbox mopidy[17796]: ERROR    [SpotifyEventLoop] spotify.session Spotify login error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>`
```

**Comment by kingosticks** [comment]
There are two parts to Mopidy-spotify. There's Spotify's deprecated libspotify library, necessarily for playback, and there's Spotify's Web API for searching/playlist support. The Web API portion has logged in fine but it's the libspotify portion that's failing. Libspotify is closed-source and no longer officially supported by Spotify (sadly they didn't bother providing a replacement for it) so it's extremely difficult to debug anything with it. This does look like a network error, there might be more info available if you enable Mopidy's debug-level logging. Are you sure there's nothing in your network configuration that might block this connection e.g. firewalls?

**Comment by Jotterloo** [comment]
Dude....thought of the firewall before, but everything was open outgoing.
Untill your post made me realize I have also a Pihole.
Configured the router to bypass the pihole and gues what:
`jun 21 12:25:37 musicbox mopidy[3968]: INFO     [SpotifyBackend-7] mopidy_spotify.web Logged into Spotify Web API as ******
jun 21 12:25:38 musicbox mopidy[3968]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Logged in to Spotify in online mode
jun 21 12:25:41 musicbox mopidy[3968]: INFO     [SpotifyBackend-7] mopidy_spotify.playlists Refreshed 4 Spotify playlists
`
Thanks!
No going to try 
- use my main account
- enable pihole

Any suggestion what urls I should whitelist? (before I start searching te logs)

**Comment by kingosticks** [comment]
I think at a minimum you need to be able to talk to *.ap.spotify.com but exactly what else I'm not sure and you may have to look through the logs.
