### ISSUE TITLE
cant install, error code 1

### ISSUE THREAD

**Issue by myfairx** [mopidy/mopidy-spotify#272]
Hi

I'm using pi zero w with debian buster lite

after installing mopidy and get it working with LOCAL and IRIS i wanted to install spotify  but I got this error

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-trld82q6/pyspotify/`

I also have mpd, upmpdcli and raspotify installed (and working) but i don't think this is related

**Comment by jodal** [comment]
Thanks for the bug report! To be able to help you, we need the full output from the installation. With only that single line, we don't have anything to work with.

**Comment by myfairx** [comment]
root@raspberrypi:/home/pi# sudo python3 -m pip install Mopidy-Spotify
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Mopidy-Spotify
  Downloading https://files.pythonhosted.org/packages/1c/41/1d5b1b6534cf5ad209ba8b814132cfdadf8dcda87024beabb42c1f88ce22/Mopidy_Spotify-4.0.1-py3-none-any.whl
Requirement already satisfied: Pykka>=2.0.1 in /usr/lib/python3/dist-packages (from Mopidy-Spotify) (2.0.2)
Collecting pyspotify>=2.0.5 (from Mopidy-Spotify)
  Downloading https://files.pythonhosted.org/packages/fe/1d/83d088397d95eacf6281ae748886d024aab50efdea50aedf8f294fc53aa7/pyspotify-2.1.3.tar.gz (157kB)
    100% |████████████████████████████████| 163kB 342kB/s
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
      Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
ck', 'wheel', '--no-deps', '-w', '/tmp/tmpie1dl884', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y0yf0y2i/pyspotify/setup.py", line 5, in <module>
        cffi_modules=['spotify/_spotify_build.py:ffi']
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/setuptools/__init__.py", line 162, in setup
        _install_setup_requires(attrs)
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/setuptools/__init__.py", line 157, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/setuptools/dist.py", line 702, in fetch_build_eggs
        replace_conflicting=True,
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
        replace_conflicting=replace_conflicting
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/tmp/pip-build-env-1339f1z3/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpie1dl884', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-y0yf0y2i/pyspotify/

**Comment by harveys300** [comment]
I have exactly the same issue.

**Comment by jodal** [comment]
It looks like `pip` have problems building a wheel of `cffi`, which is a dependency of `pyspotify`, which is a dependency of `mopidy-spotify`.

It looks like you're on a Raspberry Pi, so I'm guessing that you're running Raspbian/Debian/Ubuntu. In that case, I'd recommend you to install Mopidy-Spotify from Debian packages as well. See the "Debian" tab at https://mopidy.com/ext/spotify/ for details.

**Comment by 2play** [comment]
@jodal any idea
``` sudo apt install mopidy-spotify
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mopidy-spotify : Depends: python3-spotify (>= 2.0.5) but it is not installable
E: Unable to correct problems, you have held broken packages.

sudo apt install python3-spotify
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-spotify:armhf : Depends: python3:armhf (>= 3~) but it is not going to be installed
                         Depends: python3-cffi-backend-api-min:armhf (<= 9729)
                         Depends: python3-cffi-backend-api-max:armhf (>= 9729)
E: Unable to correct problems, you have held broken packages.```

**Comment by ChrisHilborne** [comment]
I'm having the same problem. Was a fix ever found?

**Comment by kingosticks** [comment]
We no longer use libspotify.
