### ISSUE TITLE
I don't see playlists I've created in the list

### ISSUE THREAD

**Issue by kigero** [mopidy/mopidy-spotify#276]
Are custom playlists that I've created in spotify supported through this plugin?  I've got several playlists that I've created, but I'm not seeing them in the list provided by this plugin.

![image](https://user-images.githubusercontent.com/679688/93023565-e5212480-f5bd-11ea-9f12-fddaa236ad8b.png)

On the left is spotify, the right is what I'm seeing in GMPC (I also see the same list in other clients of mopidy).  Looking through the issues, #48 seems relevant but I'm not sure if this issue is for a new feature or an enhancement to an existing feature.  I do have `allow_playlists = true` in my configuration.

**Comment by kingosticks** [comment]
This was fixed inhttps://github.com/mopidy/mopidy-spotify/releases/tag/v4.0.0a2
