### ISSUE TITLE
'Recently Played' doesn't update properly?

### ISSUE THREAD

**Issue by 01tot10** [mopidy/mopidy-spotify#281]
Hey all!

First of all, thank you for all the effort that has been put into mopidy-spotify (and mopidy in general).
I've been using the service for around a year now, and it has brought lots of joy in my life!

I have a question:

I noticed today, after logging into the official desktop app for Spotify, that my Recently Played playlist doesn't really reflect what I've been listening to in the last year or so. There seems to be some logged instances (part of yesterdays session is there, but nothing from today), which makes the thing the most confusing for me at the moment. I haven't touched the 'private_session' parameter on the mopidy-spotify config, and it has been set to 'false' for all this time.

Does this have something to do with the libspotify vs spotify-web topic, i.e is this known and expected behaviour or am I experiencing a bug of some sort?

Thanks for any insights!

**Comment by TheQwertiest** [comment]
I'm experiencing the same issue.
I think, "Recently Played" logs only tracks played via `Spotify Connect`-enabled players (Spotify web-site being one of them). And `libspotify`, which mopidy uses to actually play tracks, does not support `Spotify Connect` (#110).

**Comment by 01tot10** [comment]
Okay, thought so as well. Good to know the behavior is as expected. I guess there's not much that can be done, as long as the architecture is based on `libspotify`.

**Comment by kingosticks** [comment]
And there's nothing we can do here in Mopidy-Spotify about this so I'm going to close this.
