### ISSUE TITLE
Libspotify12 confirmed installed, still failed at building pinwheel for pyspotify

### ISSUE THREAD

**Issue by jd1103** [mopidy/mopidy-spotify#284]
My previous post was closed so I am creating a new one and referencing what we have already tried:

Previous post issue:
_Originally posted by @jodal in https://github.com/mopidy/mopidy-spotify/issues/283#issuecomment-716173584_

Solution suggested: Install dependencies including libspotify12.

 I should have mentioned this as well-

I have installed libspotify12 and dependencies from the link attached, using sudo apt install libspotify12 and get the following:

Reading package lists... Done
Building dependency tree
Reading state information... Done
libspotify12 is already the newest version (12.1.103-0mopidy1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

From further digging I see a possible root cause that I don't know how to fix-

When I run sudo mopidyctl deps I see the following:

Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
/usr/lib/python2.7/dist-packages/mopidy/ext.py:202: PkgResourcesDeprecationWarning: Parameters to load are deprecated. Call .resolve and .require separately.
extension_class = entry_point.load(require=False)
Executable: /usr/bin/mopidy
Platform: Linux-5.4.72-v7+-armv7l-with-debian-10.6
Python: CPython 2.7.16 from /usr/lib/python2.7
Mopidy: 2.2.3 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify-Web: 0.3.0 from /usr/local/lib/python2.7/dist-packages
setuptools: 40.8.0 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify>=1.2.0: 3.1.0 from /usr/lib/python2.7/dist-packages
Mopidy>=2.0: 2.2.3 from /usr/lib/python2.7/dist-packages
Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
pyspotify>=2.0.5: 2.0.5 from /usr/lib/python2.7/dist-packages
cffi>=1.0.0: 1.12.2 from /usr/lib/python2.7/dist-packages
requests>=2.0: 2.21.0 from /usr/lib/python2.7/dist-packages
spotipy: 2.16.1 from /usr/local/lib/python2.7/dist-packages
requests>=2.20.0: 2.21.0 from /usr/lib/python2.7/dist-packages
six>=1.10.0: 1.12.0 from /usr/lib/python2.7/dist-packages
Mopidy>=0.19.0: 2.2.3 from /usr/lib/python2.7/dist-packages
Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
requests: 2.21.0 from /usr/lib/python2.7/dist-packages
Mopidy-Youtube: 2.0.2 from /usr/local/lib/python2.7/dist-packages
setuptools: 40.8.0 from /usr/lib/python2.7/dist-packages
pafy>=0.3.35: 0.5.5 from /usr/local/lib/python2.7/dist-packages
Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
requests>=2.2.1: 2.21.0 from /usr/lib/python2.7/dist-packages
Mopidy>=1.0: 2.2.3 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify: 3.1.0 from /usr/lib/python2.7/dist-packages
Mopidy>=2.0: 2.2.3 from /usr/lib/python2.7/dist-packages
Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
pyspotify>=2.0.5: 2.0.5 from /usr/lib/python2.7/dist-packages
cffi>=1.0.0: 1.12.2 from /usr/lib/python2.7/dist-packages
requests>=2.0: 2.21.0 from /usr/lib/python2.7/dist-packages
GStreamer: 1.14.4.0 from /usr/lib/python2.7/dist-packages/gi
Detailed information:
Python wrapper: python-gi 3.30.4
Relevant elements:
Found:
uridecodebin
souphttpsrc
appsrc
alsasink
osssink
oss4sink
pulsesink
id3demux
id3v2mux
lamemp3enc
mpegaudioparse
mpg123audiodec
vorbisdec
vorbisenc
vorbisparse
oggdemux
oggmux
oggparse
flacdec
flacparse
shout2send
Not found:
flump3dec
mad

It looks like it's pulling stuff using python2 when it should be using python3. I'm not nearly experienced or intelligent enough to figure out what this means or how to solve it.

Thanks again,
-Jon

**Comment by jodal** [comment]
I reopened the first issue.
