### ISSUE TITLE
Provide an option to use librespot as backend library

### ISSUE THREAD

**Issue by mgrouch** [mopidy/mopidy-spotify#285]
https://github.com/librespot-org/librespot

**Comment by mgrouch** [comment]
Also arm64 support is needed

**Comment by TheQwertiest** [comment]
See https://github.com/mopidy/mopidy-spotify/issues/110

**Comment by kingosticks** [comment]
See https://github.com/mopidy/mopidy-spotify/pull/342

**Comment by kingosticks** [comment]
https://github.com/mopidy/mopidy-spotify/pull/342 was merged. I'd like to see it used more before we cut a release. I've had some teething problem with it. Note you currently need to build gst-plugins-spotify from source, instructions are at https://github.com/mopidy/mopidy-spotify#dependencies
