### ISSUE TITLE
No search function available?

### ISSUE THREAD

**Issue by schui95** [mopidy/mopidy-spotify#288]
Hello

I'm using mopidy + mopidy-spotify since several days and I wonder where the search function to go through the library of spotify is? I can only find my playlists and downloaded albums of spotify. Do I miss something? 

Thanks for any help!

![image](https://user-images.githubusercontent.com/41399294/99222640-44c8c580-27e3-11eb-8516-9da895320ffd.png)
![image](https://user-images.githubusercontent.com/41399294/99222662-4e522d80-27e3-11eb-832c-a47bb7fea344.png)

**Comment by Simon-the-Sorcerer** [comment]
It looks like you are using ncmpcpp an a mpd client. The search function can be found in ncmpcpp under "3".

1 current playlist
2 library
3 Search
