### ISSUE TITLE
Mopidy getting stuck on restart

### ISSUE THREAD

**Issue by tone77777** [mopidy/mopidy-spotify#289]
Mopidy loads fine for me - however if I add the configuration lines for spotify, i.e.

```
[spotify]
enabled = true
client_id = **
client_secret = **
username = **
password = **
```

When I try to restart Mopidy as a server, it stops on the following lines:

```
Nov 23 22:22:03 raspberrypi mopidy[24168]: INFO     [SpotifyBackend-6] mopidy_spotify.web Logged into Spotify Web API as antoniogould
Nov 23 22:22:18 raspberrypi mopidy[24168]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Logged in to Spotify in online mode
```

And doesn't go further - meaning that Mopidy doesn't start up. 

If I comment out the spotify configuration lines, it loads perfectly. 

Any ideas on what's wrong here?

**Comment by jodal** [comment]
Have you tried connecting a client to Mopidy? Might it be that those log lines are just the last ones that are outputted because no clients have tried connecting yet?

**Comment by tone77777** [comment]
Hi Stein, thanks for your reply - I logged in this morning and it was
suddenly working!

Thanks again

**Comment by jodal** [comment]
Great :-)
