### ISSUE TITLE
Secrets in password manager instead of the config file

### ISSUE THREAD

**Issue by antonmry** [mopidy/mopidy-spotify#292]
I don't find a way to avoid password and OAuth credentials in the config file. It would be ideal if we can use a password manager like gopass or similar.

**Comment by TheLugal** [comment]
Many programs have a _passwordeval_ directive, for a user to add some command that evaluates to a password, like `passwordeval = gpg --decrypt ~/.passwords/spotify.gpg"`, or using pass or gopass or what have you. Something like that would be awesome, and arguably make it more secure.

**Comment by Laptop765** [comment]
This is already possible today: https://github.com/mopidy/mopidy/issues/116#issuecomment-18026012.  It's been a while since I set mine up but I can try to answer any questions you have!

**Comment by antonmry** [comment]
I have interest yet but no idea how to start. Some help would be appreciated.

**Comment by kingosticks** [comment]
We have https://github.com/mopidy/mopidy-spotify/issues/305 to track one possible alternative, [plus the already mentioned Mopidy issue](https://github.com/mopidy/mopidy-spotify/issues/292#issuecomment-764465083).
