### ISSUE TITLE
Using on PopOS and when I start I get this

### ISSUE THREAD

**Issue by TrevorGilstrap** [mopidy/mopidy-spotify#300]
I have done my config file at the bottom added
[spotify]
username = username
password = password
client_id = clientid
client_secret = clientsecret

and I get this error on start up still and nothing happens

`<pre><font color="#CC0000">ERROR    2021-01-17 13:08:56,192 [20679:SpotifyBackend-6] pykka</font>
<font color="#CC0000">  Unhandled exception in SpotifyBackend (urn:uuid:fa24073e-54f0-40de-80c9-415973dfe69d):</font>
<font color="#CC0000">Traceback (most recent call last):</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/requests/models.py&quot;, line 380, in prepare_url</font>
<font color="#CC0000">    scheme, auth, host, port, path, query, fragment = parse_url(url)</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/urllib3/util/url.py&quot;, line 392, in parse_url</font>
<font color="#CC0000">    return six.raise_from(LocationParseError(source_url), None)</font>
<font color="#CC0000">  File &quot;&lt;string&gt;&quot;, line 2, in raise_from</font>
<font color="#CC0000">urllib3.exceptions.LocationParseError: Failed to parse: https://auth.mopidy.com/spotify/token</font>

<font color="#CC0000">During handling of the above exception, another exception occurred:</font>

<font color="#CC0000">Traceback (most recent call last):</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/pykka/_actor.py&quot;, line 186, in _actor_loop</font>
<font color="#CC0000">    self.on_start()</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/mopidy_spotify/backend.py&quot;, line 65, in on_start</font>
<font color="#CC0000">    self._web_client.login()</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/mopidy_spotify/web.py&quot;, line 424, in login</font>
<font color="#CC0000">    self.user_id = self.get(&quot;me&quot;).get(&quot;id&quot;)</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/mopidy_spotify/web.py&quot;, line 89, in get</font>
<font color="#CC0000">    self._refresh_token()</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/mopidy_spotify/web.py&quot;, line 124, in _refresh_token</font>
<font color="#CC0000">    result = self._request_with_retries(</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/mopidy_spotify/web.py&quot;, line 152, in _request_with_retries</font>
<font color="#CC0000">    prepared_request = self._session.prepare_request(</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/requests/sessions.py&quot;, line 449, in prepare_request</font>
<font color="#CC0000">    p.prepare(</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/requests/models.py&quot;, line 314, in prepare</font>
<font color="#CC0000">    self.prepare_url(url, params)</font>
<font color="#CC0000">  File &quot;/usr/lib/python3/dist-packages/requests/models.py&quot;, line 382, in prepare_url</font>
<font color="#CC0000">    raise InvalidURL(*e.args)</font>
<font color="#CC0000">requests.exceptions.InvalidURL: Failed to parse: https://auth.mopidy.com/spotify/token</font>
<font color="#CC0000">ERROR    2021-01-17 13:08:56,203 [20679:MainThread] mopidy.commands</font>
<font color="#CC0000">  Actor died: SpotifyBackend (urn:uuid:fa24073e-54f0-40de-80c9-415973dfe69d) stopped before handling the message</font>
</pre>`

**Comment by kingosticks** [comment]
Sorry you never got any help with this.

The URL https://auth.mopidy.com/spotify/token looks very reasonable so I don't understand why requests/urllib can't parse it. Please re-open this issue if it's still relevant and we'll look into it.
