### ISSUE TITLE
Error during searching for a track

### ISSUE THREAD

**Issue by Dzordzu** [mopidy/mopidy-spotify#302]
## Error
```
SpotifyBackend does not implement library.search() with "exact" support. Please upgrade it.
```

## Steps to reproduce
1. Start ncmpcpp (or musicbox)
2. Type Bruno Mars in "Artist" field
3. Nothing happens, warning is raised

## Client
- ncmpcpp
- musicbox

## Version
| Name                      | Version |
|---------------------------|---------|
| Mopidy                    | 3.1.1   |
| Mopidy-Spotify            | 4.1.1   |
| Mopidy-MusicBox-Webclient | 3.1.0   |
| Mopidy-MPD                | 3.1.0   |

Edit: it appears that some bands work (ex. Metallica), but some are unavailable (like Bruno Mars)

**Comment by Dzordzu** [comment]
Strange? It appears that only Bruno Mars is affected xD

**Comment by Dzordzu** [comment]
What tha heck?

**Comment by Dzordzu** [comment]
It seems to be a "it work for me" kind of issue. A little time and issue disappeared

**Comment by kingosticks** [comment]
This might have been due to https://github.com/mopidy/mopidy-spotify/issues/280 and fixed in https://github.com/mopidy/mopidy-spotify/pull/325
