### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by chbren** [mopidy/mopidy-spotify#306]
Hi! 
During Authentication (https://mopidy.com/ext/spotify/#authentication) pop-up opens and does not load. The process ends with "ERR_CONNECTION_TIMED_OUT" error in the pop-up. Finally, no client_id and client_secret are provided. 

What dit not help:
- use a differend device with different Internet Connection
- update browser (Chrome)
- update Spotify app

What can I do to solve this issue? 

Best Regards
Christian

**Comment by chbren** [comment]
there is an annouced down time: https://discourse.mopidy.com/t/mopidy-spotify-authentication-downtime-2021-04-14-2030-cest/4881

**Comment by adamcik** [comment]
And we are back again now, if the plugin behaved strangely during the outage that would be useful to know. Ideally the popup handling etc would be a bit more robust against the host being down, but I don't think that's worth fixing.

Instead we should focus on changing to the new authentication type Spotify supports which isn't reliant on auth.mopidy.org as a go between to keep the oauh secrets safe.
