### ISSUE TITLE
Error while installing: Could not build wheels for pyspotify which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by Kyllingene** [mopidy/mopidy-spotify#307]
On a fully-updated, Windows 10 computer running a fully-updated installation of PIP, full permissions, I get this error when attempting to install mopidy-spotify (full logs):

```
> pip3 install Mopidy-Spotify
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: c:\users\me\appdata\local\programs\python\python39\Include\UNKNOWN
sysconfig: c:\users\me\appdata\local\programs\python\python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting Mopidy-Spotify
  Using cached Mopidy_Spotify-4.1.1-py3-none-any.whl (31 kB)
Collecting pyspotify>=2.0.5
  Using cached pyspotify-2.1.3.tar.gz (157 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in c:\users\me\appdata\local\programs\python\python39\lib\site-packages (from Mopidy-Spotify) (50.3.2)
Collecting Mopidy>=3.0.0
  Using cached Mopidy-3.1.1-py3-none-any.whl (125 kB)
Requirement already satisfied: requests>=2.20.0 in c:\users\me\appdata\local\programs\python\python39\lib\site-packages (from Mopidy-Spotify) (2.24.0)
Collecting Pykka>=2.0.1
  Using cached pykka-3.0.0-py3-none-any.whl (27 kB)
Collecting tornado>=4.4
  Using cached tornado-6.1-cp39-cp39-win_amd64.whl (422 kB)
Collecting cffi>=1.0.0
  Using cached cffi-1.14.5-cp39-cp39-win_amd64.whl (179 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\me\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.20.0->Mopidy-Spotify) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in c:\users\me\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.20.0->Mopidy-Spotify) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\me\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.20.0->Mopidy-Spotify) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\me\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.20.0->Mopidy-Spotify) (2020.11.8)
Building wheels for collected packages: pyspotify
  Building wheel for pyspotify (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\me\appdata\local\programs\python\python39\python.exe' 'c:\users\me\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\me\AppData\Local\Temp\tmpthnjyqsq'
       cwd: C:\Users\me\AppData\Local\Temp\pip-install-_2475ebz\pyspotify_c81444057ce541478b94ea85adee1155
  Complete output (62 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\spotify
  copying spotify\album.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\artist.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\audio.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\compat.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\config.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\connection.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\error.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\eventloop.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\image.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\inbox.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\link.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\offline.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\player.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\playlist.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\playlist_container.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\playlist_track.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\playlist_unseen_tracks.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\search.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\session.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\sink.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\social.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\toplist.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\track.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\user.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\utils.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\version.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\_spotify_build.py -> build\lib.win-amd64-3.9\spotify
  copying spotify\__init__.py -> build\lib.win-amd64-3.9\spotify
  running egg_info
  writing pyspotify.egg-info\PKG-INFO
  writing dependency_links to pyspotify.egg-info\dependency_links.txt
  writing requirements to pyspotify.egg-info\requires.txt
  writing top-level names to pyspotify.egg-info\top_level.txt
  warning: the 'license_file' option is deprecated, use 'license_files' instead
  adding license file 'LICENSE' (matched pattern 'LICENSE')
  reading manifest file 'pyspotify.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*' under directory '.github'
  no previously-included directories found matching 'docs\_build'
  no previously-included directories found matching 'examples\tmp'
  warning: no previously-included files matching '__pycache__\*' found anywhere in distribution
  writing manifest file 'pyspotify.egg-info\SOURCES.txt'
  copying spotify\api.h -> build\lib.win-amd64-3.9\spotify
  copying spotify\api.processed.h -> build\lib.win-amd64-3.9\spotify
  running build_ext
  generating cffi module 'build\\temp.win-amd64-3.9\\Release\\spotify._spotify.c'
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  building 'spotify._spotify' extension
  creating build\temp.win-amd64-3.9\Release\build
  creating build\temp.win-amd64-3.9\Release\build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release\build\temp.win-amd64-3.9\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\me\appdata\local\programs\python\python39\include -Ic:\users\me\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcbuild\temp.win-amd64-3.9\Release\spotify._spotify.c /Fobuild\temp.win-amd64-3.9\Release\build\temp.win-amd64-3.9\Release\spotify._spotify.obj
  spotify._spotify.c
  build\temp.win-amd64-3.9\Release\spotify._spotify.c(569): fatal error C1083: Cannot open include file: 'libspotify/api.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for pyspotify
Failed to build pyspotify
ERROR: Could not build wheels for pyspotify which use PEP 517 and cannot be installed directly
```

**Comment by jodal** [comment]
Mopidy-Spotify depends on [pyspotify](https://github.com/jodal/pyspotify) which depends on [libspotify](https://mopidy.github.io/libspotify-archive/). As such, this is a pyspotify issue, and only indirectly a Mopidy-Spotify issue.

I don't know if anyone has ever tried installing pyspotify on Windows. To get that working, you at least need to have libspotify installed. There's a Win32/x86 build of libspotify available at the above link, which might be a start.

**Comment by Kyllingene** [comment]
Oh, thank you! Sorry for that, will keep trying!

**Comment by psomdeb25** [comment]
I have installed libspotify and have also sym linked it to /Library/Frameworks/ directory however the pyspotify still fails.

Output of ls-l # Shows that libspotify exists
> total 0
> lrwxr-xr-x  1 root  admin  51 14 Jan 00:50 libspotify -> /Library/Frameworks/libspotify.framework/libspotify

pyspotify install error after pip install pyspotify:

`Collecting pyspotify
  Downloading pyspotify-2.1.3.tar.gz (157 kB)
     |████████████████████████████████| 157 kB 2.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools in /Users/somdebpaul/opt/anaconda3/lib/python3.8/site-packages (from pyspotify) (49.2.0.post20200714)
Requirement already satisfied: cffi>=1.0.0 in /Users/somdebpaul/opt/anaconda3/lib/python3.8/site-packages (from pyspotify) (1.14.0)
Requirement already satisfied: pycparser in /Users/somdebpaul/opt/anaconda3/lib/python3.8/site-packages (from cffi>=1.0.0->pyspotify) (2.20)
Building wheels for collected packages: pyspotify
  Building wheel for pyspotify (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/somdebpaul/opt/anaconda3/bin/python /Users/somdebpaul/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/7h/z3vl3b7j1rng50m39zv12r2c0000gn/T/tmp9r_ivwvy
       cwd: /private/var/folders/7h/z3vl3b7j1rng50m39zv12r2c0000gn/T/pip-install-s0aea1tx/pyspotify_ca7eb089af7f4dc695d0b347b150d850
  Complete output (52 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/_spotify_build.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/link.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/user.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/social.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/config.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/version.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/compat.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/error.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/sink.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/track.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/playlist_unseen_tracks.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/session.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/offline.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/eventloop.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/album.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/artist.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/connection.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/playlist_track.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/playlist_container.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/utils.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/player.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/playlist.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/inbox.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/search.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/audio.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/toplist.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/image.py -> build/lib.macosx-10.9-x86_64-3.8/spotify
  running egg_info
  warning: no files found matching '*' under directory '.github'
  no previously-included directories found matching 'docs/_build'
  no previously-included directories found matching 'examples/tmp'
  warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
  writing manifest file 'pyspotify.egg-info/SOURCES.txt'
  copying spotify/api.h -> build/lib.macosx-10.9-x86_64-3.8/spotify
  copying spotify/api.processed.h -> build/lib.macosx-10.9-x86_64-3.8/spotify
  running build_ext
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/build
  creating build/temp.macosx-10.9-x86_64-3.8/build/temp.macosx-10.9-x86_64-3.8
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/somdebpaul/opt/anaconda3/include -arch x86_64 -I/Users/somdebpaul/opt/anaconda3/include -arch x86_64 -I/Users/somdebpaul/opt/anaconda3/include/python3.8 -c build/temp.macosx-10.9-x86_64-3.8/spotify._spotify.c -o build/temp.macosx-10.9-x86_64-3.8/build/temp.macosx-10.9-x86_64-3.8/spotify._spotify.o
  build/temp.macosx-10.9-x86_64-3.8/spotify._spotify.c:569:10: fatal error: 'libspotify/api.h' file not found
  #include "libspotify/api.h"
           ^~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pyspotify
Failed to build pyspotify
ERROR: Could not build wheels for pyspotify, which is required to install pyproject.toml-based projects
`

**Comment by Kyllingene** [comment]
Please reformat the comment; it is a pain to read when it's so large.

**Comment by psomdeb25** [comment]
@Kyllingene Is that better now.

**Comment by Kyllingene** [comment]
Much, thank you.

**Comment by psomdeb25** [comment]
I don't mind looking into what is the problem. But I was wondering how should I start looking into it. One thing I feel is that I conda environments in which I diffferent versions of python. So, when I tried using pip from one of those conda environments I was getting a completely different sort of error. Therefore deactivated that conda environment and tried installing pyspotify using pip from the base environment. The download worked so the python environment seems fine. Now the build process seems to have some isssue.

**Comment by Kyllingene** [comment]
I couldn't quite figure out what you meant; if you got the error you posted, then fixed it, please post the new error. If you got this new error, it means you need to refer to [the above comment](https://github.com/mopidy/mopidy-spotify/issues/307#issuecomment-828370769) from the owner, since they have already explained the situation; your problem is the same as mine, the inability for some step in the build process to find `libspotify/api.h`.

**Comment by LuiBi10** [comment]
Hey! I know the theme is closed but just for curiosity,  someone can found the solution?
