### ISSUE TITLE
Spotify browsing with non-Premium account crashes system

### ISSUE THREAD

**Issue by liftarn** [mopidy/mopidy-spotify#32]
As mentioned at woutervanwijk/Pi-MusicBox#184
>I have a non premium spotify account and browsing through the spotify section of the webinterface brings up "no tracks" messages everywhere except for when I click on "Personal top tracks", which causes the playback to freeze immediately and also kills the webinterface. The pi is only reachable via ssh after that to issue a reboot.

**Comment by jodal** [comment]
I'd sure like Mopidy-Spotify to fail nicer for non-Premium accounts. I guess I can make a new free account just to test this, but if you have the time, can you please:

1. Run Mopidy with `mopidy --debug-log`.
2. Reproduce the issue.
3. Stop Mopidy with Ctrl+C or similar.
3. Share the `mopidy.log` file that is produced on a pastebin and link to it here.

Thanks!

**Comment by jodal** [comment]
Mopidy-Spotify 2 already fails quite nicely for non-premium accounts. I just tested, and this is the output:

```
[...]
INFO     Starting Mopidy backends: SpotifyTunigoBackend, LocalBackend, StreamBackend, SpotifyBackend/home/jodal/.local/share/mopidy/local/playlists                                                                         
INFO     Audio output set to "autoaudiosink"
INFO     Loaded 4021 local tracks using json
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: ScrobblerFrontend, MpdFrontend, HttpFrontend
INFO     MPD server running at [::]:6600
INFO     HTTP server running at [::]:6680
ERROR    Spotify login error: <ErrorType.USER_NEEDS_PREMIUM: 15>
INFO     Scrobbler connected to Last.fm
```

When trying to search, the Spotify part of the search is aborted, but the search continues in other backends:

```
INFO     Search aborted: Spotify is offline
```

With a change today, lookup when offline also behaves properly:

```
INFO     Failed to lookup "spotify:track:33yU4Aj4JbFv1j71aX0z71": Session must be logged in and online to load objects: <ConnectionState.LOGGED_OUT: 0>
```

From what I can see, this should not be an issue with Mopidy-Spotify 2. Closing.

**Comment by lvillamarin-chwy** [comment]
> Mopidy-Spotify 2 already fails quite nicely for non-premium accounts. I just tested, and this is the output:
> 
> ```
> [...]
> INFO     Starting Mopidy backends: SpotifyTunigoBackend, LocalBackend, StreamBackend, SpotifyBackend/home/jodal/.local/share/mopidy/local/playlists                                                                         
> INFO     Audio output set to "autoaudiosink"
> INFO     Loaded 4021 local tracks using json
> INFO     Starting Mopidy core
> INFO     Starting Mopidy frontends: ScrobblerFrontend, MpdFrontend, HttpFrontend
> INFO     MPD server running at [::]:6600
> INFO     HTTP server running at [::]:6680
> ERROR    Spotify login error: <ErrorType.USER_NEEDS_PREMIUM: 15>
> INFO     Scrobbler connected to Last.fm
> ```
> 
> When trying to search, the Spotify part of the search is aborted, but the search continues in other backends:
> 
> ```
> INFO     Search aborted: Spotify is offline
> ```
> 
> With a change today, lookup when offline also behaves properly:
> 
> ```
> INFO     Failed to lookup "spotify:track:33yU4Aj4JbFv1j71aX0z71": Session must be logged in and online to load objects: <ConnectionState.LOGGED_OUT: 0>
> ```
> 
> From what I can see, this should not be an issue with Mopidy-Spotify 2. Closing.

I am premium user and I'm getting this error message.

**Comment by adamcik** [comment]
https://developer.spotify.com/community/news/2022/04/12/libspotify-sunset/ - i.e. they turned down the backend for the system we relied one. Please follow #110 for possible updates.
