### ISSUE TITLE
Spotify login error: <ErrorType.USER_NEEDS_PREMIUM: 15>

### ISSUE THREAD

**Issue by adrhc** [mopidy/mopidy-spotify#321]
As you can see, mopidy managed to get an access token (the client id and secret are ok) but the user is not permitted access because I have no premium. My configuration includes both client id and secret and username (the generated one) and password; without username and password the plugin is automatically disabled (I saw this with `mopidy config`).

INFO     2021-11-24 10:05:48,531 [409924:SpotifyBackend-8] mopidy.internal.path
  Creating dir file:///home/gigikent/.cache/mopidy/spotify
INFO     2021-11-24 10:05:48,541 [409924:MainThread] mopidy.internal.path
  Creating dir file:///home/gigikent/.config/mopidy/podcast
INFO     2021-11-24 10:05:48,553 [409924:SpotifyBackend-8] mopidy.internal.path
  Creating dir file:///home/gigikent/.local/share/mopidy/spotify
DEBUG    2021-11-24 10:05:48,558 [409924:SpotifyBackend-8] mopidy_spotify.web
  Fetching OAuth token from https://auth.mopidy.com/spotify/token
ERROR    2021-11-24 10:05:49,154 [409924:SpotifyEventLoop] spotify.session
  Spotify login error: <ErrorType.USER_NEEDS_PREMIUM: 15>
DEBUG    2021-11-24 10:05:49,155 [409924:SpotifyEventLoop] mopidy_spotify.backend
  Logged out of Spotify
DEBUG    2021-11-24 10:05:49,155 [409924:SpotifyEventLoop] mopidy_spotify.backend
  Logged out of Spotify
INFO     2021-11-24 10:05:49,401 [409924:YouTubeBackend-5] mopidy_youtube
  YouTube API key verified
INFO     2021-11-24 10:05:49,401 [409924:YouTubeBackend-5] mopidy_youtube
  Using YouTube Music API
DEBUG    2021-11-24 10:05:49,639 [409924:SomaFMBackend-9] mopidy_somafm.somafm
  Get https://api.somafm.com/channels.xml : 200
INFO     2021-11-24 10:05:49,640 [409924:SomaFMBackend-9] mopidy_somafm.somafm
  Loaded 42 SomaFM channels
DEBUG    2021-11-24 10:05:49,855 [409924:Thread-6] mopidy_ytmusic
  YTMusic updated player URL to /s/player/10df06bb/player_ias.vflset/en_US/base.js
DEBUG    2021-11-24 10:05:49,985 [409924:SpotifyBackend-8] mopidy_spotify.web
  Token expires in 3600 seconds.
DEBUG    2021-11-24 10:05:49,986 [409924:SpotifyBackend-8] mopidy_spotify.web
  Token scopes: playlist-read-private playlist-read-collaborative streaming user-library-read user-follow-read user-library-modify playlist-modify-private playlist-modify-public user-read-recently-played user-read-private user-top-read
INFO     2021-11-24 10:05:50,123 [409924:SpotifyBackend-8] mopidy_spotify.web
  Logged into Spotify Web API as ln4p6hf8wpdim5b08pu3koz1j
DEBUG    2021-11-24 10:05:50,395 [409924:Thread-6] mopidy_ytmusic
  YTMusic updated signatureTimestamp to 18954
DEBUG    2021-11-24 10:05:50,396 [409924:Thread-6] mopidy_ytmusic
  YTMusic Player URL refreshed in 1.91s
INFO     2021-11-24 10:05:50,396 [409924:SpotifyBackend-8] mopidy_spotify.playlists
  Refreshed 0 Spotify playlists
DEBUG    2021-11-24 10:05:50,396 [409924:SpotifyBackend-8] mopidy_spotify.utils
  playlists.refresh() took 271ms

**Comment by jodal** [comment]
Quoting the project README:

> A Spotify Premium subscription. Mopidy-Spotify will not work with Spotify Free, just Spotify Premium.
