### ISSUE TITLE
find_exact not supported

### ISSUE THREAD

**Issue by rawdlite** [mopidy/mopidy-spotify#33]
I know Spotify doesn't support exact search , but could'nt we filter out the inexact results after the search result got back from spotify? 
I am developing a headless client ( https://discuss.mopidy.com/t/developing-a-headless-client-for-mopidy/509 ) that features play related artist and play more of this artist. With the inexact search results from spotify this leads to some rather surprising results.

**Comment by kingosticks** [comment]
Please see https://github.com/mopidy/mopidy-spotify/issues/11
