### ISSUE TITLE
OAuth token refresh failed: Unknown error

### ISSUE THREAD

**Issue by chiguire** [mopidy/mopidy-spotify#334]
Hi, I've been getting this error when doing a search in songs. Maybe it's a transient error, but I'm wondering whether anyone else has got this error as well.

From the logs:
bamp              | ERROR    2022-04-01 09:55:38,362 [7:SpotifyBackend-5] mopidy_spotify.web
bamp              |   OAuth token refresh failed: Unknown error.

**Comment by kingosticks** [comment]
I've never hit this, if you or anyone else are still hitting this (even intermittently) then we can re-open and look more closely.
