### ISSUE TITLE
playlist folder organization

### ISSUE THREAD

**Issue by seniorkiller** [mopidy/mopidy-spotify#337]
spotify have folder to organize playlist. is it posible to structure the playlist just like in the spotify?
it would be nice if could be implemented especially because i have discover weekly archive that looks really bad when not using folder

![image](https://user-images.githubusercontent.com/77882062/168105329-254febc5-25b2-451a-99ed-fca7accf7847.png)

![image](https://user-images.githubusercontent.com/77882062/168105257-53eb594d-8adf-4794-a5fe-d2462ced5549.png)

**Comment by kingosticks** [comment]
Spotify no longer support folders as far as I know.

**Comment by jodal** [comment]
I still have folders in my Spotify client. Here's a screenshot from my phone.

![Screenshot_20241008-134113.png](https://github.com/user-attachments/assets/126c9607-f4f4-4c04-af4c-d868080c4af9)

**Comment by kingosticks** [comment]
Correct me if I am wrong, but I don't think you can create them any more. The Web API doesn't support them at all.

**Comment by kingosticks** [comment]
I will correct myself, you can create them (in the desktop client, at least).

**Comment by kingosticks** [comment]
https://support.spotify.com/us/article/playlist-folders/

> You need to use the desktop app or web player to make playlist folders, but they show on all devices.

https://developer.spotify.com/documentation/web-api/concepts/playlists

> Folders are not returned through the Web API, nor can be created using it.

There's an issue at https://github.com/spotify/web-api/issues/38 but they'll obviously never implement it because they're only a multibillion dollar company.
