### ISSUE TITLE
Spotify premium login error, even though I have a premium account?

### ISSUE THREAD

**Issue by zackartz** [mopidy/mopidy-spotify#338]
Hi! I am recieving the following error.

```
May 16 09:33:08 puter mopidy[5122]: ERROR    2022-05-16 09:33:08,458 [5122:SpotifyEventLoop] spotify.session
May 16 09:33:08 puter mopidy[5122]:   Spotify login error: <ErrorType.USER_NEEDS_PREMIUM: 15>
May 16 09:33:09 puter mopidy[5122]: INFO     2022-05-16 09:33:09,316 [5122:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web
May 16 09:33:09 puter mopidy[5122]:   Logged into Spotify Web API as kdh4e79lhqjk3n9r4co7u84pg
```
I do have a premium (family plan) account, I am the one hosting the family plan.

Also, to make things more confusing, [spot](https://github.com/xou816/spot) works, and I checked that the account `kdh4e79lhqjk3n9r4co7u84pg` is the same in both.

**Comment by lv10** [comment]
I have the same issue, I have a family plan, and I"m one that's hosting the family plan. Extra details:

1. I confirmed that I have a premium family plan
2. I have uninstalled mopidy
3. I have followed the the Authentication steps
4. I have restart my machine, restart mopidy
5. It started failing today

After I get the same error message that @zackartz I tried to load my playlists and I get:
```
INFO     2022-05-16 15:45:44,993 [175109:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.lookup
  Failed to lookup 'spotify:track:0aRxi5STXvdVVWi4zi18B5': Session must be logged in and online to load objects: <ConnectionState.LOGGED_OUT: 0>
```
Even though in the same logs I see this:
```
INFO     2022-05-16 15:45:35,524 [175109:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web
  Logged into Spotify Web API as my_username
2INFO     2022-05-16 15:45:42,170 [175109:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.playlists
  Refreshed 20 Spotify playlists

```

**Comment by NicoJusso** [comment]
I have the same problem from from today while it was working perfectly before and while I didn't change anything.

**Comment by adamcik** [comment]
https://developer.spotify.com/community/news/2022/04/12/libspotify-sunset/ - i.e. they turned down the backend for the system we relied on. Please follow #110 for possible updates.

**Comment by chris-aeviator** [comment]
I was playing music today (cached?) when suddenly it stopped. I have many

```
Session must be logged in and online to load objects:
```

errors in my log even though after revoking the API key and re-authorizing I can see a successful session login followed by many "Session must be logged in..."
