### ISSUE TITLE
Alternative for libspotify

### ISSUE THREAD

**Issue by rjoehren** [mopidy/mopidy-spotify#340]
Hey everyone involved in this project, thanks for this really cool extension. I was using it very greatfully to connect my daughter's phoniebox with Spotify.
As we all know what happened to libspotify recently, I was wondering if that could be replace by something else, not necessarily the spotify web API. 
I was made aware of these
https://github.com/librespot-org/librespot
https://github.com/dtcooper/raspotify

Since I'm software-engineering-wise not on a level that I can contribute in coding, maybe some of you are able to assess whether this is helpful. Probably you are already aware of these.

Thanks again for the great job you did with the Spotify extension.

Regards
Raphael Jöhren

**Comment by vvdan** [comment]
my cafe music system went down because of this. I was using mopidy + mopidy_party extension to let me customers add their next favourite song in the queue.

Happy to have a monthly pay app to get back the system up and running. Such a shame this has stopped working.

**Comment by adamcik** [comment]
Please see #110

**Comment by rjoehren** [comment]
@adamcik I just read all the comments on #110. Should have checked more carefully before suggesting stuff you were already aware of for years xD.
