### ISSUE TITLE
RecvError panic during spotifyaudiosrc playback 

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy-spotify#352]
```
Mar 27 15:53:58 raspberrypi mopidy[30917]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', audio/spotify/src/spotifyaudiosrc/imp.rs:341:37
Mar 27 15:53:58 raspberrypi mopidy[30917]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 27 15:53:58 raspberrypi mopidy[30917]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Panicked: called `Result::unwrap()` on an `Err` value: RecvError
Mar 27 15:53:58 raspberrypi mopidy[30917]: DEBUG    [MainThread] mopidy.audio.gst Got ERROR bus message: error=GLib.Error('Panicked: called `Result::unwrap()` on an `Err` value: RecvError', 'gst-library-error-quark', 1) debug=None
Mar 27 15:53:58 raspberrypi mopidy[30917]: DEBUG    [MainThread] mopidy.audio.gst Changing state to GST_STATE_NULL: result=GST_STATE_CHANGE_SUCCESS
```

It's also not very obvious what version of spotifyaudiosrc is being used. Logging/debug needs improvements.

**Comment by beaverking1212** [comment]
Does this crash mopidy or playback of next song works? Can we reproduce this error?

**Comment by kingosticks** [comment]
I think I had to restart Mopidy but that might have been because my USB soundcard was emitting a horrible loud noise following this. 

I've not been able to reproduce it since.

**Comment by simmel** [comment]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', audio/spotify/src/spotifyaudiosrc/imp.rs:250:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR    2024-02-05 14:55:35,983 [25858:MainThread] mopidy.audio.gst
  GStreamer error: Panicked: called `Result::unwrap()` on an `Err` value: RecvError
```

I had a similar (the same?) panic with this code https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/9556abb162aee996296ce893238e2c1bb5842704/audio/spotify/src/spotifyaudiosrc/imp.rs#L250

I did a local patch to see if that fixed it but I can't reproduce the error. For me it comes after a long time and usually while (or close to) switching between songs. I can wait it out but it takes a long time for the gst plugin to recover. I suspect setting some timeouts somewhere will make it recover faster.

**Comment by kingosticks** [comment]
I've never reproduced this so I'm going to close it. 

> but it takes a long time for the gst plugin to recover. I suspect setting some timeouts somewhere will make it recover faster.

I think this is an issue in its own right so I've created https://github.com/mopidy/mopidy-spotify/issues/398

**Comment by PureTryOut** [comment]
I'm getting this several times a day:

```
thread '<unnamed>' panicked at audio/spotify/src/spotifyaudiosrc/imp.rs:296:37:
called `Result::unwrap()` on an `Err` value: RecvError
```

Then again, I think that's a gst-plugins-spotify problem, not a Mopidy problem. At least Mopidy recovers better than it used to do: in the past I had to fully restart the container running the server because it completely hang, now Mopidy restarts itself and I "just" have to restart the playlist, set volume and enable "consume mode" (can that be enabled from a config...?). Still annoying though.

**Comment by kingosticks** [comment]
Any chance you can compile gst-plugin-spotify with [extra logging enabled](https://gitlab.freedesktop.org/kingosticks/gst-plugins-rs/-/commit/82f81031968037ff6607963da4e84f240e07651d) and catch this happening?

**Comment by kingosticks** [comment]
(it's on my list of things to do to get the extra logging merged upstream)
