### ISSUE TITLE
https://auth.mopidy.com/spotify/ not responding

### ISSUE THREAD

**Issue by jagjordi** [mopidy/mopidy-spotify#355]
Hello,
I manage to successfully install the package following the instructions in Readme.
However I cannot authenticate using the website:
![image](https://user-images.githubusercontent.com/14058667/229475486-e42293ed-541a-4b21-9fbb-a18c8a66c080.png)
I tried to use an old token from ~1 year ago (before libspotify was deprecated etc.) but it doesnt work. (maybe it expired?)

**Comment by kingosticks** [comment]
@adamcik do we have a hosting problem?
