### ISSUE TITLE
Unable to install mopidy-spotify on Rpi 3 (RaspOS bullseye)

### ISSUE THREAD

**Issue by mkono87** [mopidy/mopidy-spotify#360]
Mopidy installs with out issue but when trying to install the spotify plug in I get this

The following packages have unmet dependencies:
 mopidy-spotify : Depends: python3-spotify (>= 2.0.5) but it is not installable
E: Unable to correct problems, you have held broken packages.

I tried to install python3-spotify but it doesnt seem to work. Is it just not supported on the R3?

**Comment by kingosticks** [comment]
https://github.com/mopidy/mopidy-spotify/issues/358#issuecomment-1518591945
