### ISSUE TITLE
cargo build of gst-plugin-spotify stuck at 288/298 

### ISSUE THREAD

**Issue by faspina** [mopidy/mopidy-spotify#372]
Ran 
`cargo build --package gst-plugin-spotify --release`

As described in read me 
its been sitting on this line for good hour 

'Building [=======================> ] 288/298: gstreamer, librespot-core, librespot-metadata, librespot-protocol'

I got a few 'warning: build failed, waiting for other jobs to finish...' but reran it to get through those.  

How long should it take on  Raspberry Pi 3B+

**Comment by JanPedaal** [comment]
I had the same problem on my OrangePi. Have you tried adding the -- jobs 1 flag? This will force cargo to stick to one process. It might take a bit longer but should avoid the problem you encountered.

`cargo build --package gst-plugin-spotify --release --jobs 1`

**Comment by faspina** [comment]
> I had the same problem on my OrangePi. Have you tried adding the -- jobs 1 flag? This will force cargo to stick to one process. It might take a bit longer but should avoid the problem you encountered.
> 
> `cargo build --package gst-plugin-spotify --release --jobs 1`
> 
> Total compilation time on my OrangePi PC2 was 1.5 hours.

That worked very well. Thank you!
