### ISSUE TITLE
Problem with getting tracks from playlist

### ISSUE THREAD

**Issue by TCke83** [mopidy/mopidy-spotify#373]
According to following API doc:

https://docs.mopidy.com/en/latest/api/core/#mopidy.core.PlaylistsController.lookup

i should be able to get the tracks of the playlist, i see following log in moidy:

`DEBUG    2024-01-30 20:12:12,672 [41017:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.116.109: '{"id":11,"jsonrpc":"2.0","method":"core.playlists.lookup","params":{"uri":"spotify:playlist:3ubAuVo0RldsGEogXJTOAS"}}'
DEBUG    2024-01-30 20:12:12,674 [41017:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.playlists
  Fetching Spotify playlist "'spotify:playlist:3ubAuVo0RldsGEogXJTOAS'"
DEBUG    2024-01-30 20:12:13,055 [41017:SpotifyBackend-3 (_actor_loop)] urllib3.connectionpool
  https://api.spotify.com:443 "GET /v1/playlists/3ubAuVo0RldsGEogXJTOAS?fields=name%2Cowner.id%2Ctype%2Curi%2Csnapshot_id%2Ctracks%28next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29%29%2C&market=from_token HTTP/1.1" 304 0
DEBUG    2024-01-30 20:12:13,058 [41017:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.utils
  playlists.lookup('spotify:playlist:3ubAuVo0RldsGEogXJTOAS') took 383ms
DEBUG    2024-01-30 20:12:13,059 [41017:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.116.109: '{"jsonrpc": "2.0", "id": 11, "result": null}'`

It seems to me something is going wrong while fetching the tracks in the playlist, is this a known issue?

This is used in a custom app I use to control the mopidy playlist, the listing of all playlists still works fine.

I used to add the playlist as a whole using following api:

https://docs.mopidy.com/en/latest/api/core/#mopidy.core.TracklistController.add

But this seems broken, i used to give the playlist uri to this method and it would add all the tracks of the playlist, i thought this was due to the rewrite of the library, but i could be wrong, maybe this functionality also should still work.

Any pointers on what could be wrong?

Thanks in advance.

Tom

**Comment by kingosticks** [comment]
Do you have the very latest code from here? I fixed some changes in their API a few weeks back.

**Comment by Man-Grove** [comment]
Do note that installation of the "main" package on Debian 12 now requires --break-system-packages, i.e.

`python3 -m pip install --break-system-packages -I https://github.com/mopidy/mopidy-spotify/archive/master.zip`

I just upgraded from Debian 11 to 12, and I also got weird tracklist problems, delving into this resulted in it was because the plugin was gone. Now with the latest branch reinstalled everything is working again.

**Comment by kingosticks** [comment]
An excellent point, thanks @Man-Grove. Have added to the readme. We really need to get this change out to all the extensions. It's a bit annoying.

**Comment by TCke83** [comment]
I've updated the installation, but issue stil remains.

`DEBUG    2024-02-05 19:11:58,697 [842:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.116.109: '{"id":8,"jsonrpc":"2.0","method":"core.playlists.lookup","params":{"uri":"spotify:playlist:3ubAuVo0RldsGEogXJTOAS"}}'
DEBUG    2024-02-05 19:11:58,699 [842:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.playlists
  Fetching Spotify playlist "'spotify:playlist:3ubAuVo0RldsGEogXJTOAS'"
TRACE    2024-02-05 19:11:58,699 [842:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web
  Fetching page 'playlists/3ubAuVo0RldsGEogXJTOAS'
TRACE    2024-02-05 19:11:58,700 [842:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web
  Get 'playlists/3ubAuVo0RldsGEogXJTOAS?fields=name%2Cowner.id%2Ctype%2Curi%2Csnapshot_id%2Ctracks%28next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29%29%2C&market=from_token'
TRACE    2024-02-05 19:11:58,701 [842:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web
  Cached data expired for URL: https://api.spotify.com/v1/playlists/3ubAuVo0RldsGEogXJTOAS?fields=name%2Cowner.id%2Ctype%2Curi%2Csnapshot_id%2Ctracks%28next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29%29%2C&market=from_token expires at: 2024-02-05 19:11:22.654307 [ETag: "MC-IjcyNDY5NDRhZTdiYTBmM2ZkZGI5MGMyYTlkMmVhYWY3Ig=="]
DEBUG    2024-02-05 19:11:59,136 [842:SpotifyBackend-3 (_actor_loop)] urllib3.connectionpool
  https://api.spotify.com:443 "GET /v1/playlists/3ubAuVo0RldsGEogXJTOAS?fields=name%2Cowner.id%2Ctype%2Curi%2Csnapshot_id%2Ctracks%28next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29%29%2C&market=from_token HTTP/1.1" 304 0
TRACE    2024-02-05 19:11:59,138 [842:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web
  New WebResponse URL: https://api.spotify.com/v1/playlists/3ubAuVo0RldsGEogXJTOAS?fields=name%2Cowner.id%2Ctype%2Curi%2Csnapshot_id%2Ctracks%28next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29%29%2C&market=from_token expires at: 2024-02-05 19:11:59.138613 [ETag: "MC-ImQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0MjdlIg=="]
TRACE    2024-02-05 19:11:59,139 [842:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web
  ETag match for URL: https://api.spotify.com/v1/playlists/3ubAuVo0RldsGEogXJTOAS?fields=name%2Cowner.id%2Ctype%2Curi%2Csnapshot_id%2Ctracks%28next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29%29%2C&market=from_token expires at: 2024-02-05 19:11:22.654307 [ETag: "MC-IjcyNDY5NDRhZTdiYTBmM2ZkZGI5MGMyYTlkMmVhYWY3Ig=="] URL: https://api.spotify.com/v1/playlists/3ubAuVo0RldsGEogXJTOAS?fields=name%2Cowner.id%2Ctype%2Curi%2Csnapshot_id%2Ctracks%28next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29%29%2C&market=from_token expires at: 2024-02-05 19:11:59.138613 [ETag: "MC-ImQ0MWQ4Y2Q5OGYwMGIyMDRlOTgwMDk5OGVjZjg0MjdlIg=="]
DEBUG    2024-02-05 19:11:59,140 [842:SpotifyBackend-3 (_actor_loop)] mopidy_spotify.utils
  playlists.lookup('spotify:playlist:3ubAuVo0RldsGEogXJTOAS') took 440ms
DEBUG    2024-02-05 19:11:59,141 [842:HttpServer] mopidy.http.handlers
  Sent WebSocket message to 192.168.116.109: '{"jsonrpc": "2.0", "id": 8, "result": null}'
`

The logging however seems to be more extensive, but the result still is null.

Any suggestions what could cause this?

**Comment by kingosticks** [comment]
Try `--upgrade` because I can see from that log snippet that's not the very latest version.

**Comment by TCke83** [comment]
@kingosticks thanks, that worked!
