### ISSUE TITLE
Accessing playlists in Iris terminates Mopidy

### ISSUE THREAD

**Issue by Flattermann78** [mopidy/mopidy-spotify#392]
Using Iris, browsing the playlists causes Mopidy to terminate. Versions used are as follows:

Mopidy==3.4.2
Mopidy-Spotify==5.0.0a1
GStreamer Spotify Plugin 0.13.0-RELEASE

Using the search dialog, I can select and play lists. It is more about the playlists provided through Spotify like "Featured Lists" "2000er Hits" or "80er Hits". The effect is not immediately but takes around 10 seconds until program termination.
[log.txt](https://github.com/user-attachments/files/16401654/log.txt)

**Comment by kingosticks** [comment]
I thought iris provided playlists itself and didn't use Mopidy-spotify for that content. Is it crashing when you try and play them or when you browse them? Can you provide exact steps for me to reproduce?

**Comment by Flattermann78** [comment]
Iris provides for playlists from Spotify. As soon as I select Browse (under My Music), browse into the Spotify-Lists and select Playlists/Featured, the system takes around 10 s and reboots

<img width="797" alt="Bildschirmfoto 2024-07-28 um 16 36 10" src="https://github.com/user-attachments/assets/86cd2022-2356-494b-8d6c-2d55116a7cc6">

**Comment by Flattermann78** [comment]
I also put a [Bug Report with Iris](https://github.com/jaedb/Iris/issues/961) as I wasn't sure wich component is responsible for the behavior I see.

**Comment by kingosticks** [comment]
Nothing reboots in this log. Mopidy is terminating in response to SIGTERM. Mopidy doesn't send itself SIGTERM so this is something outside of Mopidy. Do you have some kind of watchdog running that thinks Mopidy has crashed (it hasn't)?

**Comment by kingosticks** [comment]
> As soon as I see the following lists, Mopidy starts to download Spotify content like

As a side note, specifically, it is Iris that is requesting full playlist info for all playlists in the browse response. This is slow and potentially pointless. It is akin to reading the full contents of every file as you move between the directories in your filesystem. It would be good if they could do something more optimal here as this data isn't pre-loaded at startup and the cache will be empty.

**Comment by Flattermann78** [comment]
You're right! There was a watchdog and I feel stupid. After removing the watchdog, Mopidy works again. I agree that the Iris requests are rather slow creating warnings in the Iris UI.

Thank you!
