### ISSUE TITLE
GStreamer error: Could not demultiplex stream.

### ISSUE THREAD

**Issue by Ashkky** [mopidy/mopidy-spotify#396]
hey I've got this new error starting today making me unable to play the majority of music on spotify which i havent been able to find the soultion to?

Any advice would be appreciated!!

config:

[core]
#cache_dir = /cache
#config_dir = $XDG_CONFIG_DIR/mopidy
#data_dir = /cache/httppp
#max_tracklist_length = 10000
#restore_state = true

[logging]
#verbosity = 3
#format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
#color = true
#config_file = /home/tower-linux/log

[audio]
#mixer = software
#mixer_volume =
output = audioresample ! audio/x-raw,rate=48000,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/run/snapserver/snapfifo
#buffer_time =

[proxy]
#scheme =
#hostname =
#port =
#username =
#password =

[file]
enabled = true
media_dirs = /server/Phone/music

#excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
 .zip
#show_dotfiles = false
#follow_symlinks = false
#metadata_timeout = 1000

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true
default_app = mopidy

[m3u]
#enabled = true
#base_dir = $XDG_MUSIC_DIR
#default_encoding = latin-1
#default_extension = .m3u8
#playlists_dir =

[softwaremixer]
#enabled = true

[stream]
enabled = false
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = http://*:8095/*
timeout = 5000

[spotify]
enabled = true
username = XXXXXXXX
password = XXXXX
client_id = XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
client_secret =  XXXXXXXXXXXXXXXXXXXXXXXXXX
bitrate = 320
#volume_normalization = true
#private_session = false
#timeout = 10
#allow_cache = true
#allow_network = true
#allow_playlists = true
#search_album_count = 20
#search_artist_count = 10
#search_track_count = 50
#toplist_countries =

[mpd]
#enabled = true
hostname = ::
port = 6600
#password =
#max_connections = 20
#connection_timeout = 60
#zeroconf = Mopidy MPD server on $hostname
#command_blacklist =
#  listall
#  listallinfo
#default_playlist_scheme = m

log:

Sep 02 17:07:48 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: INFO     [HttpFrontend-10 (_actor_loop)] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Sep 02 17:07:48 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::]:6600
Sep 02 17:07:48 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Sep 02 17:08:13 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not demultiplex stream.
Sep 02 17:08:16 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: ERROR    [SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web Retrying https://api.spotify.com/v1/tracks/1QBwk6GTCxVdC2hoSw9tlM?market=from_token in 2.000 seconds.
Sep 02 17:08:16 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: ERROR    [Thread-6 (_refresh_tracks)] mopidy_spotify.web Retrying https://api.spotify.com/v1/playlists/3uCrJqbu0mTEnR7ypIJQd4/tracks?fields=next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29&limit=100&market=from_token&offset=1300 in 2.000 seconds.
Sep 02 17:08:18 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: ERROR    [SpotifyBackend-3 (_actor_loop)] mopidy_spotify.web Retrying https://api.spotify.com/v1/tracks/1QBwk6GTCxVdC2hoSw9tlM?market=from_token in 1.000 seconds.
Sep 02 17:08:18 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: ERROR    [Thread-6 (_refresh_tracks)] mopidy_spotify.web Retrying https://api.spotify.com/v1/playlists/3uCrJqbu0mTEnR7ypIJQd4/tracks?fields=next%2Citems%28track%28type%2Curi%2Cname%2Cduration_ms%2Cdisc_number%2Ctrack_number%2Cartists%2Calbum%2Cis_playable%2Clinked_from.uri%29%29&limit=100&market=from_token&offset=1300 in 1.000 seconds.
Sep 02 17:08:20 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Could not demultiplex stream.
Sep 02 17:08:32 towerlinux-Standard-PC-Q35-ICH9-2009 mopidy[5025]: INFO     [Thread-6 (_refresh_tracks)] mopidy_spotify.playlists Refreshed 85 Spotify playlists

**Comment by kingosticks** [comment]
Could you get a debug log for that, I can't even see what you're trying to play here

**Comment by svanrossem** [comment]
I'm experiencing the same error.
```
0:00:32.051280307     1 0x7fb09c014ba0 DEBUG        spotifyaudiosrc audio/spotify/src/spotifyaudiosrc/imp.rs:375:gstspotify::spotifyaudiosrc::imp::SpotifyAudioSrc::setup::{{closure}}:<source> Requesting bitrate Bitrate160
0:00:32.098575432     1 0x7fb0e8001560 DEBUG        spotifyaudiosrc audio/spotify/src/spotifyaudiosrc/imp.rs:256:<gstspotify::spotifyaudiosrc::imp::SpotifyAudioSrc as gstreamer_base::subclass::push_src::PushSrcImpl>::create:<source> eos
ERROR    2024-09-03 04:46:27,146 [1:MainThread] mopidy.audio.gst
  GStreamer error: Could not demultiplex stream.
DEBUG    2024-09-03 04:46:27,146 [1:MainThread] mopidy.audio.gst
  Got ERROR bus message: error=GLib.Error('Could not demultiplex stream.', 'gst-stream-error-quark', 9) debug='../ext/ogg/gstoggdemux.c(4775): gst_ogg_demux_send_event (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstOggDemux:oggdemux0:\nEOS before finding a chain'
0:00:32.102550694     1 0x555e0711fd00 DEBUG        spotifyaudiosrc audio/spotify/src/spotifyaudiosrc/imp.rs:191:<gstspotify::spotifyaudiosrc::imp::SpotifyAudioSrc as gstreamer_base::subclass::base_src::BaseSrcImpl>::stop:<source> stopping
```

**Comment by kingosticks** [comment]
Spotify changed something yesterday and librespot (which gst-plugin-spotify uses) is currently broken. There are two workarounds:
1. https://github.com/librespot-org/librespot/issues/972#issuecomment-2320943137
2. Compile your own verison of gst-plugin-spotify using the dev branch of librespot

**Comment by kingosticks** [comment]
I've built some new packages using the latest dev branch of librespot, feel free to test them https://github.com/kingosticks/gst-plugins-rs-build/actions/runs/10679959699

**Comment by Ashkky** [comment]
Hey man appricate the reply 

Ive loaded it a fresh instance of linux and on my live server and on both the fix doesn't seem to work.

mopidy just crashed whenever i try and play a spotify track  


Log:

Sep 03 19:26:58 multiroomcontroller mopidy[2516]: INFO     [HttpFrontend-10 (_actor_loop)] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Sep 03 19:26:58 multiroomcontroller mopidy[2516]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::]:6600
Sep 03 19:26:58 multiroomcontroller mopidy[2516]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Sep 03 19:27:30 multiroomcontroller mopidy[2516]: thread '<unnamed>' panicked at audio/spotify/src/spotifysrcbin/imp.rs:63:72:
Sep 03 19:27:30 multiroomcontroller mopidy[2516]: called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to find element factory with name 'textahead' for creating element", filename: "/github/home/.cargo/git/checkouts/gstreamer-rs-79e52a2d27eb91a3/61c6e81/gstreamer/src/element_factory.rs", function: "gstreamer::element_factory::ElementBuilder::build::{{closure}}", line: 286 }
Sep 03 19:27:30 multiroomcontroller mopidy[2516]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 03 19:27:30 multiroomcontroller mopidy[2516]: fatal runtime error: failed to initiate panic, error 5
Sep 03 19:27:30 multiroomcontroller systemd[1]: mopidy.service: Main process exited, code=dumped, status=6/ABRT
Sep 03 19:27:30 multiroomcontroller systemd[1]: mopidy.service: Failed with result 'core-dump'.
Sep 03 19:27:30 multiroomcontroller systemd[1]: mopidy.service: Consumed 3.189s CPU time, 71.4M memory peak, 0B memory swap peak.
~
~
~
~
[mopidy.log](https://github.com/user-attachments/files/16854055/mopidy.log)

**Comment by Ashkky** [comment]
Your supposed to add the .SO file to the /var/lib?
becasue thats what i did with it

**Comment by kingosticks** [comment]
There are deb files for 3 architecture there. Install the correct one for your system. If it crashes, you probably used the wrong one.

**Comment by kingosticks** [comment]
OK, please find new binaries/packages at https://github.com/kingosticks/gst-plugins-rs-build/actions/runs/10691809002

I've tested the x86_64 package and it's working for me.

**Comment by Ashkky** [comment]
Bro you've done it

the player works again!!!

thank you sm

**Comment by pvincent4** [comment]
Congratulation, thanks ;)
