### ISSUE TITLE
Add disc number to album and track models

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy-spotify#4]
See https://github.com/mopidy/mopidy/issues/317 for previous state.

> See @trygveaa's comment in https://github.com/mopidy/mopidy/issues/286 for some details on what must be done wrt. album browse, etc.

**Comment by kingosticks** [comment]
We've [supported disc number](https://github.com/mopidy/mopidy-spotify/blob/de6063219c3cc0af1918672618c98f94f48744a3/src/mopidy_spotify/translator.py#L256) for a while now, I think this is solved.
