### ISSUE TITLE
The package for mopidy-spotify is not available on your repo

### ISSUE THREAD

**Issue by pitsi** [mopidy/mopidy-spotify#403]
I am on debian (not raspbian) 11 (bullseye) on arm64 and I want to install mopidy-spotify from your repo because it is not. I followed the relevant instructions to the letter and added your repo and the required key.

However, as you can see below, there is no mopidy spotify anywhere in the repo, so how do I install it now? I do not want to resort to pip and python for that, because I keep my system clean of such installations.
```
# apt-cache search mopidy-spotify
# (no output, returns to the prompt)
```
It is also missing from the pool folder of the repo, which lists all packages regardless of distro version and architecture.
https://apt.mopidy.com/pool/

Proof that the installation is indeed plain debian 11 on arm64
```
# lsb_release -d && uname -m
Description:    Debian GNU/Linux 11 (bullseye)
aarch64
```

**Comment by kingosticks** [comment]
>  I do not want to resort to pip and python for that, because I keep my system clean of such installations.

The only working version of Mopidy-Spotify is the one that is installed from source, as the project README states. If you don't want to install from source then you'll have to wait for the next release.

**Comment by pitsi** [comment]
Thank you for the quick reply.

If pip is currently the only way to install it, can you please add a notification about it here? I had not read the readme in github because I thought the instructions here would work.
https://mopidy.com/ext/spotify/

Also, I was about to try soundcloud. Can you tell me if it does work? Because pressing the relevant button on its page to get the key results in an empty page saying "oops, something went wrong".
