### ISSUE TITLE
5.0.0 installation instructions need clarifications

### ISSUE THREAD

**Issue by vincentleycuras** [mopidy/mopidy-spotify#404]
Hi,

I seem to have broken my install - is it possible to indicate what the output of gst-inspect-1.0 spotify should be?

I am getting this output:
```
Plugin Details:
  Name                     spotify
  Description              GStreamer Spotify Plugin
  Filename                 /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstspotify.so
  Version                  0.12.0-alpha.1-245185d
  License                  MPL
  Source module            gst-plugin-spotify
  Source release date      2023-10-06
  Binary package           gst-plugin-spotify
  Origin URL               https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs

  spotifyaudiosrc: Spotify source

  1 features:
  +-- 1 elements
```

and sudo mopidyctl deps returns:
```
...
GStreamer: 1.18.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.38.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
```
(so nothing for Spotify)

Thanks

**Comment by kingosticks** [comment]
Ideally it'd show something, which yours does. But your version isn't the latest: https://github.com/kingosticks/gst-plugins-rs-build/releases/tag/gst-plugin-spotify_0.13.1-1

I can't tell from what you've posted what's wrong. Please describe the actual problem.

**Comment by vincentleycuras** [comment]
Thanks kingosticks - spotify tracks won't play, at a high level, this is what i am seeing. In the Mopidy log I'm seeing:

```
Oct 05 08:32:15 l1-ap2 mopidy[17177]: DEBUG    [HttpServer] mopidy.http.handlers Received WebSocket message from 192.168.1.107: '{"method":"core.tracklist.add","params":{"uris":["spotify:album:5quMTd5zeI9yW5UDua8wS4"],"at_position":0},"jsonrpc":"2.0","id":12}'
Oct 05 08:32:15 l1-ap2 mopidy[17177]: DEBUG    [HttpServer] mopidy.http.handlers Sent WebSocket message to 192.168.1.107: '{"jsonrpc": "2.0", "id": 12, "result": []}'
```

Sorry that's not a lot to go on... is there any value in doing a fresh install? The last version i had working (of the Spotify plugin) was 4.1.1, which stopped about 2 weeks ago (seems to be a known issue).

Thanks again

**Comment by kingosticks** [comment]
If you had a previously working installation it should still be working as there would have already been a cached credentials file for it to login with, and avoid username/password login no longer working. I think the current Mopidy-Spotify pre-release along with the current gst-plugin-spotify release should work together, unless you've removed your Spotify data directory that contains the cached login. 

In any case, you should be able to get a more useful debug message if you run Mopidy like `GST_DEBUG=*spot*:6 mopidy.

A new version is due to be released with these login issues fixed but I'm not going to get round to it tonight.

**Comment by vincentleycuras** [comment]
Thanks - i will try downgrading first and wait for the new version to be released
