### ISSUE TITLE
No matching distribution found for Mopidy-Spotify==5.0.0a3

### ISSUE THREAD

**Issue by gh-nom** [mopidy/mopidy-spotify#411]
I want to using  Mopidy-Spotify for ubuntu 22.04 . I have a issue 

Linux ghnomserver 5.4.0-189-generic #209-Ubuntu SMP Fri Jun 7 14:05:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

`$ sudo python3 -m pip install Mopidy-Spotify==5.0.0a3
ERROR: Could not find a version that satisfies the requirement Mopidy-Spotify==5.0.0a3 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.3.0, 1.4.0, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 3.0.0, 3.1.0, 4.0.0a1, 4.0.0a2, 4.0.0a3, 4.0.0, 4.0.1, 4.1.0, 4.1.1)
ERROR: No matching distribution found for Mopidy-Spotify==5.0.0a3`

**Comment by kingosticks** [comment]
Sorry, try adding `--pre`. A bit sad you're the first to run into this.

**Comment by kingosticks** [comment]
Actually, less sad, I think this might just be how old versions of pip behave (fixed in https://github.com/pypa/pip/pull/11124). Presumably this is the ancient version that came with 22.04.
