### ISSUE TITLE
Spotify browsing gives "No tracks found..."

### ISSUE THREAD

**Issue by liftarn** [mopidy/mopidy-spotify#42]
I go in Browsing -> Spotify Browse and select, for instance, Featured playlists. I click on any of them and all I get is "No tracks found..."
The same for top lists, "Genres & Moods" and so on.

**Comment by jodal** [comment]
Which version of Mopidy-Spotify and Mopidy-Spotify-Tunigo do you use? Run `mopidy deps` to check.

**Comment by liftarn** [comment]
I use whatever is bundled in Pi MusicBox 0.5.3

**Comment by kingosticks** [comment]
Can you login and run `mopidy deps` so we know exactly what version that is?

**Comment by liftarn** [comment]
Platform: Linux-3.12.28+-armv6l-with-debian-7.6
Python: CPython 2.7.3 from /usr/lib/python2.7
Mopidy: 0.19.5 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
    certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
    backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
Mopidy-MusicBox-Webclient: 1.0.3 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
Mopidy-Dirble: 0.1.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  pycountry: 1.10 from /usr/local/lib/python2.7/dist-packages
Mopidy-GMusic: 0.3.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  gmusicapi>=4.0.0: 4.1.0.dev0 from /usr/local/lib/python2.7/dist-packages
    validictory!=0.9.2,>=0.8.0: 0.9.3 from /usr/local/lib/python2.7/dist-packages
    decorator>=3.3.1: 3.4.0 from /usr/local/lib/python2.7/dist-packages
    mutagen>=1.18: 1.24 from /usr/local/lib/python2.7/dist-packages
    protobuf>=2.4.1: 2.6.0 from /usr/local/lib/python2.7/dist-packages
      setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    requests!=1.2.0,!=2.2.1,>=1.1.0: 2.5.1 from /usr/local/lib/python2.7/dist-packages
    python-dateutil!=2.0,>=1.3: 2.2 from /usr/local/lib/python2.7/dist-packages
      six: 1.8.0 from /usr/local/lib/python2.7/dist-packages
    proboscis>=1.2.5.1: 1.2.6.0 from /usr/local/lib/python2.7/dist-packages
    oauth2client>=1.1: 1.2 from /usr/local/lib/python2.7/dist-packages
      httplib2>=0.8: 0.9 from /usr/local/lib/python2.7/dist-packages
    mock>=0.7.0: 1.0.1 from /usr/local/lib/python2.7/dist-packages
    appdirs>=1.1.0: 1.4.0 from /usr/local/lib/python2.7/dist-packages
Mopidy-Podcast-gpodder.net: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Mopidy-Podcast>=1.0.0: 1.1.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
      setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
      Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
      tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
        certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
        backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1.0: 1.2.0 from /usr/lib/python2.7/dist-packages
    cachetools>=0.7.0: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    uritools>=0.8.0: 0.11.0 from /usr/local/lib/python2.7/dist-packages
      ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
      ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0.0: 2.5.1 from /usr/local/lib/python2.7/dist-packages
Mopidy-Local-Whoosh: 0.1.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Whoosh>=2.0: 2.6.0 from /usr/local/lib/python2.7/dist-packages
Mopidy-WebSettings: 0.1.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  ConfigObj>=4.0.0: 5.0.6 from /usr/local/lib/python2.7/dist-packages
    six: 1.8.0 from /usr/local/lib/python2.7/dist-packages
  Jinja2>=2.7: 2.7.3 from /usr/local/lib/python2.7/dist-packages
    markupsafe: 0.23 from /usr/local/lib/python2.7/dist-packages
Mopidy-Spotify: 1.2.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  pyspotify<1.999,>=1.9: 1.11 from /usr/local/lib/python2.7/dist-packages
Mopidy-Subsonic: 0.3.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  py-sonic: 0.3.2 from /usr/local/lib/python2.7/dist-packages
Mopidy-ALSAMixer: 1.0.3 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  pyalsaaudio: 0.7 from /usr/local/lib/python2.7/dist-packages
Mopidy-HTTP-Kuechenradio: 0.4.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
Mopidy-InternetArchive: 1.1.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1.0: 1.2.0 from /usr/lib/python2.7/dist-packages
  requests>=2.0.0: 2.5.1 from /usr/local/lib/python2.7/dist-packages
  cachetools>=0.6.0: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  uritools>=0.8.0: 0.11.0 from /usr/local/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
Mopidy-Local-SQLite: 0.8.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19.4: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  uritools>=0.10: 0.11.0 from /usr/local/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
Mopidy-SomaFM: 0.7.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  requests: 2.5.1 from /usr/local/lib/python2.7/dist-packages
Mopidy-Moped: 0.4.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
Mopidy-Simple-Webclient: 0.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19.4: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
Mopidy-Spotify-Tunigo: 0.2.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19.0: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  mopidy-spotify>=1.2.0: 1.2.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
      setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
      Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
      tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
        certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
        backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    pyspotify<1.999,>=1.9: 1.11 from /usr/local/lib/python2.7/dist-packages
  tunigo: 0.1.3 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    requests>=2.0.0: 2.5.1 from /usr/local/lib/python2.7/dist-packages
Mopidy-Mopify: 1.1.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Mopidy-Spotify>=1.2.0: 1.2.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
      setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
      Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
      tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
        certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
        backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    pyspotify<1.999,>=1.9: 1.11 from /usr/local/lib/python2.7/dist-packages
Mopidy-Scrobbler: 1.1.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  pylast>=0.5.7: 0.5.11 from /usr/lib/python2.7/dist-packages
Mopidy-Youtube: 1.0.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  requests>=2.2.1: 2.5.1 from /usr/local/lib/python2.7/dist-packages
  pafy>=0.3.35: 0.3.66 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
Mopidy-TuneIn: 0.1.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  requests>=2.0.0: 2.5.1 from /usr/local/lib/python2.7/dist-packages
Mopidy-Podcast-iTunes: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Mopidy-Podcast>=1.0.0: 1.1.0 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
      setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
      Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
      tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
        certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
        backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1.0: 1.2.0 from /usr/lib/python2.7/dist-packages
    cachetools>=0.7.0: 1.0.0 from /usr/local/lib/python2.7/dist-packages
    uritools>=0.8.0: 0.11.0 from /usr/local/lib/python2.7/dist-packages
      ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
      ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0.0: 2.5.1 from /usr/local/lib/python2.7/dist-packages
Mopidy-AudioAddict: 0.2.7 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  pycountry: 1.10 from /usr/local/lib/python2.7/dist-packages
Mopidy-SoundCloud: 1.2.5 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
  requests>=2.0.0: 2.5.1 from /usr/local/lib/python2.7/dist-packages
Mopidy-Podcast: 1.1.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 0.19.5 from /usr/local/lib/python2.7/dist-packages
    setuptools: 11.3.1 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/dist-packages
    tornado>=2.3: 4.0.2 from /usr/local/lib/python2.7/dist-packages
      certifi: 14.5.14 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.4.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1.0: 1.2.0 from /usr/lib/python2.7/dist-packages
  cachetools>=0.7.0: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  uritools>=0.8.0: 0.11.0 from /usr/local/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.7 from /usr/local/lib/python2.7/dist-packages
GStreamer: 0.10.36.0 from /usr/lib/python2.7/dist-packages/gst-0.10/gst
  Detailed information:
    Python wrapper: gst-python 0.10.22.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        flump3dec
        id3demux
        id3v2mux
        lame
        mad
        mp3parse
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        pulsesink

**Comment by jodal** [comment]
Looks like the latest versions, as of a few days ago.

@trygveaa Do you want to have a look at this?

**Comment by trygveaa** [comment]
It seems that the tunigo api doesn't support region=all anymore. which is what python-tunigo defaults to if region is not set. I'll fix it, and release a new version. In the mean time, a workaround is to set region in the mopidy config:

```
[spotify_tunigo]
region = no
```

I think it can be set to any two-letter country code (http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). At least no and us works.

**Comment by jodal** [comment]
@trygveaa Did you get around to fixing -tunigo?

**Comment by liftarn** [comment]
I put it as "se" and I can now browse. Still can't get any playlists or get it to play anything from Spotify.

**Comment by jodal** [comment]
This is a bug with [python-tunigo](https://github.com/trygveaa/python-tunigo), which is now tracked in trygveaa/python-tunigo#2.
