### ISSUE TITLE
Browsing of playlists

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-spotify#48]
To get a hierarchical view of the Spotify playlists, they should be made available through `library.browse()`.

If the `spotify/allow_playlists` config is set to `False`, playlists should not be present in `library.browse()`.

It may make sense to add a config for disabling playlists in the playlist view, and just show playlists through `browse()` to reduce noise in some MPD client UIs.

**Comment by kingosticks** [comment]
Spotify no longer providers playlist folders. And we do now provide browsing of non-user playlists (categories etc).
