### ISSUE TITLE
get_distinct() support (artist browsing in ncmpc)

### ISSUE THREAD

**Issue by David-Igou** [mopidy/mopidy-spotify#50]
Updated today (Mopidy 1.0.0-5, mopidy-spotify 1.3.0-1) and ncmpc no longer views lists artists via the respective tab. Searching and playlists work fine, but nothing is listed under artists.

**Comment by chigley** [comment]
+1. I've been a little slow to update, but am experiencing the same issue (mopidy-1.0.0-3, mopidy-spotify-1.3.0-0mopidy2).

**Comment by adamcik** [comment]
See the following extract from the Mopidy 1.0 changelog: 

> Add support for blacklisting MPD commands. This is used to prevent clients from using listall and listallinfo which recursively lookup the entire “database”. If you insist on using a client that needs these commands change [mpd/command_blacklist][0].

[0]: https://docs.mopidy.com/en/latest/ext/mpd/#confval-mpd/command_blacklist

Likely ncmpc, like ncmpcpp uses these bad commands that we are somewhat strongly trying to push clients away from by blacklisting them by default. So please check your ncmpc version if there is a never one that doesn't use these commands any more.

**Comment by trygveaa** [comment]
@adamcik: That is not the problem. ncmpc uses "list Artist", and this seems to return nothing from Spotify with Mopidy 1.0 and Mopidy-Spotify 1.3.

**Comment by adamcik** [comment]
Ok, in that case it sounds like we might have messed up something with respect to `get_distinct`

**Comment by adamcik** [comment]
Right, like outright forgetting to implement it...

**Comment by jodal** [comment]
I have some work in progress for a `get_distinct()` implementation for Mopidy-Spotify 2.0 that seems to work really nicely. The library view in ncmpc/ncmpcpp is actually very usable with this :-)
