### ISSUE TITLE
1.x: Model validation breakage

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy-spotify#52]
Model validation broke how mopidy-spotify constructs models. Simple fix should be  `date = str(spotify_album.year())` in the translators.

@jodal, if you don't have time to get m-s 2.x out before Mopidy 1.1 this needs to be fixed.

**Comment by jodal** [comment]
Fixed in 392c570936c2bd4ec99d7bab162106cffe82fbfc.
