### ISSUE TITLE
 Error: Ignoring unknown config section: spotify

### ISSUE THREAD

**Issue by jaypizzle** [mopidy/mopidy-spotify#53]
Sorry, I might be missing out something very obvious here, but can't figure this out.
I think I've installed mopidy and mopidy-spotify correctly, and I've added

[spotify]
username = myusername
password = mypassword

to the config file, but still, even after uninstalling and reinstalling, I keep getting this message (when running mopidy -vv):

DEBUG    2015-04-18 19:56:07,838 [27901:MainThread] mopidy.config
  Ignoring unknown config section: spotify

Which I guess it's what it's preventing the songs I select through mopify to actually load and play (there's no sign of any Spotify backend being started).

Any suggestion?

**Comment by adamcik** [comment]
Sounds like Mopidy-Spotify isn't installed right. Take a look at https://docs.mopidy.com/en/latest/troubleshooting/ and/or see what `mopidy deps` says.

**Comment by jaypizzle** [comment]
Thanks for the hint. Apparently it was an issue with how\where pip-installed and apt-installed packages are placed ([explanation from the Mopidy docs here](https://docs.mopidy.com/en/latest/installation/debian/#missing-extensions) in case someone else runs into this).
