### ISSUE TITLE
Cannot connect to spotify (Spotify login error)

### ISSUE THREAD

**Issue by Johnneke** [mopidy/mopidy-spotify#54]
```
[john@mfwsmusic mopidy]$ mopidy
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO     Starting Mopidy 1.0.4
INFO     Loading config from builtin defaults
INFO     Loading config from /home/john/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mopify, spotify, mpd, http, stream, spotify_tunigo, m3u, softwaremixer, moped, local, tunein, soundcloud
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: SpotifyBackend, StreamBackend, M3UBackend, LocalBackend, SpotifyTunigoBackend, TuneInBackend, SoundCloudBackend
INFO     Mopidy uses SPOTIFY(R) CORE
INFO     Audio output set to "autoaudiosink"
INFO     Loaded 0 M3U playlists from /home/john/.local/share/mopidy/m3u
INFO     No local library metadata cache found at /home/john/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [0.0.0.0]:6600
INFO     HTTP server running at [0.0.0.0]:6680
ERROR    Spotify login error: Cannot connect to Spotify
INFO     Disconnected from Spotify
```

I keep on getting disconnected from Spotify when I start Mopidy, I have triple checked my account details and they are definitely correct. Is there a way I can debug this?

**Comment by Johnneke** [comment]
Verbose logging:

DEBUG    2015-05-11 17:50:12,586 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:12.586 E [ap:1694] AP Socket Error: Timeout reached (20000)
DEBUG    2015-05-11 17:50:12,593 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:12.592 E [ap:3953] Connection error:  117
DEBUG    2015-05-11 17:50:12,599 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:12.599 I [ap:1752] Connecting to AP ap.spotify.com:4070
DEBUG    2015-05-11 17:50:12,611 [8050:SpotifyThread] pyspotify.manager.session
  Got message; processing events
DEBUG    2015-05-11 17:50:12,616 [8050:SpotifyThread] pyspotify.manager.session
  Will wait 284.735s for next message
DEBUG    2015-05-11 17:50:17,610 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:17.609 E [ap:1694] AP Socket Error: Timeout reached (20000)
DEBUG    2015-05-11 17:50:17,616 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:17.615 E [ap:3953] Connection error:  117
DEBUG    2015-05-11 17:50:17,623 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:17.622 I [ap:1752] Connecting to AP ap.spotify.com:443
DEBUG    2015-05-11 17:50:17,665 [8050:SpotifyThread] pyspotify.manager.session
  Got message; processing events
DEBUG    2015-05-11 17:50:17,670 [8050:SpotifyThread] pyspotify.manager.session
  Will wait 279.682s for next message
DEBUG    2015-05-11 17:50:22,634 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:22.633 E [ap:1694] AP Socket Error: Timeout reached (20000)
DEBUG    2015-05-11 17:50:22,639 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:22.639 E [ap:3953] Connection error:  117
DEBUG    2015-05-11 17:50:22,647 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:22.646 I [ap:1752] Connecting to AP ap.spotify.com:80
DEBUG    2015-05-11 17:50:22,663 [8050:SpotifyThread] pyspotify.manager.session
  Got message; processing events
DEBUG    2015-05-11 17:50:22,668 [8050:SpotifyThread] pyspotify.manager.session
  Will wait 274.683s for next message
DEBUG    2015-05-11 17:50:27,658 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:27.657 E [ap:1694] AP Socket Error: Timeout reached (20000)
DEBUG    2015-05-11 17:50:27,664 [8050:Dummy-5] mopidy_spotify.session_manager
  System message: 15:50:27.663 E [ap:3953] Connection error:  117
DEBUG    2015-05-11 17:50:27,713 [8050:SpotifyThread] pyspotify.manager.session
  Got message; processing events
ERROR    2015-05-11 17:50:27,720 [8050:SpotifyThread] mopidy_spotify.session_manager
  Spotify login error: Cannot connect to Spotify
INFO     2015-05-11 17:50:27,725 [8050:SpotifyThread] mopidy_spotify.session_manager
  Disconnected from Spotify

**Comment by jodal** [comment]
In summary: 

1. Tries to connect to some Spotify server, fails with error code 117.
2. Tries to connect to ap.spotify.com:4070, fails after 5s with error code 117.
3. Tries to connect to ap.spotify.com:443 (HTTPS port, probably trying to get around firewalls), fails after 
5s with error code 117.
4. Tries to connect to ap.spotify.com:80 (HTTP port, probably trying to get around firewalls), fails after 5s with error code 117.
5. Gives up.

Are you sure that you network was working properly? Maybe Spotify had some server issue? Spotify had some planned server maintenance at UTC 10:00 today, according to https://twitter.com/SpotifyStatus, but that doesn't coincide with the time of your bug report.

**Comment by Johnneke** [comment]
My issues were at a different timeframe than the planned maintenance, I'll retry tomorrow and verify the network connectivity first to see if I've missed something (although I have been updating my Arch Linux succesfully all day on the same box (so I doubt I had issues with connectivity).

**Comment by jodal** [comment]
Did you figure this out? Nothing I can do here at the moment, so I'm tempted to close this issue.

**Comment by Blackskyliner** [comment]
Spotify works for me, maybe it was an ISP issue at @Johnneke's end?

**Comment by nanox** [comment]
Check your DNS resolvers, and probe with nslookup test sjc1-accesspoint-***.ap.spotify.com
