### ISSUE TITLE
Login problems

### ISSUE THREAD

**Issue by pattyland** [mopidy/mopidy-spotify#56]
When I start modipy it disconnects from spotify:
> 2015-05-19 07:44:29,815 - ERROR    Spotify login error: Bad username and/or password
> 2015-05-19 07:44:29,820 - INFO     Disconnected from Spotify

I double checked my credentials in the config, it's all correct!
Are there any known problems with a maximal lenght or certain symbols?

**Comment by kingosticks** [comment]
There is an open musicbox issue with certain symbols that still hasn't been fixed. It's not a mopidy-spotify issue, it's a problem with our extra settings parser.

**Comment by kingosticks** [comment]
https://github.com/woutervanwijk/Pi-MusicBox/issues/217
