### ISSUE TITLE
Soundcloud Authentication Token

### ISSUE THREAD

**Issue by Veltridze** [mopidy/mopidy-spotify#57]
When using the mopidy site I am unable to get an authentication token and am given the error 'Error: 401 - Unauthorized'

**Comment by jodal** [comment]
This doesn't sound related to Mopidy-Spotify. Did you intend to file this
against the Mopidy-SoundCloud project?

**Comment by Veltridze** [comment]
Sorry had both windows open my mistake. I'll move this to mopidy soundcloud.
