### ISSUE TITLE
INFO Loaded Spotify Playlists 

### ISSUE THREAD

**Issue by RobHooper** [mopidy/mopidy-spotify#58]
Between the hours of 10 and 11 UTC the following message is constantly outputted from mopidy.
INFO     Loaded 30 Spotify playlists

During this time the songs don't stop playing, the current time on the song will go past the end time and it won't stop and I have to hit next for each song.

I have tried reloading the playlist and hitting next a lot of times but this didn't fix the issue.
Also how long the playlist has been running has no effect on this.

This has been going on for a good few months now.

Package details from dpkg -s
dpkg -s mopidy-spotify
Package: mopidy-spotify
Status: install ok installed
Priority: optional
Section: sound
Installed-Size: 130
Maintainer: Stein Magnus Jodal <stein.magnus@jodal.no>
Architecture: all
Version: 1.4.0-0mopidy1
Depends: python-pkg-resources, mopidy, python-pykka, python-spotify (<< 2), python (>= 2.7)

dpkg -s mopidy
Package: mopidy
Status: install ok installed
Priority: optional
Section: sound
Installed-Size: 901
Maintainer: Stein Magnus Jodal <stein.magnus@jodal.no>
Architecture: all
Version: 1.0.7-1
Depends: debconf (>= 0.5) | debconf-2.0, init-system-helpers (>= 1.18~), python (>= 2.7), python (<< 2.8), python-pkg-resources, python-pykka, python-tornado (>= 2.3), adduser, debconf, lsb-base, gstreamer0.10-plugins-good, python-gst0.10
Recommends: gstreamer0.10-alsa, gstreamer0.10-plugins-ugly, gstreamer0.10-pulseaudio, gstreamer0.10-tools
Suggests: mopidy-doc
Conffiles:
 /etc/logrotate.d/mopidy a8e64ce52001ba5c673af6789a6c78ea
 /etc/init.d/mopidy 3f5929723a2a438cc9a5f7589080bbb6
 /etc/mopidy/mopidy.conf 9598973e8ee5bf54f1a288ae8e505a35
 /etc/mopidy/logging.conf dbacd3800f63ef3c2a7135a6f3ee573d

Thanks :)

**Comment by kingosticks** [comment]
Have you tried deleting your cache? I expect you'll need to provide a debug log. Has it really been spamming that INFO message for months but only between the hours of 11 and 12?! Or is that part just a one off?

**Comment by RobHooper** [comment]
Just deleted the cache. Will get back to you tomorrow regarding the debug log.

I am not sure how long it has been spamming that message. I haven't really been looking into it until now. However it has done it the past few days.

**Comment by RobHooper** [comment]
Ok, it has just happened again. Log in the link below.
Around 10:10 you can see the spotify playlists being loaded.
http://pastebin.com/D6PgX7nf

**Comment by jodal** [comment]
Can you reproduce this with Mopidy-Spotify 2? It is a complete rewrite of Mopidy-Spotify, based on pyspotify 2, which is a complete rewrite of pyspotify.

**Comment by RobHooper** [comment]
I updated a few days ago and I haven't noticed any issues since.
This was a strange issue, happy it is resolved.
Thanks.

**Comment by jodal** [comment]
Thanks for the reply!
