### ISSUE TITLE
Mopidy pauses playback of local tracks when it loses connection to Spotify.

### ISSUE THREAD

**Issue by jamesbvaughan** [mopidy/mopidy-spotify#59]
I have a spotty internet connection at my house and Mopidy loses it's connection to Spotify quite frequently. (It gives this error: "ERROR    Spotify connection error: Can not connect to Spotify")

Each time this happens, it pauses the song that I'm listening to, even if it's from my local library. 

If this is a problem with Mopidy rather than Mopidy-Spotify, let me know and I'll create an issue there instead.

**Comment by jodal** [comment]
The error is from libspotify, and we necessarily need to stop Spotify playback if we don't have connectivity with Spotify. As for pausing local tracks too, that is already tracked in #1, and should be fixed in the upcoming Mopidy-Spotify 2.0 release.
