### ISSUE TITLE
Use remember me feature of libspotify for auth blob

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy-spotify#6]
See https://github.com/mopidy/mopidy/issues/305 previous state.

> As https://github.com/mopidy/mopidy/issues/116 points out we shouldn't be storing passwords in plain text. Since libspotify can give us an auth blob as a token to use to stay signed in without re-requesting the password be should look into adding this an alternative to storing the plain text password.
> 
> The flow if added would be to prompt the user for the missing credentials and then store the auth blob for use next time we log in. If the blob has expired we will of course need to log in again.

**Comment by deiwin** [comment]
:+1:

**Comment by kingosticks** [comment]
How would the login prompt work? Could mopidy-spotify have a login Command or include a very small web app?

**Comment by jodal** [comment]
I imagine a `mopidy spotify login` command which stores the auth blob to the config file.

**Comment by kingosticks** [comment]
So then it expires at some point, the next login fails and the backend is disabled (or remains in offline mode?). It'd be nice if Mopidy's API had a way to pass notifications up to the frontends.

**Comment by deiwin** [comment]
I'm unfamiliar with the codebase. I know this may seem unrelated, but can someone please explain what's happening [here with this prompt](https://github.com/mopidy/mopidy/blob/097172d57430badd5f745f1c75b0a5a71af929c0/mopidy/local/commands.py#L45)? How does the user access stdin there?

**Comment by jamietanna** [comment]
I think this can be closed, as Spotify now provides "device passwords" that users can use instead of their plaintext password. It can be accessed via the [account page](https://www.spotify.com/uk/account/overview/), under "Set a password for your devices", eliminating any need for plaintext passwords.

**Comment by jodal** [comment]
AFAIK, Spotify's "device passwords" are for those that have connected their Spotify accounts with their Facebook accounts. I have not, and thus I don't have the device password option.

**Comment by kingosticks** [comment]
libspotify is no more. We use a different library with a different login system now.
