### ISSUE TITLE
Sort browse according to Spotify order 

### ISSUE THREAD

**Issue by simmel** [mopidy/mopidy-spotify#67]
Would be nice to sort the playlists in the manual order that they are sorted in Spotify, not just alphabetical.

Would be fun to help doing this, so if you have any pointers I'm willing to dig in.

**Comment by jodal** [comment]
I believe Mopidy-Spotify returns the playlists in the order from Spotify. It may be that your web/MPD client sorts them, though. Have you tried with another client?

**Comment by simmel** [comment]
I get the same result in ncmpcpp and Theremin.

I have no config other than username and password for mopidy-spotify.

Maybe this is to "blame" mopidy/mopidy#1026 ?

This is a "screenshot" of how it looks in ncmpcpp:
```
Browse: /                                                          Volume: 96%
──────────────────────────────────────────────────────────────────────────────
[Files]
[Local media]
[Spotify]
playlist -
playlist - [2]
playlist - [3]
playlist Albums|...And You Will Know Us By The Trail Of Dead – Worlds Apart
playlist Albums|Alexisonfire – Watch Out!
playlist Albums|Anders Ilar - Stories of Old
[…]
```

**Comment by simmel** [comment]
Do you have any other client that I can "easily" test with on OS X?

**Comment by kingosticks** [comment]
mopidy/mopidy#1026 is specifically regarding local playlists, not spotify playlists.

Most webclients can be installed via pip: https://docs.mopidy.com/en/latest/ext/web/#ext-web
I think mopify (or at least the old version I have running) favours alphabetical order.

**Comment by simmel** [comment]
Sorry for the long delay, but Mopify also lists them in alphabetical order (not the order on Spotify).

And Mopify also doesn't show any "folders".

**Comment by simmel** [comment]
Very interesting though, this is the output when ncmpcpp requests the playlist:
```
DEBUG    2015-10-23 10:04:31,620 [7244:MpdSession-27] mopidy.mpd.session
  Request from [::1]:49766: lsinfo "/"
DEBUG    2015-10-23 10:04:31,683 [7244:MpdSession-27] mopidy.mpd.session
  Response to [::1]:49766:
    directory: Files
    directory: Local media
    directory: Spotify
    playlist: Starred
    Last-Modified: 2015-10-23T08:04:31Z
    playlist: Nytt|Pryda – PRYDA 10 VOL III
    Last-Modified: 2015-10-23T08:04:31Z
    playlist: Nytt|Anna Ternheim – Still A Beautiful Day
    Last-Modified: 2015-10-23T08:04:31Z
    playlist: Nytt|Caspian – Dust and Disquiet
    Last-Modified: 2015-10-23T08:04:31Z
[…]
```
so mopidy and mopidy-spotify seems to do the right thing. Weird that both ncmcpp and Mopify shows them in alphabetical order though.

**Comment by simmel** [comment]
AH! Now it works! I wonder if something has been changed in ncmpcpp, mopidy or mopidy-spotify since I tried the last time. Because now `browser_sort_mode = noop` in `.ncmpcpp/config` works but it didn't when I submitted this ticket.

**Comment by kingosticks** [comment]
Mopify gets some of its data by directly calling the Spotify Web API and
not through mopidy. So it's very likely to have different behaviour.

**Comment by simmel** [comment]
Ah, thank you for that explaination @kingosticks. I'll close this ticket now since I'm no longer experiencing this "bug".

Thanks for your support and dedication!
