### ISSUE TITLE
Unable to use spotify, errors on startup

### ISSUE THREAD

**Issue by riemers** [mopidy/mopidy-spotify#70]
Default install on mac via pip install, which automaticly adds it to my mopidy installation (something brew did not) but i get below error when i start it up with correct username/pwd and enabled. All other features work as expected, audio, web extensions etc etc.

``` python
ERROR    Unhandled exception in SpotifyBackend (urn:uuid:cfd4482b-a530-4ac3-9761-9287ad23e124):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/backend.py", line 53, in on_start
    self._session = self._get_session(self._config)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/backend.py", line 69, in _get_session
    session = spotify.Session(self._get_spotify_config(config))
  File "/usr/local/lib/python2.7/site-packages/spotify/__init__.py", line 58, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/spotify/session.py", line 60, in __init__
    self.config._sp_session_config, sp_session_ptr))
  File "/usr/local/lib/python2.7/site-packages/spotify/error.py", line 31, in maybe_raise
    raise LibError(error_type)
LibError: Unable to open trace file
ERROR    Actor died: SpotifyBackend (urn:uuid:cfd4482b-a530-4ac3-9761-9287ad23e124) stopped before handling the message
```

Also don't know where it tries to make a trace file, otherwise that might have showed something?

*Updated: Removed ref to unrelated GMusic bug. -jodal*

**Comment by jodal** [comment]
I'm fixing this in one in pyspotify now. New release out soon.

**Comment by riemers** [comment]
:+1:

**Comment by jodal** [comment]
pyspotify 2.0.5 is out now. It should fix this.

**Comment by riemers** [comment]
Thanks this seems to have fixed that issue. Installed it via pip install -e alreayd, only to get the next hurdle. "ERROR    Spotify login error: <ErrorType.OTHER_PERMANENT: 10>" but nothing on the internet states a root cause for this. But i assume this is coming back from spotify so in reality you cannot help with that am i correct?

**Comment by jodal** [comment]
That's a login error returned from Spotify's servers through libspotify and pyspotify. Check your username and password, and that you have a premium account. Also watch out for other log messages that might be more helpful.

**Comment by riemers** [comment]
Just verified userid/pwd with logging into spotify.com and the subcription status says "spotify premium" its payed account. I just run mopidy manually to see the messages, but no extra messages are present.

**Comment by jodal** [comment]
If you google "AP Socket Error: Host not found (20001)" it seems to be a general problem with Spotify and proxying. Let me know if anything indicates anything wrong in Mopidy-Spotify and/or pyspotify.

**Comment by riemers** [comment]
I just did a test, with direct connection without any proxy's. It works like a charm, so it has nothing to do with mopidy/psypotify. I also see its connecting through a non default proxy port to get to the AP so that will not work with the proxy in question here. Anyways, thanks for the quick help, i'll resort to other 'internet' connections to get this working.
