### ISSUE TITLE
In ncmpcpp, unable to enter the Album column

### ISSUE THREAD

**Issue by GregorySchwartz** [mopidy/mopidy-spotify#72]
Using mopidy with mopidy-spotify, local albums work find and one can enter from the left column to the middle column in the ncmpcpp media library. However, if the middle column highlighted album contains a spotify album with a date of 0, e.g. |Jerry Goldsmith|(0) A Patch of Blue|BLANK, then you are stuck in the left column and cannot enter the middle column at all. In the mopidy output, you are left with an endless loop of
`
INFO     Searching Spotify for: album:"A Patch Of Blue" year:0 artist:"Jerry Goldsmith"
INFO     Searching Spotify for: album:"A Patch Of Blue" year:0 artist:"Jerry Goldsmith"
INFO     Searching Spotify for: album:"A Patch Of Blue" year:0 artist:"Jerry Goldsmith"
`
etc. However, as you are stuck in the left column, you can still scroll away, but it's very inconvenient. Is there a way to remove those seemingly non-existent albums from the middle column? I can try to figure this out and work on it, but I would need a starting point of where to look.

**Comment by robin92** [comment]
I'm affected by this issue as well.

**Comment by marcaddeo** [comment]
Also having this issue, will have to look into the code at some point and see if I can put in a PR. Very inconvenient though :cry:

**Comment by jodal** [comment]
I'm not experiencing this issue with ncmpcpp 0.6.4. Are you running ncmpcpp 0.5.x?

**Comment by jodal** [comment]
Even though I didn't get stuck, I saw the albums with year 0, which didn't make much sense, so I made those albums have an unknown date instead.

**Comment by GregorySchwartz** [comment]
I am no longer experiencing this issue, thanks.
