### ISSUE TITLE
"AttributeError: __exit__" from ffi.gc() cleanup function

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-spotify#73]
Recently, the following stack trace is printed when exiting Mopidy. This did not use to happen. I'm unsure what has changed.

This looks like a race between the `ffi.gc()` cleanup functions and Python teardown.

```
From callback for ffi.gc <cdata 'struct sp_track *' 0x7fe68c09cd40>:
Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/spotify/__init__.py", line 57, in wrapper
    with _lock:
AttributeError: __exit__
```

**Comment by adamcik** [comment]
@PAStheLoD this is likely the same or related issue to https://github.com/mopidy/mopidy/issues/1390 which you filed.

**Comment by trygveaa** [comment]
I can't say that I understand why, but this seems to fix the issue. I figured it out by bisecting and finding that ddf2485 introduced the issue.

```
diff --git a/mopidy_spotify/library.py b/mopidy_spotify/library.py
index 8be624e..931cd40 100644
--- a/mopidy_spotify/library.py
+++ b/mopidy_spotify/library.py
@@ -4,8 +4,7 @@ import logging
 
 from mopidy import backend
 
-import mopidy_spotify
-from mopidy_spotify import browse, distinct, images, lookup, search, utils
+from mopidy_spotify import browse, distinct, images, lookup, search, utils, __version__, Extension
 
 
 logger = logging.getLogger(__name__)
@@ -20,8 +19,8 @@ class SpotifyLibraryProvider(backend.LibraryProvider):
         self._requests_session = utils.get_requests_session(
             proxy_config=backend._config['proxy'],
             user_agent='%s/%s' % (
-                mopidy_spotify.Extension.dist_name,
-                mopidy_spotify.__version__))
+                Extension.dist_name,
+                __version__))
 
     def browse(self, uri):
         return browse.browse(self._config, self._backend._session, uri)
```

Does this give you any idea of what's wrong? Should we do this, or something else?

**Comment by adamcik** [comment]
The `import mopidy_spotify` seems to be the trigger.

**Comment by adamcik** [comment]
Or that is keeping that object around is the problem.

**Comment by adamcik** [comment]
This seems to fix it, any one care to double check before we push the change?

```
diff --git a/mopidy_spotify/library.py b/mopidy_spotify/library.py
index 8be624e..a71d15a 100644
--- a/mopidy_spotify/library.py
+++ b/mopidy_spotify/library.py
@@ -10,6 +10,10 @@ from mopidy_spotify import browse, distinct, images, lookup, search, ut
 
 logger = logging.getLogger(__name__)
 
+_dist_name = mopidy_spotify.Extension.dist_name
+_version = mopidy_spotify.__version__
+del mopidy_spotify
+
 
 class SpotifyLibraryProvider(backend.LibraryProvider):
     root_directory = browse.ROOT_DIR
@@ -19,9 +23,7 @@ class SpotifyLibraryProvider(backend.LibraryProvider):
         self._config = backend._config['spotify']
         self._requests_session = utils.get_requests_session(
             proxy_config=backend._config['proxy'],
-            user_agent='%s/%s' % (
-                mopidy_spotify.Extension.dist_name,
-                mopidy_spotify.__version__))
+            user_agent='%s/%s' % (_dist_name, _version))
 
     def browse(self, uri):
         return browse.browse(self._config, self._backend._session, uri)
```

**Comment by trygveaa** [comment]
Verified, that fixes it as well.

**Comment by kingosticks** [comment]
Yep, for me too. Thanks @trygveaa.

**Comment by clramirez** [comment]
hello, can you give a liitle help how to fix this?

**Comment by jodal** [comment]
As this isn't breaking any functionality, I suggest just waiting for the next release.

**Comment by jodal** [comment]
Workaround commited. Moving this to a later milestone for solving this properly, probably in pyspotify.

**Comment by kingosticks** [comment]
@jodal Did you solve this properly in https://github.com/mopidy/pyspotify/commit/298226a912be15c485c8c3503c06c7340eb23b93 ?

**Comment by jodal** [comment]
Yeah, I think that and this is basically the same issue. Same file, same line. Both in `ffi.gc()` object release callback. The only difference is how long the teardown of the process came before a `sp_*_release()` function call in pyspotify hit  In the latest case, it was `__enter__` on the lock's context manager. In this case, it managed to enter the lock but failed because `__exit__` was missing when it exited the lock.
