### ISSUE TITLE
Pausing breaks playback when using spotify-mopidy

### ISSUE THREAD

**Issue by fulaphex** [mopidy/mopidy-spotify#75]
When I pause and unpause music from mopidy-spotify extension it often crashes playback. The unpaused music doesn't play, the song progress bar goes quickly trough the song, next song is played back normally. I also get this warning:
`WARNING  Element doesn't implement handling of this stream. Please file a bug.`

**Comment by kingosticks** [comment]
I think this would have likely been fixed with https://github.com/mopidy/mopidy-spotify/commit/68512f6af6b7136f0cc3cfb5724d8061803f9f1a.
