### ISSUE TITLE
Unable to load playlists

### ISSUE THREAD

**Issue by luke831215** [mopidy/mopidy-spotify#76]
Hi there,
I can logged into Spotify online and offline, but had a problem loading playlists.
When I open mopify, It said 'Please connect with the Spotify service first'
![2015-11-02_025517](https://cloud.githubusercontent.com/assets/6273619/10870769/c857982c-810d-11e5-9f21-79bc6b0708a9.png)

Below is my config:

[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = mopidy.log
config_file =

[audio]
mixer = software
mixer_volume = 
output = autoaudiosink

[proxy]
#scheme = 
#hostname = 
#port = 
#username = 
#password = 

[spotify_tunigo]
enabled = true
region = all
cache_time = 3600

[spotify]
enabled = true
username = XXXXXXXXXXXX
password = XXXXXXXXXXXX
bitrate = 160
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries = 

[mpd]
enabled = true
hostname = ::
port = 6601
password = 
max_connections = 20
connection_timeout = 60
zeroconf = "" #Mopidy MPD server on $hostname
command_blacklist = 
  listall
  listallinfo

[http]
enabled = true
hostname = ::
port = 6681
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = 
timeout = 5000

[m3u]
enabled = true
playlists_dir = ~/.local/share/mopidy/m3u/

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs = 
  $XDG_MUSIC_DIR|$Music
  ~/|Home
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[local]
enabled = true
library = json
media_dir = media_dir
data_dir = media_dir/mopidy/local
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt

Any help is appreciated!! Plz

**Comment by luke831215** [comment]
Or is it just too slow?
![2015-11-02_030357](https://cloud.githubusercontent.com/assets/6273619/10870789/6f59d932-810e-11e5-8c67-ba37b20fb9e0.png)

**Comment by adamcik** [comment]
Connecting with spotify services is a mopify thing. It wants you to grant it's web frontend access to spotify within your browser. This has nothing to do with this extension or mopidy itself. So not much we can do here, try asking on the mopify issue tracker or perhaps https://discuss.mopidy.com

**Comment by luke831215** [comment]
Actually adamcik, i cang't get my modipy in the sound menu of ubuntu to run either.
![2015-11-02_012301](https://cloud.githubusercontent.com/assets/6273619/10870818/5568296a-810f-11e5-939a-20a81a0497c1.png)

So I'm guessing that Spotify isn't even connected or successfully installed. However, I did manage to get my http server done connected....
