### ISSUE TITLE
Mopidy / Mopidy-Spotify should have a configuration parameter to retrieve a password through a external command.

### ISSUE THREAD

**Issue by shymega** [mopidy/mopidy-spotify#84]
To the best of my knowledge, Mopidy currently uses plain text to store passwords, for example a Spotify password for mopidy-spotify.

Some tools like OfflineIMAP, or vdirsyncer have a option to use a external Python function to retrieve a password, or a built-in configuration option, respectively.

I think it would be a good idea if Mopidy could support a option to retrieve passwords from external methods, rather than relying on plaintext passwords inside configs.

**Comment by ZenithDK** [comment]
This is also partly covered by #6 and #76

**Comment by adamcik** [comment]
More importantly this should be a mopidy feature request IMO. Having each and every extension try and solve this would be a nightmare.

**Comment by fran-penedo** [comment]
The workaround provided here works fine for the time being: https://github.com/mopidy/mopidy/issues/116#issuecomment-18026012

**Comment by shymega** [comment]
OK then, I'll open a Mopidy issue in a little while, closing this for now as any further discussion should probably be on the new issue instead. Thanks @ZenithDK @adamcik @fran-penedo for your input.
