### ISSUE TITLE
Use unload track on stop?

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy-spotify#86]
Currently we seem to just pause. It would likely be more correct to unload.

**Comment by trygveaa** [comment]
On a related note, we don't call pause in Mopidy-Spotify when Mopidy is paused, so `session.player.state` is playing while Mopidy is paused. Should we do that?

**Comment by kingosticks** [comment]
The part @trygveaa mentions was fixed in https://github.com/mopidy/mopidy-spotify/commit/68512f6af6b7136f0cc3cfb5724d8061803f9f1a

**Comment by kingosticks** [comment]
No longer using libspotify.
